const CREOLE_ENGLISH_DICTIONARY = {
    'creole-en': {
        // Greetings and Basic Expressions
        'bonzour': 'hello',
        'sava': 'hi',
        'bonswar': 'good evening',
        'bonn nwi': 'good night',
        'aouarvoir': 'goodbye',
        'o byento': 'see you soon',
        'byenvini': 'welcome',
        'mèrsi': 'thank you',
        'si ou plé': 'please',
        'pardon': 'sorry',
        'ekskiz-mwa': 'excuse me',
        'dézolé': 'apologetic/sorry',
        'wi': 'yes',
        'non': 'no',
        'petèt': 'maybe',
        'byen sir': 'of course',
        'absoliman': 'absolutely',
        'mi pa koné': 'I don\'t know',
        'mi konprann': 'I understand',
        'mi pa konprann': 'I don\'t understand',
        'komman i alé': 'how are you',
        'i alé': 'it\'s going',
        'i alé byen': 'it\'s going well',
        'i alé mal': 'it\'s going badly',
        'pa problèm': 'no problem',
        'pa kwésyon': 'no question',
        'aplita': 'see you later',
        'bonapéti': 'enjoy your meal',
        'santé': 'health/cheers',
        'bon chans': 'good luck',
        'bonn anivèrsèr': 'happy birthday',
        'bon Nwèl': 'Merry Christmas',
        'bonn anné': 'Happy New Year',
        'mon ti aim': 'I love you',
        'mon ti kontan ou': 'I like you',
        'mon mank ou': 'I miss you',
        'pran swen dou': 'take care of yourself',
        'bon voyaz': 'have a good trip',
        'bon rétablisman': 'get well soon',
        'félicitasyon': 'congratulations',
        'ou plézi': 'nice to meet you',
        'o tou à lèr': 'see you later today',
        'o demin': 'see you tomorrow',
        'fé bèl rèv': 'sweet dreams',
        'pas bon zourné': 'have a good day',
        'bon wikenn': 'good weekend',
        'bon vakans': 'happy holidays',
        
        // Pronouns
        'mi': 'I',
        'ou': 'you',
        'li': 'he/she/it',
        'nou': 'we',
        'zot': 'you (plural)/they',
        'mwin': 'me',
        'la mwin': 'mine',
        'la tou': 'yours',
        'la li': 'his/hers/its',
        'lé mwin': 'mine (plural)',
        'lé tou': 'yours (plural)',
        'lé li': 'his/hers/its (plural)',
        'la notr': 'ours',
        'la votr': 'yours (formal/plural)',
        'la lor': 'theirs',
        'mon': 'my',
        'ma': 'my (feminine)',
        'mé': 'my (plural)',
        'ton': 'your',
        'ta': 'your (feminine)',
        'té': 'your (plural)',
        'son': 'his/her/its',
        'sa': 'his/her/its (feminine)',
        'sé': 'his/her/its (plural)',
        'notr': 'our',
        'no': 'our (plural)',
        'votr': 'your (formal/plural)',
        'vo': 'your (formal/plural, plural)',
        'lor': 'their',
        
        // Family
        'famill': 'family',
        'pèr': 'father',
        'mèr': 'mother',
        'paran': 'parents',
        'zanfan': 'child/children',
        'fiy': 'son/daughter',
        'frèr': 'brother',
        'sér': 'sister',
        'granpèr': 'grandfather',
        'granmèr': 'grandmother',
        'onkl': 'uncle',
        'tant': 'aunt',
        'kouzin': 'cousin (male/female)',
        'névé': 'nephew',
        'niès': 'niece',
        'épou': 'spouse (male)',
        'épous': 'spouse (female)',
        'mari': 'husband',
        'fanm': 'wife/woman',
        'mariaz': 'marriage',
        'marié': 'married (male/female)',
        'divors': 'divorce',
        'divorsé': 'divorced (male/female)',
        'sélibatèr': 'single (male/female)',
        'fiyansé': 'engaged (male/female)',
        'bopèr': 'father-in-law',
        'bèlmèr': 'mother-in-law',
        'bofrèr': 'brother-in-law',
        'bèlsér': 'sister-in-law',
        'zanndr': 'son-in-law',
        'bèlfiy': 'daughter-in-law',
        'bofiy': 'stepson',
        'bèlfamill': 'in-laws',
        'parrén': 'godfather',
        'maren': 'godmother',
        'fiyul': 'godson',
        'ansètr': 'ancestor',
        'déandan': 'descendant',
        'postérité': 'posterity',
        'zénérasyon': 'generation',
        'éritié': 'heir (male)',
        'érityèr': 'heir (female)',
        'orfan': 'orphan (male)',
        'orfanin': 'orphan (female)',
        'zomò': 'twin (male)',
        'zomòl': 'twin (female)',
        'aîné': 'elder (male/female)',
        'kadé': 'younger (male/female)',
        'benjamin': 'youngest (male/female)',
        'paranté': 'kinship',
        'lyen famiyal': 'family tie',
        'arbr zénéralojik': 'family tree',
        'mimbr': 'member',
        'proch': 'relative/close one',
        'titér': 'guardian (male)',
        'titris': 'guardian (female)',
        'protéjé': 'protégé (male/female)',
        'konpagnon': 'companion (male)',
        'konpagn': 'companion (female)',
        'parténèr': 'partner',
        'asosyé': 'associate (male/female)',
        'kolèg': 'colleague',
        'kamarad': 'comrade/friend',
        'lami': 'friend (male/female)',
        'kopén': 'buddy (male)',
        'kopin': 'buddy (female)',
        'voazén': 'neighbor (male)',
        'voazin': 'neighbor (female)',
        'konésans': 'acquaintance',
        'relasyon': 'relations',
        'kontak': 'contacts',
        'famill nikléèr': 'nuclear family',
        'famill élarzi': 'extended family',
        'ménaz': 'household',
        'foyé': 'home',
        'domicil': 'residence',
        'lakaz': 'house',
        
        // People
        'nonm': 'man',
        'moun': 'person',
        'zanmoun': 'people',
        'endividi': 'individual',
        'èr imen': 'human being',
        'pèrsonaz': 'character',
        'pèrsonalité': 'personality',
        'sélébrité': 'celebrity',
        'védèt': 'star',
        'adilt': 'adult',
        'mazé': 'major/adult',
        'miné': 'minor',
        'adolésan': 'adolescent (male)',
        'adolésant': 'adolescent (female)',
        'zenn': 'young (male/female)',
        'zenn nonm': 'young man',
        'zenn fanm': 'young woman',
        'zennés': 'youth',
        'bébé': 'baby',
        'novo-né': 'newborn (male/female)',
        'vyé': 'old (male)',
        'vyéy': 'old (female)',
        'moun azé': 'elderly person',
        'vétéran': 'veteran',
        'étrazé': 'foreigner (male)',
        'étrazér': 'foreigner (female)',
        'imigré': 'immigrant (male/female)',
        'tourist': 'tourist',
        'abitan': 'inhabitant (male/female)',
        'sitoyé': 'citizen (male)',
        'sitoyénn': 'citizen (female)',
        'nasyonal': 'national',
        'rézidan': 'resident (male/female)',
        'lokal': 'local (male/female)',
        
        // Professions
        'profésyonèl': 'professional (male/female)',
        'ékspar': 'expert (male/female)',
        'spésyalist': 'specialist',
        'téknisyen': 'technician (male/female)',
        'artizan': 'artisan (male/female)',
        'ouvré': 'worker (male)',
        'ouvrir': 'worker (female)',
        'anplwayé': 'employee (male/female)',
        'travayé': 'worker (male)',
        'travayéz': 'worker (female)',
        'chéf': 'boss/chief',
        'dirèktèr': 'director (male)',
        'dirèktris': 'director (female)',
        'manazé': 'manager',
        'zéran': 'manager',
        'patron': 'boss (male)',
        'patronn': 'boss (female)',
        'sipéryé': 'superior (male)',
        'sipéryér': 'superior (female)',
        'sibordoné': 'subordinate (male/female)',
        'kolaboratér': 'collaborator (male)',
        'kolaboratris': 'collaborator (female)',
        'konkiran': 'competitor (male/female)',
        'rival': 'rival (male/female)',
        'advèrsèr': 'opponent (male)',
        'advèrsèr': 'opponent (female)',
        'alyé': 'ally (male/female)',
        'anmi': 'enemy (male/female)',
        'inkonu': 'stranger (male/female)',
        'vizité': 'visitor (male)',
        'vizitéz': 'visitor (female)',
        'anvit': 'guest (male)',
        'anvité': 'guest (female)',
        'ot': 'host (male)',
        'otés': 'hostess',
        'klyan': 'client (male)',
        'klyant': 'client (female)',
        'achté': 'buyer (male)',
        'achtéz': 'buyer (female)',
        'konzomatér': 'consumer (male)',
        'konzomatris': 'consumer (female)',
        'vandé': 'seller (male)',
        'vandéz': 'seller (female)',
        'komérsan': 'merchant (male/female)',
        'fournisé': 'supplier (male)',
        'fourniséz': 'supplier (female)',
        'préstatèr': 'service provider (male/female)',
        'kréatér': 'creator (male)',
        'kréatris': 'creator (female)',
        'artist': 'artist',
        'péntr': 'painter (male)',
        'skilptér': 'sculptor (male)',
        'skilptris': 'sculptor (female)',
        'mizisyen': 'musician (male)',
        'mizisyenn': 'musician (female)',
        'chanté': 'singer (male)',
        'chantéz': 'singer (female)',
        'dansé': 'dancer (male)',
        'danséz': 'dancer (female)',
        'akté': 'actor',
        'aktris': 'actress',
        'ékrivén': 'writer (male/female)',
        'poét': 'poet (male)',
        'poétés': 'poet (female)',
        'zournalist': 'journalist',
        'rporté': 'reporter (male)',
        'prézantatér': 'presenter (male)',
        'prézantatris': 'presenter (female)',
        'animatér': 'animator (male)',
        'animatris': 'animator (female)',
        'modératér': 'moderator (male)',
        'modératris': 'moderator (female)',
        'profésé': 'professor',
        'anségnan': 'teacher (male)',
        'anségnant': 'teacher (female)',
        'édikatér': 'educator (male)',
        'édikatris': 'educator (female)',
        'étydyan': 'student (male)',
        'étydiant': 'student (female)',
        'élév': 'pupil',
        'apran': 'apprentice (male)',
        'aprant': 'apprentice (female)',
        'sersé': 'researcher (male)',
        'serséz': 'researcher (female)',
        'syantifik': 'scientist',
        'anvantér': 'inventor (male)',
        'anvantris': 'inventor (female)',
        'médésin': 'doctor',
        'doktèr': 'doctor',
        'sirizyen': 'surgeon (male)',
        'sirizyenn': 'surgeon (female)',
        'infirmyé': 'nurse (male)',
        'infirmyér': 'nurse (female)',
        'farmasyen': 'pharmacist (male)',
        'farmasyenn': 'pharmacist (female)',
        'dantis': 'dentist',
        'vétérinèr': 'veterinarian',
        'psikolog': 'psychologist',
        'psikiatr': 'psychiatrist',
        'avoka': 'lawyer (male/female)',
        'zuj': 'judge',
        'prokiré': 'prosecutor (male)',
        'prokirér': 'prosecutor (female)',
        'polisyé': 'police officer',
        'zandarm': 'gendarmerie',
        'militèr': 'military',
        'solda': 'soldier',
        'ofisyé': 'officer',
        'kapitén': 'captain',
        'zénéral': 'general',
        'politisyen': 'politician (male)',
        'politisyenn': 'politician (female)',
        'dépyé': 'deputy (male/female)',
        'sénatér': 'senator (male)',
        'sénatris': 'senator (female)',
        'ministr': 'minister',
        'prézidan': 'president (male)',
        'prézidant': 'president (female)',
        'mèr': 'mayor',
        'konséyé': 'councilor (male)',
        'konséyér': 'councilor (female)',
        'administratér': 'administrator (male)',
        'administratris': 'administrator (female)',
        'fonksyonèr': 'civil servant',
        'anplwayé piblik': 'public employee',
        'réprézantan': 'representative (male)',
        'réprézantant': 'representative (female)',
        'délégué': 'delegate (male/female)',
        'anbasadé': 'ambassador (male)',
        'anbasadris': 'ambassador (female)',
        'konsul': 'consul (male/female)',
        'diplomat': 'diplomat',
        'azan': 'agent',
        'éspyon': 'spy (male)',
        'éspyonn': 'spy (female)',
        'déktiv': 'detective',
        'ankètér': 'investigator (male)',
        'ankètris': 'investigator (female)',
        'témwan': 'witness (male/female)',
        'suspèk': 'suspect (male/female)',
        'kriminel': 'criminal (male/female)',
        'volé': 'thief (male)',
        'voléz': 'thief (female)',
        'asasan': 'assassin (male)',
        'asasinn': 'assassin (female)',
        'bandi': 'bandit',
        'gangstér': 'gangster',
        'prizonyé': 'prisoner (male)',
        'prizonyér': 'prisoner (female)',
        'délinkan': 'delinquent (male/female)',
        'viktim': 'victim',
        'plénian': 'plaintiff (male)',
        'plényant': 'plaintiff (female)',
        'souvété': 'rescuer (male)',
        'souvétéz': 'rescuer (female)',
        'éro': 'hero (male)',
        'éroyn': 'heroine',
        
        // Adjectives
        'kourazé': 'brave (male)',
        'kourazéz': 'brave (female)',
        'brav': 'brave (male/female)',
        'timid': 'shy (male/female)',
        'odasié': 'daring (male)',
        'odasiéz': 'daring (female)',
        'zanmèl': 'nice/kind (male/female)',
        'méchan': 'mean (male/female)',
        'intélijan': 'intelligent (male/female)',
        'bèt': 'stupid (male/female)',
        'séryé': 'serious (male/female)',
        'dròl': 'funny (male/female)',
        'éré': 'happy (male)',
        'éréz': 'happy (female)',
        'maléré': 'unhappy (male)',
        'maléréz': 'unhappy (female)',
        'kontan': 'happy/content (male/female)',
        'trist': 'sad (male/female)',
        'kalm': 'calm (male/female)',
        'azité': 'agitated (male/female)',
        'bo': 'beautiful (male)',
        'bèl': 'beautiful (female)',
        'joli': 'pretty (male/female)',
        'gran': 'big/large (male/female)',
        'ti': 'small (male/female)',
        'gro': 'fat (male/female)',
        'mains': 'thin (male/female)',
        'ho': 'tall/high (male/female)',
        'ba': 'short/low (male/female)',
        'lon': 'long (male/female)',
        'kour': 'short (male/female)',
        'larz': 'wide (male/female)',
        'étrèt': 'narrow (male/female)',
        'rich': 'rich (male/female)',
        'povr': 'poor (male/female)',
        'for': 'strong (male/female)',
        'fèb': 'weak (male/female)',
        'sén': 'healthy (male/female)',
        'malad': 'sick (male/female)',
        'propr': 'clean (male/female)',
        'sal': 'dirty (male/female)',
        'cho': 'hot (male/female)',
        'frèt': 'cold (male/female)',
        'rapit': 'fast (male/female)',
        'lan': 'slow (male/female)',
        'fasil': 'easy (male/female)',
        'difisil': 'difficult (male/female)',
        'nouvò': 'new (male)',
        'nouvèl': 'new (female)',
        'ansyen': 'old (male)',
        'ansyenn': 'old (female)',
        'premyé': 'first (male)',
        'premyér': 'first (female)',
        'dényé': 'last (male)',
        'dényér': 'last (female)',
        'sèl': 'alone (male/female)',
        'ansanbl': 'together',
        'libr': 'free (male/female)',
        'mor': 'dead (male)',
        'mòr': 'dead (female)',
        'vivan': 'alive (male/female)',
        
        // Places
        'vil': 'city',
        'sité': 'city',
        'métropol': 'metropolis',
        'kapital': 'capital',
        'vilaz': 'village',
        'bor': 'town',
        'amò': 'hamlet',
        'kartié': 'neighborhood',
        'rézion': 'region',
        'provinss': 'province',
        'départman': 'department',
        'kanton': 'canton',
        'péyi': 'country',
        'nasyon': 'nation',
        'éta': 'state',
        'teritwar': 'territory',
        'kontinan': 'continent',
        'mond': 'world',
        'planèt': 'planet',
        'linivèr': 'universe',
        'latèr': 'earth',
        'siel': 'sky',
        'anfèr': 'hell',
        'paradi': 'paradise',
        'soléy': 'sun',
        'lalin': 'moon',
        'zétwal': 'star',
        'galaksi': 'galaxy',
        'nébilis': 'nebula',
        'komèt': 'comet',
        'astéroid': 'asteroid',
        'kosmos': 'cosmos',
        'espas': 'space',
        'vid': 'void',
        'anfini': 'infinity',
        'tan': 'time',
        'éternité': 'eternity',
        'instan': 'instant',
        'momàn': 'moment',
        'pasé': 'past',
        'prézan': 'present',
        'fitir': 'future',
        'avenir': 'future',
        'istwar': 'history',
        'mémoir': 'memory',
        'souvnir': 'souvenir',
        'tradisyon': 'tradition',
        'koutim': 'custom',
        'abitid': 'habit',
        'kiltir': 'culture',
        'sivilizasyon': 'civilization',
        'sosyété': 'society',
        'komynoté': 'community',
        'pèp': 'people',
        'lang': 'language',
        'dyalèkt': 'dialect',
        'aksan': 'accent',
        'prononsasyon': 'pronunciation',
        'mo': 'word',
        'vokabilèr': 'vocabulary',
        'diksyonnèr': 'dictionary',
        'gramèr': 'grammar',
        'alfabé': 'alphabet',
        'lètr': 'letter',
        'fraz': 'sentence',
        'téks': 'text',
        'livr': 'book',
        'paz': 'page',
        'chapitr': 'chapter',
        'paragraf': 'paragraph',
        'titr': 'title',
        'oté': 'author',
        'roman': 'novel',
        'nuvèl': 'short story',
        'kont': 'tale',
        'poézi': 'poetry',
        'téatr': 'theater',
        'pyès': 'play',
        'akt': 'act',
        'sén': 'scene',
        'sinéma': 'cinema',
        'film': 'film',
        'réalizatér': 'director (male)',
        'réalizatris': 'director (female)',
        'prodikté': 'producer (male)',
        'prodiktris': 'producer (female)',
        'mizik': 'music',
        'chanson': 'song',
        'mélodi': 'melody',
        'ritm': 'rhythm',
        'instruman': 'instrument',
        'orkèstr': 'orchestra',
        'koral': 'choir',
        'opéra': 'opera',
        'balé': 'ballet',
        'dans': 'dance',
        'korégrafi': 'choreography',
        'péntir': 'painting',
        'tablo': 'painting/canvas',
        'koulèr': 'color',
        'skilptir': 'sculpture',
        'désén': 'drawing',
        'désinatér': 'drawer (male)',
        'désinatris': 'drawer (female)',
        'fotografi': 'photography',
        'fotograf': 'photographer (male/female)',
        'foto': 'photo',
        'arkitektir': 'architecture',
        'arkitekt': 'architect',
        'batiman': 'building',
        'dézén': 'design',
        'dézénér': 'designer (male)',
        'kréasyon': 'creation',
        'mod': 'fashion',
        'koutiryé': 'designer (male)',
        'kouturiér': 'designer (female)',
        'vètman': 'clothing',
        'bijou': 'jewelry',
        'zwayé': 'jeweler (male)',
        'zwayér': 'jeweler (female)',
        'lor': 'gold',
        'arzan': 'silver/money',
        'dyaman': 'diamond',
        'pyèr présyé': 'precious stones',
        'spor': 'sport',
        'atlétism': 'athletics',
        'futbòl': 'football',
        'basketbòl': 'basketball',
        'ténis': 'tennis',
        'gòlf': 'golf',
        'natasion': 'swimming',
        'siklism': 'cycling',
        'ski': 'skiing',
        'alpinism': 'mountaineering',
        'éskalad': 'climbing',
        'plonzé': 'diving',
        'surf': 'surfing',
        'voal': 'sailing',
        'aviron': 'rowing',
        'ékitasyon': 'horse riding',
        'boks': 'boxing',
        'zudo': 'judo',
        'karaté': 'karate',
        'ar martiyo': 'martial arts',
        'konpétisyon': 'competition',
        'match': 'match',
        'tournwa': 'tournament',
        'chanpionna': 'championship',
        'zoué': 'player (male)',
        'zouzé': 'player (female)',
        'ékip': 'team',
        'antrénné': 'coach (male)',
        'antrénnéz': 'coach (female)',
        'arbitr': 'referee',
        'stad': 'stadium',
        'térén': 'field',
        'pisin': 'swimming pool',
        'zimnaz': 'gymnasium',
        'santé': 'health',
        'médésin': 'medicine',
        'maladi': 'illness',
        'simptom': 'symptom',
        'doulér': 'pain',
        'fyèvr': 'fever',
        'grip': 'flu',
        'rum': 'cold',
        'kansér': 'cancer',
        'dyabèt': 'diabetes',
        'kèr': 'heart',
        'présyon': 'pressure',
        'trétmman': 'treatment',
        'médikaman': 'medication',
        'opérasyon': 'operation',
        'gyérizon': 'healing',
        'rétablisman': 'recovery',
        'konvalésans': 'convalescence',
        'alimantasyon': 'food/nutrition',
        'rézim': 'diet',
        'dyététik': 'dietetics',
        'vitamin': 'vitamins',
        'minéro': 'minerals',
        'protéin': 'proteins',
        'glisid': 'carbohydrates',
        'nitrisyon': 'nutrition',
        'ékilibr': 'balance',
        'pwa': 'weight',
        'obézité': 'obesity',
        'égsèrsis': 'exercise',
        'antrénnman': 'training',
        'kondisyon fizik': 'physical condition',
        'byenètr': 'well-being',
        'relaksasyon': 'relaxation',
        'méditasyon': 'meditation',
        'strès': 'stress',
        'fatig': 'fatigue',
        'épizman': 'exhaustion',
        'burn-ot': 'burnout',
        'soméy': 'sleep',
        'inzomni': 'insomnia',
        'rèv': 'dream',
        'kochmar': 'nightmare',
        'psikoloji': 'psychology',
        'térapie': 'therapy',
        'psikanaliz': 'psychoanalysis',
        'déprésyon': 'depression',
        'anksyété': 'anxiety',
        'fobi': 'phobia',
        'tròtism': 'trauma',
        'adiksion': 'addiction',
        'dépadans': 'dependence',
        'sévraz': 'withdrawal',
        'prévansyon': 'prevention',
        'vaksinasyon': 'vaccination',
        'yizyén': 'hygiene',
        'sékirité': 'security',
        'proteksyon': 'protection',
        'danzé': 'danger',
        'risk': 'risk',
        'aksidan': 'accident',
        'irzans': 'emergency',
        'sékou': 'help',
        'premyé sékou': 'first aid',
        'asirans': 'insurance',
        'kouvèrtir': 'coverage',
        'ranbourseman': 'reimbursement',
        'téknoloji': 'technology',
        'informatik': 'computer science',
        'ordinatér': 'computer',
        'intèrnèt': 'internet',
        'web': 'web',
        'sit web': 'website',
        'imèl': 'email',
        'smartfon': 'smartphone',
        'tablèt': 'tablet',
        'aplikasyon': 'application',
        'lojisyèl': 'software',
        'progrann': 'program',
        'sistém': 'system',
        'rézo': 'network',
        'wifi': 'wifi',
        'blutut': 'bluetooth',
        'imprimant': 'printer',
        'skané': 'scanner',
        'klavyé': 'keyboard',
        'souri': 'mouse',
        'ékrann': 'screen',
        'monitér': 'monitor',
        'prosesér': 'processor',
        'mémoir': 'memory',
        'stokaz': 'storage',
        'disk dur': 'hard drive',
        'klod': 'cloud',
        'souvégard': 'backup',
        'sibérsékirité': 'cybersecurity',
        'virus': 'virus',
        'pirataz': 'hacking',
        'intélijans artisyisyèl': 'artificial intelligence',
        'robot': 'robot',
        'otomatisazon': 'automation',
        'réalité virtièl': 'virtual reality',
        'réalité ogmenté': 'augmented reality',
        'inovasyon': 'innovation',
        'sers': 'research',
        'dévelopman': 'development',
        'syans': 'science',
        'syantifik': 'scientific',
        'laboratwar': 'laboratory',
        'éksérimantasyon': 'experimentation',
        'dékouvèrt': 'discovery',
        'anvansyon': 'invention',
        'fizik': 'physics',
        'chimi': 'chemistry',
        'bioloji': 'biology',
        'matématik': 'mathematics',
        'astronomi': 'astronomy',
        'zéoloji': 'geology',
        'météoroloji': 'meteorology',
        'ékoloji': 'ecology',
        'anvironman': 'environment',
        'klima': 'climate',
        'polisyon': 'pollution',
        'réchaufman klimatik': 'global warming',
        'énerzi': 'energy',
        'renouvlabl': 'renewable',
        'solèr': 'solar',
        'éolyen': 'wind',
        'dévelopman durabl': 'sustainable development',
        'siklaz': 'recycling',
        'zèsyon dé déché': 'waste management',
        'byodivérsité': 'biodiversity',
        'espés an danzé': 'endangered species',
        'konèrvasyon': 'conservation',
        'prézèrvasyon': 'preservation',
        'ékonomi': 'economy',
        'finans': 'finance',
        'monay': 'currency',
        'budzé': 'budget',
        'épargn': 'savings',
        'anvestisman': 'investment',
        'bank': 'bank',
        'krédi': 'credit',
        'anpran': 'loan',
        'pré': 'loan',
        'bours': 'stock market',
        'aksyon': 'share',
        'marché finansyé': 'financial market',
        'antrepriz': 'company',
        'komèrs': 'commerce',
        'indistri': 'industry',
        'prodiksyon': 'production',
        'konsozmasyon': 'consumption',
        'anportasyon': 'importation',
        'ékspòrtasyon': 'exportation',
        'komèrs entèrnasyonal': 'international trade',
        'marketing': 'marketing',
        'piblisité': 'advertising',
        'promosyon': 'promotion',
        'vant': 'sale',
        'acha': 'purchase',
        'négosiasyon': 'negotiation',
        'kontra': 'contract',
        'travay': 'work',
        'anploé': 'employment',
        'karyér': 'career',
        'profésyon': 'profession',
        'salèr': 'salary',
        'revénu': 'income',
        'anpo': 'tax',
        'taks': 'tax',
        'rètrait': 'retirement',
        'sékirité sosyal': 'social security',
        'édikasyon': 'education',
        'formasyon': 'training',
        'aprantisaz': 'apprenticeship',
        'konpétans': 'skill',
        'kalifikasyon': 'qualification',
        'sèrtifikat': 'certificate',
        'diplom': 'diploma',
        'linivèrsité': 'university',
        'étyd': 'studies',
        'politik': 'politics',
        'gouvanman': 'government',
        'démokrasi': 'democracy',
        'éléksyon': 'election',
        'vot': 'vote',
        'kandida': 'candidate (male/female)',
        'parti politik': 'political party',
        'kanpan élèktoral': 'electoral campaign',
        'parlman': 'parliament',
        'séna': 'senate',
        'asanblé': 'assembly',
        'lwa': 'law',
        'lézislasion': 'legislation',
        'régliman': 'regulation',
        'zistis': 'justice',
        'tribinal': 'court',
        'kour': 'court',
        'polis': 'police',
        'armé': 'army',
        'défans': 'defense',
        'relasyon entèrnasyonal': 'international relations',
        'diplomasi': 'diplomacy',
        'tréyé': 'treaty',
        'akor': 'agreement',
        'alyans': 'alliance',
        'konfli': 'conflict',
        'gèr': 'war',
        'pé': 'peace',
        'térorism': 'terrorism',
        'menas': 'threat',
        'dwa dé lom': 'human rights',
        'libèrté': 'freedom',
        'égalité': 'equality',
        'fratérnité': 'fraternity',
        'solidarité': 'solidarity',
        'modèrnité': 'modernity',
        'progrè': 'progress',
        'globalizasyon': 'globalization',
        'mondyalizasyon': 'globalization',
        'komynikasyon': 'communication',
        'informasyon': 'information',
        'médya': 'media',
        'zournalism': 'journalism',
        'télevizyon': 'television',
        'radio': 'radio',
        'prés': 'press',
        'rézo sosyo': 'social networks',
        'opinyon piblik': 'public opinion',
        'rélijyon': 'religion',
        'fwa': 'faith',
        'kroyans': 'belief',
        'dyé': 'god',
        'légliz': 'church',
        'moské': 'mosque',
        'tanpl': 'temple',
        'sinagòg': 'synagogue',
        'priyèr': 'prayer',
        'ritiyèl': 'ritual',
        'sérémoni': 'ceremony',
        'spiritwalité': 'spirituality',
        'filozofi': 'philosophy',
        'étik': 'ethics',
        'moral': 'morality',
        'valé': 'values',
        'ar': 'art',
        'estétik': 'aesthetics',
        'bauté': 'beauty',
        'armoni': 'harmony',
        'kréativité': 'creativity',
        'éksprésyon': 'expression',
        'inspirasyon': 'inspiration',
        'talan': 'talent',
        'lwazir': 'leisure',
        'divèrtisman': 'entertainment',
        'vakans': 'vacations',
        'tourism': 'tourism',
        'vwiyaz': 'travel',
        'avantir': 'adventure',
        'éksplorazon': 'exploration',
        'natiir': 'nature',
        'agrikiltir': 'agriculture',
        'péché': 'fishing',
        'élévaz': 'livestock farming',
        'rékolt': 'harvest',
        'kiltivazon': 'cultivation',
        'kizin': 'kitchen/cuisine',
        'gastronomi': 'gastronomy',
        'van': 'wine',
        'spiritié': 'spirits',
        'koktéy': 'cocktail',
        'fèt': 'party',
        'sélébrasyon': 'celebration',
        'festival': 'festival',
        'konsèr': 'concert',
        'spètakl': 'show',
        'éksposisyon': 'exhibition',
        'pèrformans': 'performance',
        'form fizik': 'physical form',
        'transpor': 'transport',
        'déplasman': 'movement',
        'sirkilasyon': 'circulation',
        'irbanism': 'urbanism',
        'konstriksyon': 'construction',
        'abita': 'habitat',
        'lozman': 'housing',
        'imobilié': 'real estate',
        'résours': 'resources',
        'matyèr prémyé': 'raw materials',
        'météo': 'weather',
        'durabilité': 'durability',
        'ékosistém': 'ecosystem',
        'kroysans': 'growth',
        'patrimwan': 'heritage',
        'idantité': 'identity',
        'apartnans': 'belonging',
        'rasin': 'roots',
        'divèrsité': 'diversity',
        'tolérans': 'tolerance',
        'respè': 'respect',
        'antréid': 'mutual aid',
        'koopérasyon': 'cooperation',
        'ékilibr': 'balance',
        'sitwayanneté': 'citizenship',
        'partisipasyon': 'participation',
        'réponsabilité': 'responsibility',
        'angazman': 'commitment',
        'implikasyon': 'involvement',
        'dévelopman pèrsonèl': 'personal development',
        'épanisman': 'fulfillment',
        'konésans dé lwa-mèm': 'self-knowledge',
        'réflèksyon': 'reflection',
        'sazès': 'wisdom',
        'éksperyans': 'experience',
        'matirité': 'maturity',
        'évolisyon': 'evolution',
        'transformazon': 'transformation',
        'zanzman': 'change',
        'adaptazon': 'adaptation',
        'rézilyans': 'resilience',
        'kouraz': 'courage',
        'dépasman dé lwa-mèm': 'self-transcendence',
        'dépasman': 'surpassing',
        'akomplisman': 'accomplishment',
        'réalizasyon': 'realization',
        'siksé': 'success',
        'bonèr': 'happiness',
        'plénitid': 'fullness',
        'lamour': 'love',
        'amitié': 'friendship',
        'relasyon imén': 'human relations',
        'kupl': 'couple',
        'parténaria': 'partnership',
        'dyalog': 'dialogue',
        'ékout': 'listening',
        'konprénsyon': 'understanding',
        'anpati': 'empathy',
        'konpasyon': 'compassion',
        'partaz': 'sharing',
        'zénérosité': 'generosity',
        'altrism': 'altruism',
        'konfyans': 'trust',
        'konsidérasyon': 'consideration',
        'estim': 'esteem',
        'rekonésans': 'recognition',
        'valorizasyon': 'valorization',
        'otantisité': 'authenticity',
        'sinsérité': 'sincerity',
        'onèté': 'honesty',
        'intégrité': 'integrity',
        'droitir': 'rectitude',
        'transparans': 'transparency',
        'vérité': 'truth',
        'klarté': 'clarity',
        'lisidité': 'lucidity',
        'vizilans': 'vigilance',
        'atansyon': 'attention',
        'présans': 'presence',
        'mindfulness': 'mindfulness',
        'plén konfyans': 'full awareness',
        'kontanplasyon': 'contemplation',
        
        // Verbs
        'manz': 'to eat',
        'bwar': 'to drink',
        'dormi': 'to sleep',
        'travay': 'to work',
        'étidyé': 'to study',
        'zoué': 'to play',
        'chanté': 'to sing',
        'dansé': 'to dance',
        'kouri': 'to run',
        'mars': 'to walk',
        'soté': 'to jump',
        'nagé': 'to swim',
        'volé': 'to fly/to steal',
        'gripé': 'to climb',
        'désan': 'to descend',
        'monté': 'to ascend',
        'arivé': 'to arrive',
        'parti': 'to leave',
        'rvini': 'to come back',
        'rourné': 'to return',
        'soti': 'to go out',
        'antré': 'to enter',
        'rété': 'to stay',
        'dmoré': 'to remain',
        'viv': 'to live',
        'abité': 'to inhabit',
        'nèss': 'to be born',
        'mouri': 'to die',
        'dévini': 'to become',
        'granndir': 'to grow up',
        'vyéyir': 'to grow old',
        'zanzé': 'to change',
        'apran': 'to learn',
        'anségné': 'to teach',
        'ékspliké': 'to explain',
        'konprann': 'to understand',
        'koné': 'to know',
        'dékouvr': 'to discover',
        'trouvé': 'to find',
        'sersé': 'to search',
        'pèrd': 'to lose',
        'oublié': 'to forget',
        'souvnir': 'to remember',
        'pansé': 'to think',
        'réfléchi': 'to reflect',
        'imaziné': 'to imagine',
        'kwar': 'to believe',
        'douté': 'to doubt',
        'éspéré': 'to hope',
        'atann': 'to wait',
        'pasyanté': 'to be patient',
        'vlé': 'to want',
        'déziré': 'to desire',
        'souété': 'to wish',
        'préféré': 'to prefer',
        'aimé': 'to love/like',
        'adoré': 'to adore',
        'détésté': 'to hate',
        'é': 'to hate',
        'kapav': 'to be able to',
        'dwar': 'to have to',
        'falwar': 'to be necessary',
        'sanblé': 'to seem',
        'aparètr': 'to appear',
        'lé': 'to be',
        'gagn': 'to have',
        'fé': 'to do/make',
        'dir': 'to say',
        'war': 'to see',
        'pran': 'to take',
        'donn': 'to give',
        'résouwar': 'to receive',
        'ofrir': 'to offer',
        'achté': 'to buy',
        'vand': 'to sell',
        'payé': 'to pay',
        'kouté': 'to cost',
        'valwar': 'to be worth',
        'pézé': 'to weigh',
        'mezuré': 'to measure',
        'konté': 'to count',
        'kalkilé': 'to calculate',
        'adisyoné': 'to add',
        'soustré': 'to subtract',
        'multiplié': 'to multiply',
        'divizé': 'to divide',
        'éstimé': 'to estimate',
        'zjugé': 'to judge',
        'désidé': 'to decide',
        'chwazi': 'to choose',
        'détérminé': 'to determine',
        'fixé': 'to fix',
        'nomé': 'to name',
        'dézigné': 'to designate',
        'apélé': 'to call',
        'kalifyé': 'to qualify',
        'définir': 'to define',
        'karaktérizé': 'to characterize',
        'dékrir': 'to describe',
        'reprézanté': 'to represent',
        'simbolizé': 'to symbolize',
        'signifyé': 'to signify',
        'andiké': 'to indicate',
        'montré': 'to show',
        'démontré': 'to demonstrate',
        'révéler': 'to reveal',
        'dévwalyé': 'to unveil',
        'ékspozé': 'to expose',
        'prézanté': 'to present',
        'antrouir': 'to introduce',
        'anséré': 'to insert',
        'ankorporé': 'to incorporate',
        'anlégré': 'to integrate',
        'ajouté': 'to add',
        'konplété': 'to complete',
        'séplémanté': 'to supplement',
        'anrichir': 'to enrich',
        'anélyoré': 'to improve',
        'parfèr': 'to perfect',
        'achévér': 'to complete',
        'parachévér': 'to complete thoroughly',
        'finalizé': 'to finalize',
        'términé': 'to finish',
        'konkly': 'to conclude',
        'anteromp': 'to interrupt',
        'sispan': 'to suspend',
        'sésé': 'to cease',
        'arété': 'to stop',
        'stopé': 'to stop',
        'abandoné': 'to abandon',
        'rononsé': 'to renounce',
        'sédé': 'to cede',
        'laché': 'to let go',
        'relaché': 'to release',
        'délivré': 'to deliver',
        'libéré': 'to free',
        'afranchir': 'to enfranchise',
        'émasipé': 'to emancipate',
        'sové': 'to save',
        'sékourir': 'to rescue',
        'édé': 'to help',
        'asisté': 'to assist',
        'souténir': 'to support',
        'manténir': 'to maintain',
        'préservé': 'to preserve',
        'konservé': 'to conserve',
        'gardé': 'to keep',
        'protégé': 'to protect',
        'défand': 'to defend',
        'abrité': 'to shelter',
        'kouvri': 'to cover',
        'anvelopé': 'to wrap',
        'anbalé': 'to pack',
        'anbwaté': 'to fit together',
        'anfermé': 'to lock up',
        'anklor': 'to enclose',
        'anouré': 'to surround',
        'ansèrklé': 'to encircle',
        'séparé': 'to separate',
        'distangé': 'to distinguish',
        'diféransyé': 'to differentiate',
        'komparé': 'to compare',
        'analizé': 'to analyze',
        'égzaminé': 'to examine',
        'anspèkté': 'to inspect',
        'obsèrvé': 'to observe',
        'sirvéyé': 'to monitor',
        'kontrolé': 'to control',
        'vérifyé': 'to verify',
        'tésté': 'to test',
        'ésayé': 'to try',
        'éksérimanté': 'to experiment',
        'prouvé': 'to prove',
        'établir': 'to establish',
        'konfirmé': 'to confirm',
        'sèrtifyé': 'to certify',
        'garantir': 'to guarantee',
        'asiré': 'to assure',
        'épyé': 'to spy on',
        'éspyoné': 'to spy',
        'pèrsoar': 'to perceive',
        'disèrné': 'to discern',
        'anterprété': 'to interpret',
        'tradwir': 'to translate',
        'rakonté': 'to tell',
        'narré': 'to narrate',
        's-éksprimé': 'to express oneself',
        'artikilé': 'to articulate',
        'prononsé': 'to pronounce',
        'éonsé': 'to state',
        'déklaré': 'to declare',
        'anonsé': 'to announce',
        'anformé': 'to inform',
        'prévénir': 'to prevent',
        'avertir': 'to warn',
        'alarté': 'to alert',
        'signalé': 'to signal',
        'dénonsé': 'to denounce',
        'akuzé': 'to accuse',
        'ankilpé': 'to indict',
        'kondanné': 'to condemn',
        'punir': 'to punish',
        'pardoné': 'to forgive',
        'ékuzé': 'to excuse',
        'absoudr': 'to absolve',
        'grasié': 'to grant amnesty',
        'anmistié': 'to amnesty',
        's-rapélé': 'to remember',
        'mémorizé': 'to memorize',
        's-antrené': 'to train oneself',
        'pratiké': 'to practice',
        'égsèrsé': 'to exercise',
        's-égsèrsé': 'to exercise oneself',
        'progréssé': 'to progress',
        'avansé': 'to advance',
        's-dévelopé': 'to develop oneself',
        'évolyé': 'to evolve',
        'transformé': 'to transform',
        'modifyé': 'to modify',
        'altéré': 'to alter',
        'adapté': 'to adapt',
        'azusté': 'to adjust',
        'akrwatr': 'to increase',
        'ogmanté': 'to augment',
        'diminyé': 'to diminish',
        'réduir': 'to reduce',
        'bésé': 'to lower',
        's-miltiplié': 'to multiply oneself',
        's-reprodwir': 'to reproduce oneself',
        'émérzé': 'to emerge',
        'sirvénir': 'to occur',
        's-prodwir': 'to occur',
        'disparètr': 'to disappear',
        's-évanwir': 'to faint',
        'désédé': 'to pass away',
        'trépasé': 'to pass away',
        'résisité': 'to resurrect',
        'rénèss': 'to be reborn',
        'réaparètr': 'to reappear',
        'réémérzé': 'to re-emerge',
        'égzisté': 'to exist',
        'sizisté': 'to subsist',
        'sirviv': 'to survive',
        'diré': 'to last',
        'persisté': 'to persist',
        'kontinyé': 'to continue',
        's-manténir': 'to maintain oneself',
        'aparténir': 'to belong',
        'dépan': 'to depend',
        'rpozé sur': 'to rest on',
        'konserné': 'to concern',
        'anpliké': 'to apply',
        'afekté': 'to affect',
        'touché': 'to affect',
        'anflansé': 'to influence',
        'provoqué': 'to provoke',
        'kozé': 'to cause',
        'antrénné': 'to train/to cause',
        'déklanché': 'to trigger',
        'prodwir': 'to produce',
        'zénéré': 'to generate',
        'anzandré': 'to beget',
        'prokréé': 'to procreate',
        'fabriké': 'to manufacture',
        'manifaktiré': 'to manufacture',
        'konféksyoné': 'to make',
        'élabaré': 'to elaborate',
        'kompozé': 'to compose',
        'konstitwé': 'to constitute',
        'formé': 'to form',
        'batir': 'to build',
        'érizé': 'to erect',
        'édifyé': 'to edify',
        'anstalé': 'to install',
        'dépozé': 'to arrange',
        'plasé': 'to place',
        'pozisyoné': 'to position',
        'situé': 'to situate',
        'lokalizé': 'to locate',
        'organizé': 'to organize',
        'amanazé': 'to arrange',
        'aranjé': 'to arrange',
        'préparé': 'to prepare',
        'ranzé': 'to tidy up',
        'klasé': 'to classify',
        'ordonné': 'to order',
        'triyé': 'to sort',
        'sélèksyoné': 'to select',
        'opté': 'to opt',
        'ézigé': 'to demand',
        'mandé': 'to ask',
        'priyé': 'to pray',
        'souplié': 'to beg',
        'anploré': 'to implore',
        'nésésité': 'to necessitate',
        'ansisté': 'to insist',
        'poursivir': 'to pursue',
        'atén': 'to reach',
        'obténir': 'to obtain',
        'gagné': 'to win/to earn',
        'ranporté': 'to bring back',
        'triomfé': 'to triumph',
        'réyisi': 'to succeed',
        'échwé': 'to fail',
        'manké': 'to miss',
        'raté': 'to miss',
        'loupé': 'to miss',
        'ézité': 'to hesitate',
        'krén': 'to fear',
        'rédouté': 'to dread',
        'apréandé': 'to apprehend',
        'ozé': 'to dare',
        'avoué': 'to admit',
        'konfésé': 'to confess',
        'rekonèt': 'to recognize',
        'admetr': 'to admit',
        'nié': 'to deny',
        'déméntir': 'to contradict',
        'kontradir': 'to contradict',
        'réfuté': 'to refute',
        'argimanté': 'to argue',
        'diskuté': 'to discuss',
        'débatt': 'to debate',
        'négosyé': 'to negotiate',
        'dialogé': 'to dialogue',
        'komyniké': 'to communicate',
        'transmèt': 'to transmit',
        'anvoyé': 'to send',
        'éspédyé': 'to expedite',
        'posté': 'to post',
        'livré': 'to deliver',
        'distribyé': 'to distribute',
        'rasanblé': 'to gather',
        'réynir': 'to reunite',
        'goupé': 'to group',
        'asosyé': 'to associate',
        'lyé': 'to link',
        'konèkté': 'to connect',
        'branché': 'to plug in',
        'rlyé': 'to connect',
        'zwan': 'to join',
        'ynir': 'to unite',
        'gardé': 'to look at/to keep',
        'ékouté': 'to listen',
        'tand': 'to hear',
        'sésir': 'to grasp',
        'kozé': 'to speak',
        'tomber': 'to fall',
        'pousé': 'to push',
        'krwatr': 'to grow'
    }
};