const FRENCH_ENGLISH_DICTIONARY = {
    'fr-en': {
        // Greetings and Basic Expressions
        'bonjour': 'hello',
        'salut': 'hi',
        'bonsoir': 'good evening',
        'bonne nuit': 'good night',
        'au revoir': 'goodbye',
        'à bientôt': 'see you soon',
        'bienvenue': 'welcome',
        'merci': 'thank you',
        's\'il vous plaît': 'please',
        'pardon': 'sorry',
        'excusez-moi': 'excuse me',
        'désolé(e)': 'apologetic/sorry',
        'oui': 'yes',
        'non': 'no',
        'peut-être': 'maybe',
        'bien sûr': 'of course',
        'absolument': 'absolutely',
        'je ne sais pas': 'I don\'t know',
        'je comprends': 'I understand',
        'je ne comprends pas': 'I don\'t understand',
        'comment allez-vous': 'how are you',
        'ça va': 'it\'s going',
        'ça va bien': 'it\'s going well',
        'ça va mal': 'it\'s going badly',
        'pas de problème': 'no problem',
        'pas de question': 'no question',
        'à plus tard': 'see you later',
        'bon appétit': 'enjoy your meal',
        'santé/tchin': 'health/cheers',
        'bonne chance': 'good luck',
        'joyeux anniversaire': 'happy birthday',
        'Joyeux Noël': 'Merry Christmas',
        'Bonne année': 'Happy New Year',
        'je t\'aime': 'I love you',
        'je t\'aime bien': 'I like you',
        'tu me manques': 'I miss you',
        'prends soin de toi': 'take care of yourself',
        'bon voyage': 'have a good trip',
        'bon rétablissement': 'get well soon',
        'félicitations': 'congratulations',
        'enchanté(e)': 'nice to meet you',
        'à plus tard aujourd\'hui': 'see you later today',
        'à demain': 'see you tomorrow',
        'fais de beaux rêves': 'sweet dreams',
        'passez une bonne journée': 'have a good day',
        'bon week-end': 'good weekend',
        'bonnes vacances': 'happy holidays',
        
        // Pronouns
        'je': 'I',
        'tu': 'you',
        'il/elle': 'he/she',
        'nous': 'we',
        'vous/ils': 'you (plural)/they',
        'moi': 'me',
        'le mien': 'mine',
        'le tien': 'yours',
        'le sien': 'his/hers/its',
        'les miens': 'mine (plural)',
        'les tiens': 'yours (plural)',
        'les siens': 'his/hers/its (plural)',
        'le nôtre': 'ours',
        'le vôtre': 'yours (formal/plural)',
        'le leur': 'theirs',
        'mon': 'my',
        'ma': 'my (feminine)',
        'mes': 'my (plural)',
        'ton': 'your',
        'ta': 'your (feminine)',
        'tes': 'your (plural)',
        'son': 'his/her/its',
        'sa': 'his/her/its (feminine)',
        'ses': 'his/her/its (plural)',
        'notre': 'our',
        'nos': 'our (plural)',
        'votre': 'your (formal/plural)',
        'vos': 'your (formal/plural, plural)',
        'leur': 'their',
        
        // Family
        'famille': 'family',
        'père': 'father',
        'mère': 'mother',
        'parents': 'parents',
        'enfant/enfants': 'child/children',
        'fils/fille': 'son/daughter',
        'frère': 'brother',
        'sœur': 'sister',
        'grand-père': 'grandfather',
        'grand-mère': 'grandmother',
        'oncle': 'uncle',
        'tante': 'aunt',
        'cousin/cousine': 'cousin (male/female)',
        'neveu': 'nephew',
        'nièce': 'niece',
        'époux': 'spouse (male)',
        'épouse': 'spouse (female)',
        'mari': 'husband',
        'femme': 'wife/woman',
        'mariage': 'marriage',
        'marié(e)': 'married (male/female)',
        'divorce': 'divorce',
        'divorcé(e)': 'divorced (male/female)',
        'célibataire': 'single (male/female)',
        'fiancé(e)': 'engaged (male/female)',
        'beau-père': 'father-in-law',
        'belle-mère': 'mother-in-law',
        'beau-frère': 'brother-in-law',
        'belle-sœur': 'sister-in-law',
        'gendre': 'son-in-law',
        'belle-fille': 'daughter-in-law',
        'beau-fils': 'stepson',
        'belle-famille': 'in-laws',
        'parrain': 'godfather',
        'marraine': 'godmother',
        'filleul': 'godson',
        'ancêtre': 'ancestor',
        'descendant': 'descendant',
        'postérité': 'posterity',
        'génération': 'generation',
        'héritier': 'heir (male)',
        'héritière': 'heir (female)',
        'orphelin': 'orphan (male)',
        'orpheline': 'orphan (female)',
        'jumeau': 'twin (male)',
        'jumelle': 'twin (female)',
        'aîné(e)': 'elder (male/female)',
        'cadet(te)': 'younger (male/female)',
        'benjamin': 'youngest (male/female)',
        'parenté': 'kinship',
        'lien familial': 'family tie',
        'arbre généalogique': 'family tree',
        'membre': 'member',
        'proche': 'relative/close one',
        'tuteur': 'guardian (male)',
        'tutrice': 'guardian (female)',
        'protégé(e)': 'protégé (male/female)',
        'compagnon': 'companion (male)',
        'compagne': 'companion (female)',
        'partenaire': 'partner',
        'associé(e)': 'associate (male/female)',
        'collègue': 'colleague',
        'camarade': 'comrade/friend',
        'ami(e)': 'friend (male/female)',
        'copain': 'buddy (male)',
        'copine': 'buddy (female)',
        'voisin': 'neighbor (male)',
        'voisine': 'neighbor (female)',
        'connaissance': 'acquaintance',
        'relations': 'relations',
        'contacts': 'contacts',
        'famille nucléaire': 'nuclear family',
        'famille élargie': 'extended family',
        'ménage': 'household',
        'foyer': 'home',
        'résidence': 'residence',
        'maison': 'house',
        
        // People
        'homme': 'man',
        'personne': 'person',
        'gens': 'people',
        'individu': 'individual',
        'être humain': 'human being',
        'personnage': 'character',
        'personnalité': 'personality',
        'célébrité': 'celebrity',
        'vedette': 'star',
        'adulte': 'adult',
        'majeur': 'major/adult',
        'mineur': 'minor',
        'adolescent': 'adolescent (male)',
        'adolescente': 'adolescent (female)',
        'jeune': 'young (male/female)',
        'jeune homme': 'young man',
        'jeune femme': 'young woman',
        'jeunesse': 'youth',
        'bébé': 'baby',
        'nouveau-né': 'newborn (male/female)',
        'vieux': 'old (male)',
        'vieille': 'old (female)',
        'personne âgée': 'elderly person',
        'vétéran': 'veteran',
        'étranger': 'foreigner (male)',
        'étrangère': 'foreigner (female)',
        'immigré(e)': 'immigrant (male/female)',
        'touriste': 'tourist',
        'habitant': 'inhabitant (male/female)',
        'citoyen': 'citizen (male)',
        'citoyenne': 'citizen (female)',
        'national': 'national',
        'résident': 'resident (male/female)',
        'local(e)': 'local (male/female)',
        
        // Professions
        'professionnel(le)': 'professional (male/female)',
        'expert(e)': 'expert (male/female)',
        'spécialiste': 'specialist',
        'technicien(ne)': 'technician (male/female)',
        'artisan(e)': 'artisan (male/female)',
        'ouvrier': 'worker (male)',
        'ouvrière': 'worker (female)',
        'employé(e)': 'employee (male/female)',
        'travailleur': 'worker (male)',
        'travailleuse': 'worker (female)',
        'chef': 'boss/chief',
        'directeur': 'director (male)',
        'directrice': 'director (female)',
        'manager': 'manager',
        'gérant': 'manager',
        'patron': 'boss (male)',
        'patronne': 'boss (female)',
        'supérieur': 'superior (male)',
        'supérieure': 'superior (female)',
        'subordonné(e)': 'subordinate (male/female)',
        'collaborateur': 'collaborator (male)',
        'collaboratrice': 'collaborator (female)',
        'concurrent(e)': 'competitor (male/female)',
        'rivale': 'rival (male/female)',
        'adversaire': 'opponent (male)',
        'adversaire': 'opponent (female)',
        'allié(e)': 'ally (male/female)',
        'ennemi(e)': 'enemy (male/female)',
        'inconnu(e)': 'stranger (male/female)',
        'visiteur': 'visitor (male)',
        'visiteuse': 'visitor (female)',
        'invité': 'guest (male)',
        'invitée': 'guest (female)',
        'hôte': 'host (male)',
        'hôtesse': 'hostess',
        'client': 'client (male)',
        'cliente': 'client (female)',
        'acheteur': 'buyer (male)',
        'acheteuse': 'buyer (female)',
        'consommateur': 'consumer (male)',
        'consommatrice': 'consumer (female)',
        'vendeur': 'seller (male)',
        'vendeuse': 'seller (female)',
        'commerçant(e)': 'merchant (male/female)',
        'fournisseur': 'supplier (male)',
        'fournisseuse': 'supplier (female)',
        'prestataire de services': 'service provider (male/female)',
        'créateur': 'creator (male)',
        'créatrice': 'creator (female)',
        'artiste': 'artist',
        'peintre': 'painter (male)',
        'sculpteur': 'sculptor (male)',
        'sculptrice': 'sculptor (female)',
        'musicien': 'musician (male)',
        'musicienne': 'musician (female)',
        'chanteur': 'singer (male)',
        'chanteuse': 'singer (female)',
        'danseur': 'dancer (male)',
        'danseuse': 'dancer (female)',
        'acteur': 'actor',
        'actrice': 'actress',
        'écrivain(e)': 'writer (male/female)',
        'poète': 'poet (male)',
        'poétesse': 'poet (female)',
        'journaliste': 'journalist',
        'reporter': 'reporter (male)',
        'présentateur': 'presenter (male)',
        'présentatrice': 'presenter (female)',
        'animateur': 'animator (male)',
        'animatrice': 'animator (female)',
        'modérateur': 'moderator (male)',
        'modératrice': 'moderator (female)',
        'professeur': 'professor',
        'enseignant': 'teacher (male)',
        'enseignante': 'teacher (female)',
        'éducateur': 'educator (male)',
        'éducatrice': 'educator (female)',
        'étudiant': 'student (male)',
        'étudiante': 'student (female)',
        'élève': 'pupil',
        'apprenti': 'apprentice (male)',
        'apprentie': 'apprentice (female)',
        'chercheur': 'researcher (male)',
        'chercheuse': 'researcher (female)',
        'scientifique': 'scientist',
        'inventeur': 'inventor (male)',
        'inventrice': 'inventor (female)',
        'médecin': 'doctor',
        'docteur': 'doctor',
        'chirurgien': 'surgeon (male)',
        'chirurgienne': 'surgeon (female)',
        'infirmier': 'nurse (male)',
        'infirmière': 'nurse (female)',
        'pharmacien': 'pharmacist (male)',
        'pharmacienne': 'pharmacist (female)',
        'dentiste': 'dentist',
        'vétérinaire': 'veterinarian',
        'psychologue': 'psychologist',
        'psychiatre': 'psychiatrist',
        'avocat(e)': 'lawyer (male/female)',
        'juge': 'judge',
        'procureur': 'prosecutor (male)',
        'procureure': 'prosecutor (female)',
        'policier': 'police officer',
        'gendarme': 'gendarmerie',
        'militaire': 'military',
        'soldat': 'soldier',
        'officier': 'officer',
        'capitaine': 'captain',
        'général': 'general',
        'homme politique': 'politician (male)',
        'femme politique': 'politician (female)',
        'député(e)': 'deputy (male/female)',
        'sénateur': 'senator (male)',
        'sénatrice': 'senator (female)',
        'ministre': 'minister',
        'président': 'president (male)',
        'présidente': 'president (female)',
        'maire': 'mayor',
        'conseiller': 'councilor (male)',
        'conseillère': 'councilor (female)',
        'administrateur': 'administrator (male)',
        'administratrice': 'administrator (female)',
        'fonctionnaire': 'civil servant',
        'employé public': 'public employee',
        'représentant': 'representative (male)',
        'représentante': 'representative (female)',
        'délégué(e)': 'delegate (male/female)',
        'ambassadeur': 'ambassador (male)',
        'ambassadrice': 'ambassador (female)',
        'consul': 'consul (male/female)',
        'diplomate': 'diplomat',
        'agent': 'agent',
        'espion': 'spy (male)',
        'espionne': 'spy (female)',
        'détective': 'detective',
        'enquêteur': 'investigator (male)',
        'enquêtrice': 'investigator (female)',
        'témoin': 'witness (male/female)',
        'suspect(e)': 'suspect (male/female)',
        'criminel(le)': 'criminal (male/female)',
        'voleur': 'thief (male)',
        'voleuse': 'thief (female)',
        'assassin': 'assassin (male)',
        'assassine': 'assassin (female)',
        'bandit': 'bandit',
        'gangster': 'gangster',
        'prisonnier': 'prisoner (male)',
        'prisonnière': 'prisoner (female)',
        'délinquant(e)': 'delinquent (male/female)',
        'victime': 'victim',
        'plaignant': 'plaintiff (male)',
        'plaignante': 'plaintiff (female)',
        'sauveteur': 'rescuer (male)',
        'sauveteuse': 'rescuer (female)',
        'héros': 'hero (male)',
        'héroïne': 'heroine',
        
        // Adjectives
        'courageux': 'brave (male)',
        'courageuse': 'brave (female)',
        'brave': 'brave (male/female)',
        'timide': 'shy (male/female)',
        'audacieux': 'daring (male)',
        'audacieuse': 'daring (female)',
        'gentil(le)': 'nice/kind (male/female)',
        'méchant(e)': 'mean (male/female)',
        'intelligent(e)': 'intelligent (male/female)',
        'bête': 'stupid (male/female)',
        'sérieux/sérieuse': 'serious (male/female)',
        'drôle': 'funny (male/female)',
        'heureux': 'happy (male)',
        'heureuse': 'happy (female)',
        'malheureux': 'unhappy (male)',
        'malheureuse': 'unhappy (female)',
        'content(e)': 'happy/content (male/female)',
        'triste': 'sad (male/female)',
        'calme': 'calm (male/female)',
        'agité(e)': 'agitated (male/female)',
        'beau': 'beautiful (male)',
        'belle': 'beautiful (female)',
        'joli(e)': 'pretty (male/female)',
        'grand(e)': 'big/large (male/female)',
        'petit(e)': 'small (male/female)',
        'gros(se)': 'fat (male/female)',
        'maigre': 'thin (male/female)',
        'haut(e)': 'tall/high (male/female)',
        'bas/basse': 'short/low (male/female)',
        'long(longue)': 'long (male/female)',
        'court(e)': 'short (male/female)',
        'large': 'wide (male/female)',
        'étroit(e)': 'narrow (male/female)',
        'riche': 'rich (male/female)',
        'pauvre': 'poor (male/female)',
        'fort(e)': 'strong (male/female)',
        'faible': 'weak (male/female)',
        'sain(e)': 'healthy (male/female)',
        'malade': 'sick (male/female)',
        'propre': 'clean (male/female)',
        'sale': 'dirty (male/female)',
        'chaud(e)': 'hot (male/female)',
        'froid(e)': 'cold (male/female)',
        'rapide': 'fast (male/female)',
        'lent(e)': 'slow (male/female)',
        'facile': 'easy (male/female)',
        'difficile': 'difficult (male/female)',
        'nouveau': 'new (male)',
        'nouvelle': 'new (female)',
        'ancien': 'old (male)',
        'ancienne': 'old (female)',
        'premier': 'first (male)',
        'première': 'first (female)',
        'dernier': 'last (male)',
        'dernière': 'last (female)',
        'seul(e)': 'alone (male/female)',
        'ensemble': 'together',
        'libre': 'free (male/female)',
        'mort': 'dead (male)',
        'morte': 'dead (female)',
        'vivant(e)': 'alive (male/female)',
        
        // Places
        'ville': 'city',
        'cité': 'city',
        'métropole': 'metropolis',
        'capitale': 'capital',
        'village': 'village',
        'bourg': 'town',
        'hameau': 'hamlet',
        'quartier': 'neighborhood',
        'région': 'region',
        'province': 'province',
        'département': 'department',
        'canton': 'canton',
        'pays': 'country',
        'nation': 'nation',
        'état': 'state',
        'territoire': 'territory',
        'continent': 'continent',
        'monde': 'world',
        'planète': 'planet',
        'univers': 'universe',
        'terre': 'earth',
        'ciel': 'sky',
        'enfer': 'hell',
        'paradis': 'paradise',
        'soleil': 'sun',
        'lune': 'moon',
        'étoile': 'star',
        'galaxie': 'galaxy',
        'nébuleuse': 'nebula',
        'comète': 'comet',
        'astéroïde': 'asteroid',
        'cosmos': 'cosmos',
        'espace': 'space',
        'vide': 'void',
        'infini': 'infinity',
        'temps': 'time',
        'éternité': 'eternity',
        'instant': 'instant',
        'moment': 'moment',
        'passé': 'past',
        'présent': 'present',
        'futur': 'future',
        'avenir': 'future',
        'histoire': 'history',
        'mémoire': 'memory',
        'souvenir': 'souvenir',
        'tradition': 'tradition',
        'coutume': 'custom',
        'habitude': 'habit',
        'culture': 'culture',
        'civilisation': 'civilization',
        'société': 'society',
        'communauté': 'community',
        'peuple': 'people',
        'langue': 'language',
        'dialecte': 'dialect',
        'accent': 'accent',
        'prononciation': 'pronunciation',
        'mot': 'word',
        'vocabulaire': 'vocabulary',
        'dictionnaire': 'dictionary',
        'grammaire': 'grammar',
        'alphabet': 'alphabet',
        'lettre': 'letter',
        'phrase': 'sentence',
        'texte': 'text',
        'livre': 'book',
        'page': 'page',
        'chapitre': 'chapter',
        'paragraphe': 'paragraph',
        'titre': 'title',
        'auteur': 'author',
        'roman': 'novel',
        'nouvelle': 'short story',
        'conte': 'tale',
        'poésie': 'poetry',
        'théâtre': 'theater',
        'pièce': 'play',
        'acte': 'act',
        'scène': 'scene',
        'cinéma': 'cinema',
        'film': 'film',
        'réalisateur': 'director (male)',
        'réalisatrice': 'director (female)',
        'producteur': 'producer (male)',
        'productrice': 'producer (female)',
        'musique': 'music',
        'chanson': 'song',
        'mélodie': 'melody',
        'rythme': 'rhythm',
        'instrument': 'instrument',
        'orchestre': 'orchestra',
        'chœur': 'choir',
        'opéra': 'opera',
        'ballet': 'ballet',
        'danse': 'dance',
        'chorégraphie': 'choreography',
        'peinture': 'painting',
        'tableau': 'painting/canvas',
        'couleur': 'color',
        'sculpture': 'sculpture',
        'dessin': 'drawing',
        'dessinateur': 'drawer (male)',
        'dessinatrice': 'drawer (female)',
        'photographie': 'photography',
        'photographe': 'photographer (male/female)',
        'photo': 'photo',
        'architecture': 'architecture',
        'architecte': 'architect',
        'bâtiment': 'building',
        'design': 'design',
        'designer': 'designer (male)',
        'création': 'creation',
        'mode': 'fashion',
        'couturier': 'designer (male)',
        'couturière': 'designer (female)',
        'vêtement': 'clothing',
        'bijou': 'jewelry',
        'bijoutier': 'jeweler (male)',
        'bijoutière': 'jeweler (female)',
        'or': 'gold',
        'argent': 'silver/money',
        'diamant': 'diamond',
        'pierres précieuses': 'precious stones',
        'sport': 'sport',
        'athlétisme': 'athletics',
        'football': 'football',
        'basketball': 'basketball',
        'tennis': 'tennis',
        'golf': 'golf',
        'natation': 'swimming',
        'cyclisme': 'cycling',
        'ski': 'skiing',
        'alpinisme': 'mountaineering',
        'escalade': 'climbing',
        'plongée': 'diving',
        'surf': 'surfing',
        'voile': 'sailing',
        'aviron': 'rowing',
        'équitation': 'horse riding',
        'boxe': 'boxing',
        'judo': 'judo',
        'karaté': 'karate',
        'arts martiaux': 'martial arts',
        'compétition': 'competition',
        'match': 'match',
        'tournoi': 'tournament',
        'championnat': 'championship',
        'joueur': 'player (male)',
        'joueuse': 'player (female)',
        'équipe': 'team',
        'entraîneur': 'coach (male)',
        'entraîneuse': 'coach (female)',
        'arbitre': 'referee',
        'stade': 'stadium',
        'terrain': 'field',
        'piscine': 'swimming pool',
        'gymnase': 'gymnasium',
        'santé': 'health',
        'médecine': 'medicine',
        'maladie': 'illness',
        'symptôme': 'symptom',
        'douleur': 'pain',
        'fièvre': 'fever',
        'grippe': 'flu',
        'rhume': 'cold',
        'cancer': 'cancer',
        'diabète': 'diabetes',
        'cœur': 'heart',
        'pression': 'pressure',
        'traitement': 'treatment',
        'médicament': 'medication',
        'opération': 'operation',
        'guérison': 'healing',
        'rétablissement': 'recovery',
        'convalescence': 'convalescence',
        'alimentation': 'food/nutrition',
        'régime': 'diet',
        'diététique': 'dietetics',
        'vitamines': 'vitamins',
        'minéraux': 'minerals',
        'protéines': 'proteins',
        'glucides': 'carbohydrates',
        'nutrition': 'nutrition',
        'équilibre': 'balance',
        'poids': 'weight',
        'obésité': 'obesity',
        'exercice': 'exercise',
        'entraînement': 'training',
        'condition physique': 'physical condition',
        'bien-être': 'well-being',
        'relaxation': 'relaxation',
        'méditation': 'meditation',
        'stress': 'stress',
        'fatigue': 'fatigue',
        'épuisement': 'exhaustion',
        'burn-out': 'burnout',
        'sommeil': 'sleep',
        'insomnie': 'insomnia',
        'rêve': 'dream',
        'cauchemar': 'nightmare',
        'psychologie': 'psychology',
        'thérapie': 'therapy',
        'psychanalyse': 'psychoanalysis',
        'dépression': 'depression',
        'anxiété': 'anxiety',
        'phobie': 'phobia',
        'traumatisme': 'trauma',
        'addiction': 'addiction',
        'dépendance': 'dependence',
        'sevrage': 'withdrawal',
        'prévention': 'prevention',
        'vaccination': 'vaccination',
        'hygiène': 'hygiene',
        'sécurité': 'security',
        'protection': 'protection',
        'danger': 'danger',
        'risque': 'risk',
        'accident': 'accident',
        'urgence': 'emergency',
        'secours': 'help',
        'premiers secours': 'first aid',
        'assurance': 'insurance',
        'couverture': 'coverage',
        'remboursement': 'reimbursement',
        'technologie': 'technology',
        'informatique': 'computer science',
        'ordinateur': 'computer',
        'internet': 'internet',
        'web': 'web',
        'site web': 'website',
        'email': 'email',
        'smartphone': 'smartphone',
        'tablette': 'tablet',
        'application': 'application',
        'logiciel': 'software',
        'programme': 'program',
        'système': 'system',
        'réseau': 'network',
        'wifi': 'wifi',
        'bluetooth': 'bluetooth',
        'imprimante': 'printer',
        'scanner': 'scanner',
        'clavier': 'keyboard',
        'souris': 'mouse',
        'écran': 'screen',
        'moniteur': 'monitor',
        'processeur': 'processor',
        'mémoire': 'memory',
        'stockage': 'storage',
        'disque dur': 'hard drive',
        'cloud': 'cloud',
        'sauvegarde': 'backup',
        'cybersécurité': 'cybersecurity',
        'virus': 'virus',
        'piratage': 'hacking',
        'intelligence artificielle': 'artificial intelligence',
        'robot': 'robot',
        'automatisation': 'automation',
        'réalité virtuelle': 'virtual reality',
        'réalité augmentée': 'augmented reality',
        'innovation': 'innovation',
        'recherche': 'research',
        'développement': 'development',
        'science': 'science',
        'scientifique': 'scientific',
        'laboratoire': 'laboratory',
        'expérimentation': 'experimentation',
        'découverte': 'discovery',
        'invention': 'invention',
        'physique': 'physics',
        'chimie': 'chemistry',
        'biologie': 'biology',
        'mathématiques': 'mathematics',
        'astronomie': 'astronomy',
        'géologie': 'geology',
        'météorologie': 'meteorology',
        'écologie': 'ecology',
        'environnement': 'environment',
        'climat': 'climate',
        'pollution': 'pollution',
        'réchauffement climatique': 'global warming',
        'énergie': 'energy',
        'renouvelable': 'renewable',
        'solaire': 'solar',
        'éolien': 'wind',
        'développement durable': 'sustainable development',
        'recyclage': 'recycling',
        'gestion des déchets': 'waste management',
        'biodiversité': 'biodiversity',
        'espèces en danger': 'endangered species',
        'conservation': 'conservation',
        'préservation': 'preservation',
        'économie': 'economy',
        'finance': 'finance',
        'monnaie': 'currency',
        'budget': 'budget',
        'épargne': 'savings',
        'investissement': 'investment',
        'banque': 'bank',
        'crédit': 'credit',
        'prêt': 'loan',
        'bourse': 'stock market',
        'action': 'share',
        'marché financier': 'financial market',
        'entreprise': 'company',
        'commerce': 'commerce',
        'industrie': 'industry',
        'production': 'production',
        'consommation': 'consumption',
        'importation': 'importation',
        'exportation': 'exportation',
        'commerce international': 'international trade',
        'marketing': 'marketing',
        'publicité': 'advertising',
        'promotion': 'promotion',
        'vente': 'sale',
        'achat': 'purchase',
        'négociation': 'negotiation',
        'contrat': 'contract',
        'travail': 'work',
        'emploi': 'employment',
        'carrière': 'career',
        'profession': 'profession',
        'salaire': 'salary',
        'revenu': 'income',
        'impôt': 'tax',
        'taxe': 'tax',
        'retraite': 'retirement',
        'sécurité sociale': 'social security',
        'éducation': 'education',
        'formation': 'training',
        'apprentissage': 'apprenticeship',
        'compétence': 'skill',
        'qualification': 'qualification',
        'certificat': 'certificate',
        'diplôme': 'diploma',
        'université': 'university',
        'études': 'studies',
        'politique': 'politics',
        'gouvernement': 'government',
        'démocratie': 'democracy',
        'élection': 'election',
        'vote': 'vote',
        'candidat(e)': 'candidate (male/female)',
        'parti politique': 'political party',
        'campagne électorale': 'electoral campaign',
        'parlement': 'parliament',
        'sénat': 'senate',
        'assemblée': 'assembly',
        'loi': 'law',
        'législation': 'legislation',
        'règlement': 'regulation',
        'justice': 'justice',
        'tribunal': 'court',
        'cour': 'court',
        'police': 'police',
        'armée': 'army',
        'défense': 'defense',
        'relations internationales': 'international relations',
        'diplomatie': 'diplomacy',
        'traité': 'treaty',
        'accord': 'agreement',
        'alliance': 'alliance',
        'conflit': 'conflict',
        'guerre': 'war',
        'paix': 'peace',
        'terrorisme': 'terrorism',
        'menace': 'threat',
        'droits de l\'homme': 'human rights',
        'liberté': 'freedom',
        'égalité': 'equality',
        'fraternité': 'fraternity',
        'solidarité': 'solidarity',
        'modernité': 'modernity',
        'progrès': 'progress',
        'mondialisation': 'globalization',
        'communication': 'communication',
        'information': 'information',
        'médias': 'media',
        'journalisme': 'journalism',
        'télévision': 'television',
        'radio': 'radio',
        'presse': 'press',
        'réseaux sociaux': 'social networks',
        'opinion publique': 'public opinion',
        'religion': 'religion',
        'foi': 'faith',
        'croyance': 'belief',
        'dieu': 'god',
        'église': 'church',
        'mosquée': 'mosque',
        'temple': 'temple',
        'synagogue': 'synagogue',
        'prière': 'prayer',
        'rituel': 'ritual',
        'cérémonie': 'ceremony',
        'spiritualité': 'spirituality',
        'philosophie': 'philosophy',
        'éthique': 'ethics',
        'morale': 'morality',
        'valeurs': 'values',
        'art': 'art',
        'esthétique': 'aesthetics',
        'beauté': 'beauty',
        'harmonie': 'harmony',
        'créativité': 'creativity',
        'expression': 'expression',
        'inspiration': 'inspiration',
        'talent': 'talent',
        'loisir': 'leisure',
        'divertissement': 'entertainment',
        'vacances': 'vacations',
        'tourisme': 'tourism',
        'voyage': 'travel',
        'aventure': 'adventure',
        'exploration': 'exploration',
        'nature': 'nature',
        'agriculture': 'agriculture',
        'pêche': 'fishing',
        'élevage': 'livestock farming',
        'récolte': 'harvest',
        'culture': 'cultivation',
        'cuisine': 'kitchen/cuisine',
        'gastronomie': 'gastronomy',
        'vin': 'wine',
        'spiritueux': 'spirits',
        'cocktail': 'cocktail',
        'fête': 'party',
        'célébration': 'celebration',
        'festival': 'festival',
        'concert': 'concert',
        'spectacle': 'show',
        'exposition': 'exhibition',
        'performance': 'performance',
        'forme physique': 'physical form',
        'transport': 'transport',
        'déplacement': 'movement',
        'circulation': 'circulation',
        'urbanisme': 'urbanism',
        'construction': 'construction',
        'habitat': 'habitat',
        'logement': 'housing',
        'immobilier': 'real estate',
        'ressources': 'resources',
        'matières premières': 'raw materials',
        'météo': 'weather',
        'durabilité': 'durability',
        'écosystème': 'ecosystem',
        'croissance': 'growth',
        'patrimoine': 'heritage',
        'identité': 'identity',
        'appartenance': 'belonging',
        'racines': 'roots',
        'diversité': 'diversity',
        'tolérance': 'tolerance',
        'respect': 'respect',
        'entraide': 'mutual aid',
        'coopération': 'cooperation',
        'équilibre': 'balance',
        'citoyenneté': 'citizenship',
        'participation': 'participation',
        'responsabilité': 'responsibility',
        'engagement': 'commitment',
        'implication': 'involvement',
        'développement personnel': 'personal development',
        'épanouissement': 'fulfillment',
        'connaissance de soi': 'self-knowledge',
        'réflexion': 'reflection',
        'sagesse': 'wisdom',
        'expérience': 'experience',
        'maturité': 'maturity',
        'évolution': 'evolution',
        'transformation': 'transformation',
        'changement': 'change',
        'adaptation': 'adaptation',
        'résilience': 'resilience',
        'courage': 'courage',
        'dépassement de soi': 'self-transcendence',
        'dépassement': 'surpassing',
        'accomplissement': 'accomplishment',
        'réalisation': 'realization',
        'succès': 'success',
        'bonheur': 'happiness',
        'plénitude': 'fullness',
        'amour': 'love',
        'amitié': 'friendship',
        'relations humaines': 'human relations',
        'couple': 'couple',
        'partenariat': 'partnership',
        'dialogue': 'dialogue',
        'écoute': 'listening',
        'compréhension': 'understanding',
        'empathie': 'empathy',
        'compassion': 'compassion',
        'partage': 'sharing',
        'générosité': 'generosity',
        'altruisme': 'altruism',
        'confiance': 'trust',
        'considération': 'consideration',
        'estime': 'esteem',
        'reconnaissance': 'recognition',
        'valorisation': 'valorization',
        'authenticité': 'authenticity',
        'sincérité': 'sincerity',
        'honnêteté': 'honesty',
        'intégrité': 'integrity',
        'droiture': 'rectitude',
        'transparence': 'transparency',
        'vérité': 'truth',
        'clarté': 'clarity',
        'lucidité': 'lucidity',
        'vigilance': 'vigilance',
        'attention': 'attention',
        'présence': 'presence',
        'pleine conscience': 'mindfulness',
        'contemplation': 'contemplation',
        
        // Verbs
        'manger': 'to eat',
        'boire': 'to drink',
        'dormir': 'to sleep',
        'travailler': 'to work',
        'étudier': 'to study',
        'jouer': 'to play',
        'chanter': 'to sing',
        'danser': 'to dance',
        'courir': 'to run',
        'marcher': 'to walk',
        'sauter': 'to jump',
        'nager': 'to swim',
        'voler': 'to fly/to steal',
        'grimper': 'to climb',
        'descendre': 'to descend',
        'monter': 'to ascend',
        'arriver': 'to arrive',
        'partir': 'to leave',
        'revenir': 'to come back',
        'retourner': 'to return',
        'sortir': 'to go out',
        'entrer': 'to enter',
        'rester': 'to stay',
        'demeurer': 'to remain',
        'vivre': 'to live',
        'habiter': 'to inhabit',
        'naître': 'to be born',
        'mourir': 'to die',
        'devenir': 'to become',
        'grandir': 'to grow up',
        'vieillir': 'to grow old',
        'changer': 'to change',
        'apprendre': 'to learn',
        'enseigner': 'to teach',
        'expliquer': 'to explain',
        'comprendre': 'to understand',
        'connaître': 'to know',
        'découvrir': 'to discover',
        'trouver': 'to find',
        'chercher': 'to search',
        'perdre': 'to lose',
        'oublier': 'to forget',
        'se souvenir': 'to remember',
        'penser': 'to think',
        'réfléchir': 'to reflect',
        'imaginer': 'to imagine',
        'croire': 'to believe',
        'douter': 'to doubt',
        'espérer': 'to hope',
        'attendre': 'to wait',
        'être patient': 'to be patient',
        'vouloir': 'to want',
        'désirer': 'to desire',
        'souhaiter': 'to wish',
        'préférer': 'to prefer',
        'aimer': 'to love/like',
        'adorer': 'to adore',
        'détester': 'to hate',
        'haïr': 'to hate',
        'pouvoir': 'to be able to',
        'devoir': 'to have to',
        'falloir': 'to be necessary',
        'sembler': 'to seem',
        'apparaître': 'to appear',
        'être': 'to be',
        'avoir': 'to have',
        'faire': 'to do/make',
        'dire': 'to say',
        'voir': 'to see',
        'prendre': 'to take',
        'donner': 'to give',
        'recevoir': 'to receive',
        'offrir': 'to offer',
        'acheter': 'to buy',
        'vendre': 'to sell',
        'payer': 'to pay',
        'coûter': 'to cost',
        'valoir': 'to be worth',
        'peser': 'to weigh',
        'mesurer': 'to measure',
        'compter': 'to count',
        'calculer': 'to calculate',
        'additionner': 'to add',
        'soustraire': 'to subtract',
        'multiplier': 'to multiply',
        'diviser': 'to divide',
        'estimer': 'to estimate',
        'juger': 'to judge',
        'décider': 'to decide',
        'choisir': 'to choose',
        'déterminer': 'to determine',
        'fixer': 'to fix',
        'nommer': 'to name',
        'désigner': 'to designate',
        'appeler': 'to call',
        'qualifier': 'to qualify',
        'définir': 'to define',
        'caractériser': 'to characterize',
        'décrire': 'to describe',
        'représenter': 'to represent',
        'symboliser': 'to symbolize',
        'signifier': 'to signify',
        'indiquer': 'to indicate',
        'montrer': 'to show',
        'démontrer': 'to demonstrate',
        'révéler': 'to reveal',
        'dévoiler': 'to unveil',
        'exposer': 'to expose',
        'présenter': 'to present',
        'introduire': 'to introduce',
        'insérer': 'to insert',
        'incorporer': 'to incorporate',
        'intégrer': 'to integrate',
        'ajouter': 'to add',
        'compléter': 'to complete',
        'supplémenter': 'to supplement',
        'enrichir': 'to enrich',
        'améliorer': 'to improve',
        'parfaire': 'to perfect',
        'achever': 'to complete',
        'parachever': 'to complete thoroughly',
        'finaliser': 'to finalize',
        'terminer': 'to finish',
        'conclure': 'to conclude',
        'interrompre': 'to interrupt',
        'suspendre': 'to suspend',
        'cesser': 'to cease',
        'arrêter': 'to stop',
        'stopper': 'to stop',
        'abandonner': 'to abandon',
        'renoncer': 'to renounce',
        'céder': 'to cede',
        'lâcher': 'to let go',
        'relâcher': 'to release',
        'délivrer': 'to deliver',
        'libérer': 'to free',
        'affranchir': 'to enfranchise',
        'émanciper': 'to emancipate',
        'sauver': 'to save',
        'secourir': 'to rescue',
        'aider': 'to help',
        'assister': 'to assist',
        'soutenir': 'to support',
        'maintenir': 'to maintain',
        'préserver': 'to preserve',
        'conserver': 'to conserve',
        'garder': 'to keep',
        'protéger': 'to protect',
        'défendre': 'to defend',
        'abriter': 'to shelter',
        'couvrir': 'to cover',
        'envelopper': 'to wrap',
        'emballer': 'to pack',
        'emboîter': 'to fit together',
        'enfermer': 'to lock up',
        'enclôturer': 'to enclose',
        'entourer': 'to surround',
        'encercler': 'to encircle',
        'séparer': 'to separate',
        'distinguer': 'to distinguish',
        'différencier': 'to differentiate',
        'comparer': 'to compare',
        'analyser': 'to analyze',
        'examiner': 'to examine',
        'inspecter': 'to inspect',
        'observer': 'to observe',
        'surveiller': 'to monitor',
        'contrôler': 'to control',
        'vérifier': 'to verify',
        'tester': 'to test',
        'essayer': 'to try',
        'expérimenter': 'to experiment',
        'prouver': 'to prove',
        'établir': 'to establish',
        'confirmer': 'to confirm',
        'certifier': 'to certify',
        'garantir': 'to guarantee',
        'assurer': 'to assure',
        'épier': 'to spy on',
        'espionner': 'to spy',
        'percevoir': 'to perceive',
        'discerner': 'to discern',
        'interpréter': 'to interpret',
        'traduire': 'to translate',
        'raconter': 'to tell',
        'narrer': 'to narrate',
        's\'exprimer': 'to express oneself',
        'articuler': 'to articulate',
        'prononcer': 'to pronounce',
        'énoncer': 'to state',
        'déclarer': 'to declare',
        'annoncer': 'to announce',
        'informer': 'to inform',
        'prévenir': 'to prevent',
        'avertir': 'to warn',
        'alerter': 'to alert',
        'signaler': 'to signal',
        'dénoncer': 'to denounce',
        'accuser': 'to accuse',
        'inculper': 'to indict',
        'condamner': 'to condemn',
        'punir': 'to punish',
        'pardonner': 'to forgive',
        'excuser': 'to excuse',
        'absoudre': 'to absolve',
        'gracier': 'to grant amnesty',
        'amnistier': 'to amnesty',
        'se rappeler': 'to remember',
        'mémoriser': 'to memorize',
        's\'entraîner': 'to train oneself',
        'pratiquer': 'to practice',
        'exercer': 'to exercise',
        's\'exercer': 'to exercise oneself',
        'progresser': 'to progress',
        'avancer': 'to advance',
        'se développer': 'to develop oneself',
        'évoluer': 'to evolve',
        'transformer': 'to transform',
        'modifier': 'to modify',
        'altérer': 'to alter',
        'adapter': 'to adapt',
        'ajuster': 'to adjust',
        'accroître': 'to increase',
        'augmenter': 'to augment',
        'diminuer': 'to diminish',
        'réduire': 'to reduce',
        'baisser': 'to lower',
        'se multiplier': 'to multiply oneself',
        'se reproduire': 'to reproduce oneself',
        'émerger': 'to emerge',
        'survenir': 'to occur',
        'se produire': 'to occur',
        'disparaître': 'to disappear',
        's\'évanouir': 'to faint',
        'décéder': 'to pass away',
        'trépasser': 'to pass away',
        'ressusciter': 'to resurrect',
        'renaître': 'to be reborn',
        'réapparaître': 'to reappear',
        'réémerger': 'to re-emerge',
        'exister': 'to exist',
        'subsister': 'to subsist',
        'survivre': 'to survive',
        'durer': 'to last',
        'persister': 'to persist',
        'continuer': 'to continue',
        'se maintenir': 'to maintain oneself',
        'appartenir': 'to belong',
        'dépendre': 'to depend',
        'reposer sur': 'to rest on',
        'concerner': 'to concern',
        'appliquer': 'to apply',
        'affecter': 'to affect',
        'influencer': 'to influence',
        'provoquer': 'to provoke',
        'causer': 'to cause',
        'entraîner': 'to train/to cause',
        'déclencher': 'to trigger',
        'produire': 'to produce',
        'générer': 'to generate',
        'engendrer': 'to beget',
        'procréer': 'to procreate',
        'fabriquer': 'to manufacture',
        'manufacturer': 'to manufacture',
        'confectionner': 'to make',
        'élaborer': 'to elaborate',
        'composer': 'to compose',
        'constituer': 'to constitute',
        'former': 'to form',
        'bâtir': 'to build',
        'ériger': 'to erect',
        'édifier': 'to edify',
        'installer': 'to install',
        'disposer': 'to arrange',
        'placer': 'to place',
        'positionner': 'to position',
        'situer': 'to situate',
        'localiser': 'to locate',
        'organiser': 'to organize',
        'aménager': 'to arrange',
        'arranger': 'to arrange',
        'préparer': 'to prepare',
        'ranger': 'to tidy up',
        'classer': 'to classify',
        'ordonner': 'to order',
        'trier': 'to sort',
        'sélectionner': 'to select',
        'opter': 'to opt',
        'exiger': 'to demand',
        'demander': 'to ask',
        'prier': 'to pray',
        'supplier': 'to beg',
        'implorer': 'to implore',
        'nécessiter': 'to necessitate',
        'insister': 'to insist',
        'poursuivre': 'to pursue',
        'atteindre': 'to reach',
        'obtenir': 'to obtain',
        'gagner': 'to win/to earn',
        'rapporter': 'to bring back',
        'triompher': 'to triumph',
        'réussir': 'to succeed',
        'échouer': 'to fail',
        'manquer': 'to miss',
        'rater': 'to miss',
        'louper': 'to miss',
        'hésiter': 'to hesitate',
        'craindre': 'to fear',
        'redouter': 'to dread',
        'appréhender': 'to apprehend',
        'oser': 'to dare',
        'avouer': 'to admit',
        'confesser': 'to confess',
        'reconnaître': 'to recognize',
        'admettre': 'to admit',
        'nier': 'to deny',
        'démentir': 'to contradict',
        'contredire': 'to contradict',
        'réfuter': 'to refute',
        'argumenter': 'to argue',
        'discuter': 'to discuss',
        'débattre': 'to debate',
        'négocier': 'to negotiate',
        'dialoguer': 'to dialogue',
        'communiquer': 'to communicate',
        'transmettre': 'to transmit',
        'envoyer': 'to send',
        'expédier': 'to expedite',
        'poster': 'to post',
        'livrer': 'to deliver',
        'distribuer': 'to distribute',
        'rassembler': 'to gather',
        'réunir': 'to reunite',
        'grouper': 'to group',
        'associer': 'to associate',
        'lier': 'to link',
        'connecter': 'to connect',
        'brancher': 'to plug in',
        'relier': 'to connect',
        'joindre': 'to join',
        'unir': 'to unite',
        'regarder': 'to look at',
        'écouter': 'to listen',
        'entendre': 'to hear',
        'saisir': 'to grasp',
        'parler': 'to speak',
        'tomber': 'to fall',
        'pousser': 'to push',
        'croître': 'to grow',
        
        // Food and Drinks
        'riz': 'rice',
        'maïs': 'corn',
        'haricots': 'beans',
        'légumes': 'vegetables',
        'frites': 'fries',
        'viande': 'meat',
        'poulet': 'chicken',
        'poisson': 'fish',
        'crevettes': 'shrimp',
        'banane': 'banana',
        'mangue': 'mango',
        'ananas': 'pineapple',
        'pain': 'bread',
        'lapin': 'rabbit',
        'chèvre': 'goat',
        'œuf': 'egg',
        'lait': 'milk',
        'eau': 'water',
        'sucre': 'sugar',
        'sel': 'salt',
        'poivre': 'pepper',
        'bois/arbre': 'wood/tree',
        'fruit': 'fruit',
        'légume': 'vegetable',
        'cari': 'curry',
        'sauce piquante': 'spicy sauce',
        'riz frit': 'fried rice',
        'samosa': 'samosa',
        'ravioli': 'dumpling',
        'cari de viande': 'meat curry',
        'bouillon': 'broth',
        'soupe': 'soup',
        'salade': 'salad',
        'dessert': 'dessert',
        'gâteau': 'cake',
        'soufflé': 'soufflé',
        'crème': 'cream',
        'glace': 'ice cream',
        'chocolat': 'chocolate',
        'bonbon': 'candy',
        'biscuit': 'biscuit',
        'café': 'coffee',
        'thé': 'tea',
        'jus': 'juice',
        'limonade': 'lemonade',
        'bière': 'beer',
        'vin': 'wine',
        'rhum': 'rum',
        'noix de coco': 'coconut',
        'vanille': 'vanilla',
        'cannelle': 'cinnamon',
        'clou de girofle': 'clove',
        'gingembre': 'ginger',
        'feuille de cari': 'curry leaf',
        'tamarin': 'tamarind',
        'carambole': 'starfruit',
        'litchi': 'lychee',
        'longane': 'longan',
        'pois': 'pea',
        'olive': 'olive',
        'fromage': 'cheese',
        'beurre': 'butter',
        'huile': 'oil',
        'vinaigre': 'vinegar',
        'sauce': 'sauce',
        'mayonnaise': 'mayonnaise',
        'moutarde': 'mustard',
        'ketchup': 'ketchup',
        'confiture': 'jam',
        'miel': 'honey',
        'pâtisserie': 'pastry',
        'croissant': 'croissant',
        'sandwich': 'sandwich',
        'pizza': 'pizza',
        'pâtes': 'pasta',
        'nouilles': 'noodles',
        'choucroute': 'sauerkraut',
        'tofu': 'tofu',
        'soja': 'soy',
        'avocat': 'avocado',
        'tomate': 'tomato',
        'oignon': 'onion',
        'épinard': 'spinach',
        'chayote': 'chayote',
        'fèves': 'broad beans',
        'lentilles': 'lentils',
        'cresson': 'watercress',
        'citrouille': 'pumpkin',
        'courgette': 'courgette',
        'concombre': 'cucumber',
        'chou': 'cabbage',
        'carotte': 'carrot',
        'navet': 'turnip',
        'potiron': 'pumpkin',
        'patate douce': 'sweet potato',
        'piment': 'chili pepper',
        'ail': 'garlic',
        'persil': 'parsley',
        'coriandre': 'coriander',
        'thym': 'thyme',
        'romarin': 'rosemary',
        'laurier': 'bay leaf',
        'basilic': 'basil',
        'masala': 'masala',
        'tandoori': 'tandoori',
        'tikka': 'tikka',
        'pain naan': 'naan bread',
        'roti': 'roti',
        'dosa': 'dosa',
        'idli': 'idli',
        'chutney': 'chutney',
        'achar': 'pickle',
        'caviar': 'caviar',
        'foie gras': 'foie gras',
        'truffe': 'truffle',
        'omelette': 'omelette',
        'crêpe': 'pancake',
        'gaufre': 'waffle',
        'beignet': 'doughnut',
        'baguette': 'baguette',
        'hamburger': 'hamburger',
        'hot dog': 'hot dog',
        'taco': 'taco',
        'burrito': 'burrito',
        'kebab': 'kebab',
        'falafel': 'falafel',
        'sushi': 'sushi',
        'sashimi': 'sashimi',
        'ramen': 'ramen',
        'tempura': 'tempura',
        'yakitori': 'yakitori',
        'satay': 'satay',
        'rouleau de printemps': 'spring roll',
        'dim sum': 'dim sum',
        'ravioli': 'dumpling',
        'nouille': 'noodle',
        'canard': 'duck',
        'dinde': 'turkey',
        'agneau': 'lamb',
        'mouton': 'sheep',
        'veau': 'veal',
        'porc': 'pork',
        'bœuf': 'beef',
        'jambon': 'ham',
        'saucisse': 'sausage',
        'bacon': 'bacon',
        'côtelette': 'chop',
        'steak': 'steak',
        'côte de bœuf': 'rib steak',
        'entrecôte': 'entrecote',
        'filet': 'fillet',
        'rôti': 'roast',
        'bouilli': 'boiled',
        'frit': 'fried',
        'grillé': 'grilled',
        'cuit': 'cooked',
        'cru': 'raw',
        'mûr': 'ripe',
        'pas mûr': 'unripe',
        'frais': 'fresh',
        'congelé': 'frozen',
        'en conserve': 'canned',
        'séché': 'dried',
        'salé': 'salty',
        'sucré': 'sweet',
        'acide': 'sour',
        'amer': 'bitter',
        'épicé': 'spicy',
        'fade': 'bland',
        'délicieux': 'delicious',
        'savoureux': 'tasty',
        'sans goût': 'tasteless',
        'mauvais': 'bad',
        'pourri': 'rotten',
        'brûlé': 'burnt',
        'croquant': 'crunchy',
        'mou': 'soft',
        'dur': 'hard',
        'chaud': 'hot',
        'froid': 'cold',
        'tiède': 'warm',
        'glacé': 'iced',
        'bouillant': 'boiling',
        'petit-déjeuner': 'breakfast',
        'déjeuner': 'lunch',
        'dîner': 'dinner',
        'collation': 'snack',
        'goûter': 'snack',
        'apéritif': 'appetizer',
        'digestif': 'digestif',
        'recette': 'recipe',
        'cuisine': 'cuisine',
        'cuisinier': 'cook (male)',
        'cuisinière': 'cook (female)',
        'chef': 'chef',
        'restaurant': 'restaurant',
        'café': 'cafe',
        'bistro': 'bistro',
        'brasserie': 'brasserie',
        'fast food': 'fast food',
        'livraison': 'delivery',
        'emporter': 'takeaway',
        'service': 'service',
        'menu': 'menu',
        'carte': 'menu',
        'plat du jour': 'dish of the day',
        'spécialité': 'specialty',
        'formule': 'set menu',
        'buffet': 'buffet',
        'self-service': 'self-service',
        'boisson': 'drink',
        'alcool': 'alcohol',
        'boisson alcoolisée': 'alcoholic beverage',
        'boisson non alcoolisée': 'non-alcoholic beverage',
        'cocktail': 'cocktail',
        'vin rouge': 'red wine',
        'vin blanc': 'white wine',
        'vin rosé': 'rose wine',
        'champagne': 'champagne',
        'cidre': 'cider',
        'whisky': 'whisky',
        'vodka': 'vodka',
        'gin': 'gin',
        'liqueur': 'liqueur',
        'nectar': 'nectar',
        'nectar de fruits': 'fruit nectar',
        'smoothie': 'smoothie',
        'milkshake': 'milkshake',
        'soda': 'soda',
        'eau minérale': 'mineral water',
        'eau gazeuse': 'sparkling water',
        'eau plate': 'still water',
        'thé glacé': 'iced tea',
        'infusion': 'herbal tea',
        'café au lait': 'coffee with milk',
        'expresso': 'espresso',
        'cappuccino': 'cappuccino',
        'latte': 'latte',
        'chocolat chaud': 'hot chocolate',
        'sirop': 'syrup',
        'boisson énergisante': 'energy drink',
        'boisson sportive': 'sports drink',
        'canette': 'can',
        'bouteille': 'bottle',
        'verre': 'glass',
        'tasse': 'cup',
        'mug': 'mug',
        'pichet': 'pitcher',
        'carafe': 'carafe',
        'bol': 'bowl',
        'assiette': 'plate',
        'couvert': 'cutlery',
        'fourchette': 'fork',
        'couteau': 'knife',
        'cuillère': 'spoon',
        'cuillère à soupe': 'tablespoon',
        'cuillère à café': 'teaspoon',
        'plat': 'dish',
        'poêle': 'pan',
        'casserole': 'casserole',
        'faitout': 'stockpot',
        'marmite': 'pot',
        'passoire': 'colander',
        'strainer': 'strainer',
        'fouet': 'whisk',
        'rouleau à pâtisserie': 'rolling pin',
        'planche à découper': 'cutting board',
        'balance': 'scale',
        'measure': 'measure',
        'four': 'oven',
        'micro-ondes': 'microwave',
        'plaque de cuisson': 'stove',
        'grill': 'grill',
        'frigo': 'fridge',
        'congélateur': 'freezer',
        'lave-vaisselle': 'dishwasher',
        'évier': 'sink',
        'robinet': 'tap',
        'table': 'table',
        'chaise': 'chair',
        'tabouret': 'stool',
        'nappe': 'tablecloth',
        'serviette': 'napkin',
        'napperon': 'placemat',
        'viande': 'meat',
        'fruits de mer': 'seafood',
        'volaille': 'poultry',
        'charcuterie': 'deli meat',
        'viennoiserie': 'pastry',
        'confiserie': 'confectionery',
        'épicerie': 'grocery',
        'marché': 'market',
        'supermarché': 'supermarket',
        'hypermarché': 'hypermarket',
        'épicerie fine': 'delicatessen',
        'boulangerie': 'bakery',
        'boucher': 'butcher',
        'poissonnier': 'fishmonger',
        'crémier': 'dairy',
        'marchand de vin': 'wine merchant',
        'primeur': 'greengrocer',
        'pâtissier': 'pastry chef',
        'boulanger': 'baker',
        'serveur': 'waiter',
        'serveuse': 'waitress',
        'sommelier': 'sommelier',
        'barman': 'bartender',
        'barmaid': 'barmaid',
        'plongeur': 'dishwasher',
        'restaurateur': 'restaurateur',
        'chef de cuisine': 'head chef',
        'sous-chef': 'sous-chef',
        'commis de cuisine': 'kitchen assistant',
        'chocolatier': 'chocolatier',
        'glacier': 'ice cream maker',
        'traiteur': 'caterer',
        'livreur': 'delivery person',
        'client': 'customer',
        'habitué': 'regular customer',
        'critique gastronomique': 'food critic',
        'guide gastronomique': 'restaurant guide',
        'étoile Michelin': 'Michelin star',
        'repas': 'meal',
        'festin': 'feast',
        'banquet': 'banquet',
        'casse-croûte': 'snack',
        'en-cas': 'snack',
        'pique-nique': 'picnic',
        'barbecue': 'barbecue',
        'grillade': 'grill',
        'ingrédient': 'ingredient',
        'préparation': 'preparation',
        'cuisson': 'cooking',
        'assaisonnement': 'seasoning',
        'épice': 'spice',
        'herbe aromatique': 'herb',
        'condiment': 'condiment',
        'vinaigrette': 'vinaigrette',
        'marinade': 'marinade',
        'fumage': 'smoking',
        'saumure': 'brine',
        'conservation': 'preservation',
        'stérilisation': 'sterilization',
        'pasteurisation': 'pasteurization',
        'congélation': 'freezing',
        'lyophilisation': 'freeze-drying',
        'déshydratation': 'dehydration',
        'mise en conserve': 'canning',
        'saumurage': 'brining',
        'salaison': 'salting',
        'séchage': 'drying',
        'macération': 'maceration',
        'fermentation': 'fermentation',
        'levure': 'yeast',
        'levain': 'sourdough',
        'pâte': 'dough',
        'pâte levée': 'leavened dough',
        'pâte feuilletée': 'puff pastry',
        'pâte brisée': 'shortcrust pastry',
        'pâte sablée': 'sweet shortcrust pastry',
        'pâte à choux': 'choux pastry',
        'pâte à pizza': 'pizza dough',
        'pâte à pain': 'bread dough',
        'pâte à tarte': 'pie dough',
        'pâte à crêpes': 'crêpe batter',
        'pâte à gaufres': 'waffle batter',
        'pâte à beignets': 'doughnut batter',
        'pâte à biscuits': 'cookie dough',
        'pâte à gâteau': 'cake batter',
        'génoise': 'sponge cake',
        'biscuit sec': 'dry biscuit',
        'biscuit moelleux': 'soft biscuit',
        'biscuit au beurre': 'butter biscuit',
        'biscuit au chocolat': 'chocolate biscuit',
        'biscuit à la confiture': 'jam biscuit',
        'biscuit à la vanille': 'vanilla biscuit',
        'biscuit à la cannelle': 'cinnamon biscuit',
        'biscuit au gingembre': 'ginger biscuit',
        'biscuit au citron': 'lemon biscuit',
        'biscuit à l\'orange': 'orange biscuit',
        'biscuit à la fraise': 'strawberry biscuit',
        'biscuit à la framboise': 'raspberry biscuit',
        'biscuit à la myrtille': 'blueberry biscuit',
        'biscuit à la pomme': 'apple biscuit',
        'biscuit à la poire': 'pear biscuit',
        'biscuit à la pêche': 'peach biscuit',
        'biscuit à l\'abricot': 'apricot biscuit',
        'biscuit à la cerise': 'cherry biscuit',
        'biscuit à la prune': 'plum biscuit',
        'biscuit à la figue': 'fig biscuit',
        'biscuit à la noix': 'nut biscuit',
        'biscuit à la noisette': 'hazelnut biscuit',
        'biscuit à l\'amande': 'almond biscuit',
        'biscuit à la cacahuète': 'peanut biscuit',
        'biscuit à la pistache': 'pistachio biscuit',
        'biscuit à la noix de coco': 'coconut biscuit',
        'biscuit au chocolat blanc': 'white chocolate biscuit',
        'biscuit au chocolat au lait': 'milk chocolate biscuit',
        'biscuit au chocolat noir': 'dark chocolate biscuit',
        'biscuit au caramel': 'caramel biscuit',
        'biscuit au miel': 'honey biscuit',
        'biscuit à la mélasse': 'molasses biscuit',
        'biscuit à la réglisse': 'licorice biscuit',
        'biscuit à la menthe': 'mint biscuit',
        'biscuit à la rose': 'rose biscuit',
        'biscuit au thé': 'tea biscuit',
        'biscuit au café': 'coffee biscuit',
        'biscuit au rhum': 'rum biscuit',
        'biscuit au kirsch': 'kirsch biscuit',
        'biscuit au cognac': 'cognac biscuit',
        'biscuit à l\'armagnac': 'armagnac biscuit',
        'biscuit au calvados': 'calvados biscuit',
        'biscuit au whisky': 'whisky biscuit',
        'biscuit au gin': 'gin biscuit',
        'biscuit à la vodka': 'vodka biscuit',
        'biscuit au champagne': 'champagne biscuit',
        'biscuit au vin rouge': 'red wine biscuit',
        'biscuit au vin blanc': 'white wine biscuit',
        'biscuit au vin rosé': 'rose wine biscuit',
        'biscuit à la bière': 'beer biscuit',
        'biscuit au cidre': 'cider biscuit',
        'biscuit au jus de pomme': 'apple juice biscuit',
        'biscuit au jus d\'orange': 'orange juice biscuit',
        'biscuit au jus de citron': 'lemon juice biscuit',
        'biscuit au jus de pamplemousse': 'grapefruit juice biscuit',
        'biscuit au jus de tomate': 'tomato juice biscuit',
        'biscuit au jus de carotte': 'carrot juice biscuit',
        'biscuit au jus de betterave': 'beetroot juice biscuit',
        'biscuit au jus de céleri': 'celery juice biscuit',
        'biscuit au jus de concombre': 'cucumber juice biscuit',
        'biscuit au jus de poivron': 'pepper juice biscuit',
        'biscuit au jus d\'oignon': 'onion juice biscuit',
        'biscuit au jus d\'ail': 'garlic juice biscuit',
        'biscuit au jus de gingembre': 'ginger juice biscuit',
        'biscuit au jus de curcuma': 'turmeric juice biscuit',
        'biscuit au jus de paprika': 'paprika juice biscuit',
        'biscuit au jus de piment': 'chili juice biscuit',
        'biscuit au jus de vanille': 'vanilla juice biscuit',
        'biscuit au jus de cannelle': 'cinnamon juice biscuit',
        'biscuit au jus de muscade': 'nutmeg juice biscuit',
        'biscuit au jus de clou de girofle': 'clove juice biscuit',
        'biscuit au jus de cardamome': 'cardamom juice biscuit',
        'biscuit au jus d\'anis': 'anise juice biscuit',
        'biscuit au jus de fenouil': 'fennel juice biscuit',
        'biscuit au jus de coriandre': 'coriander juice biscuit',
        'biscuit au jus de persil': 'parsley juice biscuit',
        'biscuit au jus de cerfeuil': 'chervil juice biscuit',
        'biscuit au jus de ciboulette': 'chives juice biscuit',
        'biscuit au jus de menthe': 'mint juice biscuit',
        'biscuit au jus de basilic': 'basil juice biscuit',
        'biscuit au jus de thym': 'thyme juice biscuit',
        'biscuit au jus de romarin': 'rosemary juice biscuit',
        'biscuit au jus de laurier': 'bay leaf juice biscuit',
        'biscuit au jus de sauge': 'sage juice biscuit',
        'biscuit au jus de marjolaine': 'marjoram juice biscuit',
        'biscuit au jus d\'origan': 'oregano juice biscuit',
        'biscuit au jus de sarriette': 'savory juice biscuit',
        'biscuit au jus de livèche': 'lovage juice biscuit',
        'biscuit au jus d\'angélique': 'angelica juice biscuit',
        'biscuit au jus de mélisse': 'lemon balm juice biscuit',
        'biscuit au jus de verveine': 'verbena juice biscuit',
        'biscuit au jus de camomille': 'chamomile juice biscuit',
        'biscuit au jus de tilleul': 'linden juice biscuit',
        'biscuit au jus de hibiscus': 'hibiscus juice biscuit',
        'biscuit au jus de rose': 'rose juice biscuit',
        'biscuit au jus de jasmin': 'jasmine juice biscuit',
        'biscuit au jus de violette': 'violet juice biscuit',
        'biscuit au jus de lavande': 'lavender juice biscuit',
        'biscuit au jus de géranium': 'geranium juice biscuit',
        'biscuit au jus de muguet': 'lily of the valley juice biscuit',
        'biscuit au jus de réséda': 'mignonette juice biscuit',
        'biscuit au jus de myrte': 'myrtle juice biscuit',
        'biscuit au jus de laurier-rose': 'oleander juice biscuit',
        'biscuit au jus de gardénia': 'gardenia juice biscuit',
        'biscuit au jus de magnolia': 'magnolia juice biscuit',
        'biscuit au jus de camélia': 'camellia juice biscuit',
        'biscuit au jus d\'azalée': 'azalea juice biscuit',
        'biscuit au jus de rhododendron': 'rhododendron juice biscuit',
        'biscuit au jus d\'hortensia': 'hydrangea juice biscuit',
        'biscuit au jus de pivoine': 'peony juice biscuit',
        'biscuit au jus de dahlia': 'dahlia juice biscuit',
        'biscuit au jus de glaïeul': 'gladiolus juice biscuit',
        'biscuit au jus de lys': 'lily juice biscuit',
        'arbre/bois': 'tree/wood',
        'animal': 'animal',
        'oiseau': 'bird',
        'fleur': 'flower',
        'rivière': 'river',
        'mer': 'sea',
        'montagne': 'mountain',
        'pluie': 'rain',
        'tonnerre': 'thunder',
        'arc-en-ciel': 'rainbow',
        'vent': 'wind',
        'soleil': 'sun',
        'lune': 'moon',
        'étoile': 'star',
        'noir': 'black',
        'blanc': 'white',
        'rouge': 'red',
        'jaune': 'yellow',
        'bleu': 'blue',
        'vert': 'green',
        'or': 'gold',
        'argent': 'silver/money',
        'maison': 'house',
        'jardin': 'garden',
        'boue': 'mud',
        'roche': 'rock',
        'sable': 'sand',
        'forêt': 'forest',
        'plaine': 'plain',
        'cascade': 'waterfall',
        'volcan': 'volcano',
        'île': 'island',
        'côte': 'coast',
        'récif': 'reef',
        'corail': 'coral',
        'crique': 'creek',
        'chien': 'dog',
        'chat': 'cat',
        'souris': 'mouse',
        'insectes': 'insects',
        'papillon': 'butterfly',
        'araignée': 'spider',
        'serpent': 'snake',
        'lézard': 'lizard',
        'crapaud': 'toad',
        'grenouille': 'frog',
        'cigale': 'cicada',
        'moustique': 'mosquito',
        'coq': 'rooster',
        'poule': 'hen',
        'cheval': 'horse',
        'zèbre': 'zebra',
        'lion': 'lion',
        'tigre': 'tiger',
        'éléphant': 'elephant',
        'girafe': 'giraffe',
        'singe': 'monkey',
        'bœuf': 'ox',
        'vache': 'cow',
        'mouton': 'sheep',
        'chèvre': 'goat',
        'cochon': 'pig',
        'cerf': 'deer',
        'biche': 'doe',
        'loup': 'wolf',
        'renard': 'fox',
        'ours': 'bear',
        'requin': 'shark',
        'baleine': 'whale',
        'dauphin': 'dolphin',
        'tortue': 'turtle',
        'crabe': 'crab',
        'langouste': 'rock lobster',
        'pieuvre': 'octopus',
        'calmar': 'squid',
        'corne': 'horn',
        'pied': 'foot',
        'œil': 'eye',
        'bouche': 'mouth',
        'nez': 'nose',
        'oreille': 'ear',
        'cheveux': 'hair',
        'peau': 'skin',
        'dent': 'tooth',
        'langue': 'tongue',
        'sang': 'blood',
        'cœur': 'heart',
        'poumon': 'lung',
        'estomac': 'stomach',
        'intestins': 'intestines',
        'os': 'bone',
        'clé': 'key',
        'porte': 'door',
        'fenêtre': 'window',
        'toit': 'roof',
        'mur': 'wall',
        'sol': 'floor',
        'cour': 'yard',
        'route': 'road',
        'chemin': 'path',
        'pont': 'bridge',
        'école': 'school',
        'hôpital': 'hospital',
        'mairie': 'town hall',
        'église': 'church',
        'poste': 'post office',
        'banque': 'bank',
        'magasin': 'shop/store',
        'marché': 'market',
        'restaurant': 'restaurant',
        'hôtel': 'hotel',
        'cinéma': 'cinema',
        'musée': 'museum',
        'bibliothèque': 'library',
        'parc': 'park',
        'place': 'square',
        'stade': 'stadium',
        'aéroport': 'airport',
        'station-service': 'gas station',
        'arrêt de bus': 'bus stop',
        'taxi': 'taxi',
        'bus': 'bus',
        'minibus': 'minibus',
        'voiture': 'car',
        'moto': 'motorcycle',
        'bicyclette': 'bicycle',
        'bateau': 'boat',
        'navire': 'ship',
        'avion': 'airplane',
        'hélicoptère': 'helicopter',
        'train': 'train',
        'tramway': 'tramway',
        'métro': 'subway',

        // Time and Weather
        'lundi': 'Monday',
        'mardi': 'Tuesday',
        'mercredi': 'Wednesday',
        'jeudi': 'Thursday',
        'vendredi': 'Friday',
        'samedi': 'Saturday',
        'dimanche': 'Sunday',
        'janvier': 'January',
        'février': 'February',
        'mars': 'March',
        'avril': 'April',
        'mai': 'May',
        'juin': 'June',
        'juillet': 'July',
        'août': 'August',
        'septembre': 'September',
        'octobre': 'October',
        'novembre': 'November',
        'décembre': 'December',
        'l\'année': 'the year',
        'le mois': 'the month',
        'la semaine': 'the week',
        'le jour': 'the day',
        'la nuit': 'the night',
        'temps': 'time',
        'moment': 'moment',
        'matin': 'morning',
        'après-midi': 'afternoon',
        'soir': 'evening',
        'midi': 'noon',
        'minuit': 'midnight',
        'avant': 'before',
        'après': 'after',
        'quand/comment': 'when/how',
        'alors': 'then',
        'pendant ce temps': 'meanwhile',
        'actuellement': 'currently',
        'souvent': 'often',
        'parfois': 'sometimes',
        'rarement': 'rarely',
        'toujours': 'always',
        'jamais': 'never',
        'aujourd\'hui': 'today',
        'hier': 'yesterday',
        'demain': 'tomorrow',
        'après-demain': 'the day after tomorrow',
        'avant-hier': 'the day before yesterday',
        'la saison': 'the season',
        'été': 'summer',
        'hiver': 'winter',
        'automne': 'autumn',
        'printemps': 'spring',
        'chaud': 'hot',
        'froid': 'cold',
        'bon': 'good',
        'mauvais': 'bad',
        'venteux': 'windy',
        'nuageux': 'cloudy',
        'ensoleillé': 'sunny',
        'pluvieux': 'rainy',
        'orage': 'thunderstorm',
        'tremblement de terre': 'earthquake',
        'cyclone/ouragan': 'cyclone/hurricane',
        'raz de marée/tsunami': 'tidal wave/tsunami',
        'inondation': 'flood',
        'sécheresse': 'drought',
        'tempête': 'storm',
        'brise': 'breeze',
        'brouillard': 'fog',
        'brume': 'mist',
        'rosée': 'dew',
        'glace': 'ice',
        'neige': 'snow',
        'grêle': 'hail',
        'éclair': 'lightning',
        'pluie': 'rain',
        'univers': 'universe',
        'galaxie': 'galaxy',
        'système solaire': 'solar system',
        'terre': 'earth',
        'planète': 'planet',
        'satellite': 'satellite',
        'comète': 'comet',
        'astéroïde': 'asteroid',
        'météorite': 'meteorite',
        'trou noir': 'black hole',
        'nébuleuse': 'nebula',
        'cosmos': 'cosmos',
        'espace': 'space',
        'infini': 'infinity',
        'éternité': 'eternity',
        'zéro': 'zero',
        'un': 'one',
        'deux': 'two',
        'trois': 'three',
        'quatre': 'four',
        'cinq': 'five',
        'six': 'six',
        'sept': 'seven',
        'huit': 'eight',
        'neuf': 'nine',
        'dix': 'ten',
        'onze': 'eleven',
        'douze': 'twelve',
        'treize': 'thirteen',
        'quatorze': 'fourteen',
        'quinze': 'fifteen',
        'seize': 'sixteen',
        'dix-sept': 'seventeen',
        'dix-huit': 'eighteen',
        'dix-neuf': 'nineteen',
        'vingt': 'twenty',
        'vingt-et-un': 'twenty-one',
        'trente': 'thirty',
        'quarante': 'forty',
        'cinquante': 'fifty',
        'soixante': 'sixty',
        'quatre-vingt': 'eighty',
        'cent': 'one hundred',
        'deux cents': 'two hundred',
        'mille': 'one thousand',
        'deux mille': 'two thousand',
        'un million': 'one million',
        'premier': 'first',
        'deuxième': 'second',
        'troisième': 'third',
        'quatrième': 'fourth',
        'cinquième': 'fifth',
        'sixième': 'sixth',
        'septième': 'seventh',
        'huitième': 'eighth',
        'neuvième': 'ninth',
        'dixième': 'tenth',
        'dernier': 'last',
        'quelques': 'a few',
        'beaucoup': 'many',
        'trop': 'too much',
        'un peu': 'a little',
        'loin': 'far',
        'près': 'near',
        'ici': 'here',
        'là': 'there',
        'partout': 'everywhere',
        'nulle part': 'nowhere',
        'côté': 'side',
        'au-dessus': 'above',
        'en dessous': 'below',
        'dedans': 'inside',
        'dehors': 'outside',
        'devant': 'in front of',
        'derrière': 'behind',
        'entre': 'between',
        'parmi': 'among',
        'contre': 'against',
        'sous': 'under',
        'sur': 'on',
        'dans': 'in',
        'avec': 'with',
        'sans': 'without',
        'pour': 'for',
        'par': 'by',
        'à': 'at/to',
        'de': 'of/from',
        'depuis': 'since',
        'jusqu\'à': 'until',
        'qui': 'who/which',
        'quoi': 'what',
        'où': 'where',
        'pourquoi': 'why',
        'combien': 'how much/many',
        'quelle heure': 'what time',
        'quel homme': 'which man',
        'à qui': 'whose',
        'lesquels': 'which ones',
        'quoi (informel)': 'what (informal)',
        'pourquoi (informel)': 'why (informal)',
        'comment (informel)': 'how (informal)',
        'qui peut': 'who can',
        'qui veut': 'who wants',
        'qu\'est-ce que c\'est': 'what is that',
        'qui est-ce': 'who is that',
        'qu\'as-tu dit': 'what did you say',
        'que sont ceux-là': 'what are those',
        'et': 'and',
        'mais': 'but',
        'ou': 'or',
        'si': 'if',
        'parce que': 'because',
        'donc': 'therefore',
        'car': 'because',
        'conséquemment': 'consequently',
        'même si': 'even if',
        'tandis que': 'while',
        'pendant': 'during',
        'afin que': 'so that',
        'afin de': 'in order to',
        'sinon': 'otherwise',
        'ni': 'neither',
        'soit': 'either',
        'soit... soit...': 'either... or...',
        'ni... ni...': 'neither... nor...',
        'non seulement... mais aussi': 'not only... but also',
        'comme': 'like/as',
        'par rapport à': 'compared to',
        'accompagné de': 'accompanied by',
        'grâce à': 'thanks to',
        'malgré': 'despite',
        'loin de': 'far from',
        'près de': 'close to',
        'en face de': 'opposite',
        'à côté de': 'next to',
        'autour de': 'around',
        'autre que': 'other than',
        'sauf': 'except for',
        'à partir de': 'starting from',
        'chez': 'at someone\'s place',
        'vers': 'towards',
        'selon': 'according to',
        'hors de': 'outside of',
        'quelque part': 'somewhere',
        'là-bas': 'over there',
        'd\'ici': 'from here',
        'de là': 'from there',
        'jusqu\'ici': 'until here',
        'jusqu\'là': 'until there',
        'depuis quand': 'since when',
        'depuis longtemps': 'for a long time',
        'depuis peu': 'recently',
        'pendant que': 'while',
        'avant que': 'before',
        'après que': 'after',
        'aussitôt que': 'as soon as',
        'chaque fois que': 'every time that',
        'la première fois que': 'the first time that',
        'la dernière fois que': 'the last time that',
        'toutes les fois que': 'every time that',
        'bien que': 'although',
        'comme si': 'as if',
        'si... que': 'so... that',
        'tellement... que': 'so... that',
        'trop... pour': 'too... to',
        'assez... pour': 'enough... to',
        'prêt à': 'ready to',
        'en train de': 'in the process of',
        'sur le point de': 'about to',
        'obligé de': 'obliged to',
        'forcé de': 'forced to',
        'habitué à': 'used to',
        'sensé': 'supposed to',
        'capable de': 'capable of',
        'en mesure de': 'able to',
        'dans l\'impossibilité de': 'unable to',
        'faute de': 'for lack of',
        'à cause de': 'because of',
        'en raison de': 'due to',
        'en dépit de': 'despite',
        'au lieu de': 'instead of',
        'à force de': 'by dint of',
        'par manque de': 'for lack of',
        'par excès de': 'by excess of',
        'au risque de': 'at the risk of',
        'dans le but de': 'with the aim of',
        'dans l\'espoir de': 'in the hope of',
        'en vue de': 'with a view to',
        'pour ce qui est de': 'as for',
        'quant à': 'as for',
        'en ce qui concerne': 'concerning',
        'au sujet de': 'about',
        'touchant': 'concerning',
        'relativement à': 'relative to',
        'vis-à-vis de': 'in relation to',
        'en fonction de': 'depending on',
        'conformément à': 'in accordance with',
        'suivant': 'according to',
        'outre': 'besides',
        'en plus de': 'in addition to',
        'y compris': 'including',
        'notamment': 'in particular',
        'spécialement': 'especially',
        'particulièrement': 'particularly',
        'surtout': 'above all',
        'principalement': 'mainly',
        'essentiellement': 'essentially',
        'fondamentalement': 'fundamentally',
        'généralement': 'generally',
        'habituellement': 'usually',
        'normalement': 'normally',
        'ordinairement': 'ordinarily',
        'couramment': 'commonly',
        'fréquemment': 'frequently',
        'régulièrement': 'regularly',
        'occasionnellement': 'occasionally',
        'exceptionnellement': 'exceptionally',
        'de temps en temps': 'from time to time',
        'ne... jamais': 'never',
        'toujours est-il que': 'be that as it may',
        'en tout cas': 'in any case',
        'dans tous les cas': 'in any case',
        'dans tous les cas de figure': 'in all cases',
        'quoi qu\'il en soit': 'be that as it may',
        'en définitive': 'ultimately',
        'finalement': 'finally',
        'au final': 'in the end',
        'à la fin': 'at the end',
        'à terme': 'in the long run',
        'sur le long terme': 'in the long term',
        'sur le court terme': 'in the short term',
        'à court terme': 'in the short term',
        'à moyen terme': 'in the medium term',
        'à long terme': 'in the long term',
        'dès maintenant': 'from now on',
        'désormais': 'from now on',
        'à partir de maintenant': 'from now on',
        'à compter de ce jour': 'from this day forward',
        'd\'ores et déjà': 'as of now',
        'déjà': 'already',
        'encore': 'still/yet',
        'ne... plus': 'no longer',
        'ne... point': 'not at all',
        'ne... guère': 'hardly',
        'ne... nulle part': 'nowhere',
        'ne... rien': 'nothing',
        'ne... personne': 'nobody',
        'ne... que': 'only',
        'ne... aucun': 'no',
        'ne... nul': 'no',
        'seulement': 'only',
        'uniquement': 'only',
        'simplement': 'simply',
        'juste': 'just',
        'exactement': 'exactly',
        'précisément': 'precisely',
        'approximativement': 'approximately',
        'environ': 'approximately',
        'à peu près': 'approximately',
        'presque': 'almost',
        'quasiment': 'almost',
        'pratiquement': 'practically',
        'virtuellement': 'virtually',
        'réellement': 'really',
        'effectivement': 'indeed',
        'vraiment': 'truly',
        'sincèrement': 'sincerely',
        'franchement': 'frankly',
        'honnêtement': 'honestly',
        'carrément': 'frankly/blatantly',
        'certainement': 'certainly',
        'sûrement': 'surely',
        'probablement': 'probably',
        'peut-être': 'maybe',
        'éventuellement': 'possibly',
        'potentiellement': 'potentially',
        'naturellement': 'naturally',
        'logiquement': 'logically',
        'évidemment': 'obviously',
        'bien sûr': 'of course',
        'bien entendu': 'of course',
        'sans doute': 'without a doubt',
        'sans aucun doute': 'without any doubt',
        'indubitablement': 'indubitably',
        'assurément': 'assuredly',
        'manifestement': 'manifestly',
        'clairement': 'clearly',
        'nettement': 'clearly',
        'distinctement': 'distinctly',
        'spécifiquement': 'specifically',
        'de temps à autre': 'from time to time',
    }
},
