const CREOLE_ENGLISH_DICTIONARY = {
    'creole-en': {
        'bonzour': 'hello',
        'sava': 'hi',
        'bonswar': 'good evening',
        'bonn nwi': 'good night',
        'aouarvoir': 'goodbye',
        'o byento': 'see you soon',
        'byenvini': 'welcome',
        'mèrsi': 'thank you',
        'si ou plé': 'please',
        'pardon': 'sorry',
        'ekskiz-mwa': 'excuse me',
        'dézolé': 'apologetic/sorry',
        'wi': 'yes',
        'non': 'no',
        'petèt': 'maybe',
        'byen sir': 'of course',
        'absoliman': 'absolutely',
        'mi pa koné': 'I don\'t know',
        'mi konprann': 'I understand',
        'mi pa konprann': 'I don\'t understand',
        'komman i alé': 'how are you',
        'i alé': 'it\'s going',
        'i alé byen': 'it\'s going well',
        'i alé mal': 'it\'s going badly',
        'pa problèm': 'no problem',
        'pa kwésyon': 'no question',
        'aplita': 'see you later',
        'bonapéti': 'enjoy your meal',
        'santé': 'health/cheers',
        'bon chans': 'good luck',
        'bonn anivèrsèr': 'happy birthday',
        'bon Nwèl': 'Merry Christmas',
        'bonn anné': 'Happy New Year',
        'mon ti aim': 'I love you',
        'mon ti kontan ou': 'I like you',
        'mon mank ou': 'I miss you',
        'pran swen dou': 'take care of yourself',
        'bon voyaz': 'have a good trip',
        'bon rétablisman': 'get well soon',
        'félicitasyon': 'congratulations',
        'ou plézi': 'nice to meet you',
        'o tou à lèr': 'see you later today',
        'o demin': 'see you tomorrow',
        'fé bèl rèv': 'sweet dreams',
        'pas bon zourné': 'have a good day',
        'bon wikenn': 'good weekend',
        'bon vakans': 'happy holidays',
        'mi': 'I',
        'ou': 'you',
        'li': 'he/she/it',
        'nou': 'we',
        'zot': 'you (plural)/they',
        'mwin': 'me',
        'la mwin': 'mine',
        'la tou': 'yours',
        'la li': 'his/hers/its',
        'lé mwin': 'mine (plural)',
        'lé tou': 'yours (plural)',
        'lé li': 'his/hers/its (plural)',
        'la notr': 'ours',
        'la votr': 'yours (formal/plural)',
        'la lor': 'theirs',
        'mon': 'my',
        'ma': 'my (feminine)',
        'mé': 'my (plural)',
        'ton': 'your',
        'ta': 'your (feminine)',
        'té': 'your (plural)',
        'son': 'his/her/its',
        'sa': 'his/her/its (feminine)',
        'sé': 'his/her/its (plural)',
        'notr': 'our',
        'no': 'our (plural)',
        'votr': 'your (formal/plural)',
        'vo': 'your (formal/plural, plural)',
        'lor': 'their',
        'famill': 'family',
        'pèr': 'father',
        'mèr': 'mother',
        'paran': 'parents',
        'zanfan': 'child/children',
        'fiy': 'son/daughter',
        'frèr': 'brother',
        'sér': 'sister',
        'granpèr': 'grandfather',
        'granmèr': 'grandmother',
        'onkl': 'uncle',
        'tant': 'aunt',
        'kouzin': 'cousin (male/female)',
        'névé': 'nephew',
        'niès': 'niece',
        'épou': 'spouse (male)',
        'épous': 'spouse (female)',
        'mari': 'husband',
        'fanm': 'wife/woman',
        'mariaz': 'marriage',
        'marié': 'married (male/female)',
        'divors': 'divorce',
        'divorsé': 'divorced (male/female)',
        'sélibatèr': 'single (male/female)',
        'fiyansé': 'engaged (male/female)',
        'bopèr': 'father-in-law',
        'bèlmèr': 'mother-in-law',
        'bofrèr': 'brother-in-law',
        'bèlsér': 'sister-in-law',
        'zanndr': 'son-in-law',
        'bèlfiy': 'daughter-in-law',
        'bofiy': 'stepson',
        'bèlfamill': 'in-laws',
        'parrén': 'godfather',
        'maren': 'godmother',
        'fiyul': 'godson',
        'ansètr': 'ancestor',
        'déandan': 'descendant',
        'postérité': 'posterity',
        'zénérasyon': 'generation',
        'éritié': 'heir (male)',
        'érityèr': 'heir (female)',
        'orfan': 'orphan (male)',
        'orfanin': 'orphan (female)',
        'zomò': 'twin (male)',
        'zomòl': 'twin (female)',
        'aîné': 'elder (male/female)',
        'kadé': 'younger (male/female)',
        'benjamin': 'youngest (male/female)',
        'paranté': 'kinship',
        'lyen famiyal': 'family tie',
        'arbr zénéralojik': 'family tree',
        'mimbr': 'member',
        'proch': 'relative/close one',
        'titér': 'guardian (male)',
        'titris': 'guardian (female)',
        'protéjé': 'protégé (male/female)',
        'konpagnon': 'companion (male)',
        'konpagn': 'companion (female)',
        'parténèr': 'partner',
        'asosyé': 'associate (male/female)',
        'kolèg': 'colleague',
        'kamarad': 'comrade/friend',
        'lami': 'friend (male/female)',
        'kopén': 'buddy (male)',
        'kopin': 'buddy (female)',
        'voazén': 'neighbor (male)',
        'voazin': 'neighbor (female)',
        'konésans': 'acquaintance',
        'relasyon': 'relations',
        'kontak': 'contacts',
        'famill nikléèr': 'nuclear family',
        'famill élarzi': 'extended family',
        'ménaz': 'household',
        'foyé': 'home',
        'domicil': 'residence',
        'lakaz': 'house',
        'nonm': 'man',
        'moun': 'person',
        'zanmoun': 'people',
        'endividi': 'individual',
        'èr imen': 'human being',
        'pèrsonaz': 'character',
        'pèrsonalité': 'personality',
        'sélébrité': 'celebrity',
        'védèt': 'star',
        'adilt': 'adult',
        'mazé': 'major/adult',
        'miné': 'minor',
        'adolésan': 'adolescent (male)',
        'adolésant': 'adolescent (female)',
        'zenn': 'young (male/female)',
        'zenn nonm': 'young man',
        'zenn fanm': 'young woman',
        'zennés': 'youth',
        'bébé': 'baby',
        'novo-né': 'newborn (male/female)',
        'vyé': 'old (male)',
        'vyéy': 'old (female)',
        'moun azé': 'elderly person',
        'vétéran': 'veteran',
        'étrazé': 'foreigner (male)',
        'étrazér': 'foreigner (female)',
        'imigré': 'immigrant (male/female)',
        'tourist': 'tourist',
        'abitan': 'inhabitant (male/female)',
        'sitoyé': 'citizen (male)',
        'sitoyénn': 'citizen (female)',
        'nasyonal': 'national',
        'rézidan': 'resident (male/female)',
        'lokal': 'local (male/female)',
        'profésyonèl': 'professional (male/female)',
        'ékspar': 'expert (male/female)',
        'spésyalist': 'specialist',
        'téknisyen': 'technician (male/female)',
        'artizan': 'artisan (male/female)',
        'ouvré': 'worker (male)',
        'ouvrir': 'worker (female)',
        'anplwayé': 'employee (male/female)',
        'travayé': 'worker (male)',
        'travayéz': 'worker (female)',
        'chéf': 'boss/chief',
        'dirèktèr': 'director (male)',
        'dirèktris': 'director (female)',
        'manazé': 'manager',
        'zéran': 'manager',
        'patron': 'boss (male)',
        'patronn': 'boss (female)',
        'sipéryé': 'superior (male)',
        'sipéryér': 'superior (female)',
        'sibordoné': 'subordinate (male/female)',
        'kolaboratér': 'collaborator (male)',
        'kolaboratris': 'collaborator (female)',
        'konkiran': 'competitor (male/female)',
        'rival': 'rival (male/female)',
        'advèrsèr': 'opponent (male)',
        'advèrsèr': 'opponent (female)',
        'alyé': 'ally (male/female)',
        'anmi': 'enemy (male/female)',
        'inkonu': 'stranger (male/female)',
        'vizité': 'visitor (male)',
        'vizitéz': 'visitor (female)',
        'anvit': 'guest (male)',
        'anvité': 'guest (female)',
        'ot': 'host (male)',
        'otés': 'hostess',
        'klyan': 'client (male)',
        'klyant': 'client (female)',
        'achté': 'buyer (male)',
        'achtéz': 'buyer (female)',
        'konzomatér': 'consumer (male)',
        'konzomatris': 'consumer (female)',
        'vandé': 'seller (male)',
        'vandéz': 'seller (female)',
        'komérsan': 'merchant (male/female)',
        'fournisé': 'supplier (male)',
        'fourniséz': 'supplier (female)',
        'préstatèr': 'service provider (male/female)',
        'kréatér': 'creator (male)',
        'kréatris': 'creator (female)',
        'artist': 'artist',
        'péntr': 'painter (male)',
        'skilptér': 'sculptor (male)',
        'skilptris': 'sculptor (female)',
        'mizisyen': 'musician (male)',
        'mizisyenn': 'musician (female)',
        'chanté': 'singer (male)',
        'chantéz': 'singer (female)',
        'dansé': 'dancer (male)',
        'danséz': 'dancer (female)',
        'akté': 'actor',
        'aktris': 'actress',
        'ékrivén': 'writer (male/female)',
        'poét': 'poet (male)',
        'poétés': 'poet (female)',
        'zournalist': 'journalist',
        'rporté': 'reporter (male)',
        'prézantatér': 'presenter (male)',
        'prézantatris': 'presenter (female)',
        'animatér': 'animator (male)',
        'animatris': 'animator (female)',
        'modératér': 'moderator (male)',
        'modératris': 'moderator (female)',
        'profésé': 'professor',
        'anségnan': 'teacher (male)',
        'anségnant': 'teacher (female)',
        'édikatér': 'educator (male)',
        'édikatris': 'educator (female)',
        'étydyan': 'student (male)',
        'étydiant': 'student (female)',
        'élév': 'pupil',
        'apran': 'apprentice (male)',
        'aprant': 'apprentice (female)',
        'sersé': 'researcher (male)',
        'serséz': 'researcher (female)',
        'syantifik': 'scientist',
        'anvantér': 'inventor (male)',
        'anvantris': 'inventor (female)',
        'médésin': 'doctor',
        'doktèr': 'doctor',
        'sirizyen': 'surgeon (male)',
        'sirizyenn': 'surgeon (female)',
        'infirmyé': 'nurse (male)',
        'infirmyér': 'nurse (female)',
        'farmasyen': 'pharmacist (male)',
        'farmasyenn': 'pharmacist (female)',
        'dantis': 'dentist',
        'vétérinèr': 'veterinarian',
        'psikolog': 'psychologist',
        'psikiatr': 'psychiatrist',
        'avoka': 'lawyer (male/female)',
        'zuj': 'judge',
        'prokiré': 'prosecutor (male)',
        'prokirér': 'prosecutor (female)',
        'polisyé': 'police officer',
        'zandarm': 'gendarmerie',
        'militèr': 'military',
        'solda': 'soldier',
        'ofisyé': 'officer',
        'kapitén': 'captain',
        'zénéral': 'general',
        'politisyen': 'politician (male)',
        'politisyenn': 'politician (female)',
        'dépyé': 'deputy (male/female)',
        'sénatér': 'senator (male)',
        'sénatris': 'senator (female)',
        'ministr': 'minister',
        'prézidan': 'president (male)',
        'prézidant': 'president (female)',
        'mèr': 'mayor',
        'konséyé': 'councilor (male)',
        'konséyér': 'councilor (female)',
        'administratér': 'administrator (male)',
        'administratris': 'administrator (female)',
        'fonksyonèr': 'civil servant',
        'anplwayé piblik': 'public employee',
        'réprézantan': 'representative (male)',
        'réprézantant': 'representative (female)',
        'délégué': 'delegate (male/female)',
        'anbasadé': 'ambassador (male)',
        'anbasadris': 'ambassador (female)',
        'konsul': 'consul (male/female)',
        'diplomat': 'diplomat',
        'azan': 'agent',
        'éspyon': 'spy (male)',
        'éspyonn': 'spy (female)',
        'déktiv': 'detective',
        'ankètér': 'investigator (male)',
        'ankètris': 'investigator (female)',
        'témwan': 'witness (male/female)',
        'suspèk': 'suspect (male/female)',
        'kriminel': 'criminal (male/female)',
        'volé': 'thief (male)',
        'voléz': 'thief (female)',
        'asasan': 'assassin (male)',
        'asasinn': 'assassin (female)',
        'bandi': 'bandit',
        'gangstér': 'gangster',
        'prizonyé': 'prisoner (male)',
        'prizonyér': 'prisoner (female)',
        'délinkan': 'delinquent (male/female)',
        'viktim': 'victim',
        'plénian': 'plaintiff (male)',
        'plényant': 'plaintiff (female)',
        'souvété': 'rescuer (male)',
        'souvétéz': 'rescuer (female)',
        'éro': 'hero (male)',
        'éroyn': 'heroine',
        'kourazé': 'brave (male)',
        'kourazéz': 'brave (female)',
        'brav': 'brave (male/female)',
        'timid': 'shy (male/female)',
        'odasié': 'daring (male)',
        'odasiéz': 'daring (female)',
        'zanmèl': 'nice/kind (male/female)',
        'méchan': 'mean (male/female)',
        'intélijan': 'intelligent (male/female)',
        'bèt': 'stupid (male/female)',
        'séryé': 'serious (male/female)',
        'dròl': 'funny (male/female)',
        'éré': 'happy (male)',
        'éréz': 'happy (female)',
        'maléré': 'unhappy (male)',
        'maléréz': 'unhappy (female)',
        'kontan': 'happy/content (male/female)',
        'trist': 'sad (male/female)',
        'kalm': 'calm (male/female)',
        'azité': 'agitated (male/female)',
        'bo': 'beautiful (male)',
        'bèl': 'beautiful (female)',
        'joli': 'pretty (male/female)',
        'gran': 'big/large (male/female)',
        'ti': 'small (male/female)',
        'gro': 'fat (male/female)',
        'mains': 'thin (male/female)',
        'ho': 'tall/high (male/female)',
        'ba': 'short/low (male/female)',
        'lon': 'long (male/female)',
        'kour': 'short (male/female)',
        'larz': 'wide (male/female)',
        'étrèt': 'narrow (male/female)',
        'rich': 'rich (male/female)',
        'povr': 'poor (male/female)',
        'for': 'strong (male/female)',
        'fèb': 'weak (male/female)',
        'sén': 'healthy (male/female)',
        'malad': 'sick (male/female)',
        'propr': 'clean (male/female)',
        'sal': 'dirty (male/female)',
        'cho': 'hot (male/female)',
        'frèt': 'cold (male/female)',
        'rapit': 'fast (male/female)',
        'lan': 'slow (male/female)',
        'fasil': 'easy (male/female)',
        'difisil': 'difficult (male/female)',
        'nouvò': 'new (male)',
        'nouvèl': 'new (female)',
        'ansyen': 'old (male)',
        'ansyenn': 'old (female)',
        'premyé': 'first (male)',
        'premyér': 'first (female)',
        'dényé': 'last (male)',
        'dényér': 'last (female)',
        'sèl': 'alone (male/female)',
        'ansanbl': 'together',
        'libr': 'free (male/female)',
        'mor': 'dead (male)',
        'mòr': 'dead (female)',
        'vivan': 'alive (male/female)',
        'vil': 'city',
        'sité': 'city',
        'métropol': 'metropolis',
        'kapital': 'capital',
        'vilaz': 'village',
        'bor': 'town',
        'amò': 'hamlet',
        'kartié': 'neighborhood',
        'rézion': 'region',
        'provinss': 'province',
        'départman': 'department',
        'kanton': 'canton',
        'péyi': 'country',
        'nasyon': 'nation',
        'éta': 'state',
        'teritwar': 'territory',
        'kontinan': 'continent',
        'mond': 'world',
        'planèt': 'planet',
        'linivèr': 'universe',
        'latèr': 'earth',
        'siel': 'sky',
        'anfèr': 'hell',
        'paradi': 'paradise',
        'soléy': 'sun',
        'lalin': 'moon',
        'zétwal': 'star',
        'galaksi': 'galaxy',
        'nébilis': 'nebula',
        'komèt': 'comet',
        'astéroid': 'asteroid',
        'kosmos': 'cosmos',
        'espas': 'space',
        'vid': 'void',
        'anfini': 'infinity',
        'tan': 'time',
        'éternité': 'eternity',
        'instan': 'instant',
        'momàn': 'moment',
        'pasé': 'past',
        'prézan': 'present',
        'fitir': 'future',
        'avenir': 'future',
        'istwar': 'history',
        'mémoir': 'memory',
        'souvnir': 'souvenir',
        'tradisyon': 'tradition',
        'koutim': 'custom',
        'abitid': 'habit',
        'kiltir': 'culture',
        'sivilizasyon': 'civilization',
        'sosyété': 'society',
        'komynoté': 'community',
        'pèp': 'people',
        'lang': 'language',
        'dyalèkt': 'dialect',
        'aksan': 'accent',
        'prononsasyon': 'pronunciation',
        'mo': 'word',
        'vokabilèr': 'vocabulary',
        'diksyonnèr': 'dictionary',
        'gramèr': 'grammar',
        'alfabé': 'alphabet',
        'lètr': 'letter',
        'fraz': 'sentence',
        'téks': 'text',
        'livr': 'book',
        'paz': 'page',
        'chapitr': 'chapter',
        'paragraf': 'paragraph',
        'titr': 'title',
        'oté': 'author',
        'roman': 'novel',
        'nuvèl': 'short story',
        'kont': 'tale',
        'poézi': 'poetry',
        'téatr': 'theater',
        'pyès': 'play',
        'akt': 'act',
        'sén': 'scene',
        'sinéma': 'cinema',
        'film': 'film',
        'réalizatér': 'director (male)',
        'réalizatris': 'director (female)',
        'prodikté': 'producer (male)',
        'prodiktris': 'producer (female)',
        'mizik': 'music',
        'chanson': 'song',
        'mélodi': 'melody',
        'ritm': 'rhythm',
        'instruman': 'instrument',
        'orkèstr': 'orchestra',
        'koral': 'choir',
        'opéra': 'opera',
        'balé': 'ballet',
        'dans': 'dance',
        'korégrafi': 'choreography',
        'péntir': 'painting',
        'tablo': 'painting/canvas',
        'koulèr': 'color',
        'skilptir': 'sculpture',
        'désén': 'drawing',
        'désinatér': 'drawer (male)',
        'désinatris': 'drawer (female)',
        'fotografi': 'photography',
        'fotograf': 'photographer (male/female)',
        'foto': 'photo',
        'arkitektir': 'architecture',
        'arkitekt': 'architect',
        'batiman': 'building',
        'dézén': 'design',
        'dézénér': 'designer (male)',
        'kréasyon': 'creation',
        'mod': 'fashion',
        'koutiryé': 'designer (male)',
        'kouturiér': 'designer (female)',
        'vètman': 'clothing',
        'bijou': 'jewelry',
        'zwayé': 'jeweler (male)',
        'zwayér': 'jeweler (female)',
        'lor': 'gold',
        'arzan': 'silver/money',
        'dyaman': 'diamond',
        'pyèr présyé': 'precious stones',
        'spor': 'sport',
        'atlétism': 'athletics',
        'futbòl': 'football',
        'basketbòl': 'basketball',
        'ténis': 'tennis',
        'gòlf': 'golf',
        'natasion': 'swimming',
        'siklism': 'cycling',
        'ski': 'skiing',
        'alpinism': 'mountaineering',
        'éskalad': 'climbing',
        'plonzé': 'diving',
        'surf': 'surfing',
        'voal': 'sailing',
        'aviron': 'rowing',
        'ékitasyon': 'horse riding',
        'boks': 'boxing',
        'zudo': 'judo',
        'karaté': 'karate',
        'ar martiyo': 'martial arts',
        'konpétisyon': 'competition',
        'match': 'match',
        'tournwa': 'tournament',
        'chanpionna': 'championship',
        'zoué': 'player (male)',
        'zouzé': 'player (female)',
        'ékip': 'team',
        'antrénné': 'coach (male)',
        'antrénnéz': 'coach (female)',
        'arbitr': 'referee',
        'stad': 'stadium',
        'térén': 'field',
        'pisin': 'swimming pool',
        'zimnaz': 'gymnasium',
        'santé': 'health',
        'médésin': 'medicine',
        'maladi': 'illness',
        'simptom': 'symptom',
        'doulér': 'pain',
        'fyèvr': 'fever',
        'grip': 'flu',
        'rum': 'cold',
        'kansér': 'cancer',
        'dyabèt': 'diabetes',
        'kèr': 'heart',
        'présyon': 'pressure',
        'trétmman': 'treatment',
        'médikaman': 'medication',
        'opérasyon': 'operation',
        'gyérizon': 'healing',
        'rétablisman': 'recovery',
        'konvalésans': 'convalescence',
        'alimantasyon': 'food/nutrition',
        'rézim': 'diet',
        'dyététik': 'dietetics',
        'vitamin': 'vitamins',
        'minéro': 'minerals',
        'protéin': 'proteins',
        'glisid': 'carbohydrates',
        'nitrisyon': 'nutrition',
        'ékilibr': 'balance',
        'pwa': 'weight',
        'obézité': 'obesity',
        'égsèrsis': 'exercise',
        'antrénnman': 'training',
        'kondisyon fizik': 'physical condition',
        'byenètr': 'well-being',
        'relaksazon': 'relaxation',
        'méditasyon': 'meditation',
        'strès': 'stress',
        'fatig': 'fatigue',
        'épizman': 'exhaustion',
        'burn-ot': 'burnout',
        'soméy': 'sleep',
        'inzomni': 'insomnia',
        'rèv': 'dream',
        'kochmar': 'nightmare',
        'psikoloji': 'psychology',
        'térapie': 'therapy',
        'psikanaliz': 'psychoanalysis',
        'déprésyon': 'depression',
        'anksyété': 'anxiety',
        'fobi': 'phobia',
        'tròtism': 'trauma',
        'adiksion': 'addiction',
        'dépadans': 'dependence',
        'sévraz': 'withdrawal',
        'prévansyon': 'prevention',
        'vaksinasyon': 'vaccination',
        'yizyén': 'hygiene',
        'sékirité': 'security',
        'proteksyon': 'protection',
        'danzé': 'danger',
        'risk': 'risk',
        'aksidan': 'accident',
        'irzans': 'emergency',
        'sékou': 'help',
        'premyé sékou': 'first aid',
        'asirans': 'insurance',
        'kouvèrtir': 'coverage',
        'ranbourseman': 'reimbursement',
        'téknoloji': 'technology',
        'informatik': 'computer science',
        'ordinatér': 'computer',
        'intèrnèt': 'internet',
        'web': 'web',
        'sit web': 'website',
        'imèl': 'email',
        'smartfon': 'smartphone',
        'tablèt': 'tablet',
        'aplikasyon': 'application',
        'lojisyèl': 'software',
        'progrann': 'program',
        'sistém': 'system',
        'rézo': 'network',
        'wifi': 'wifi',
        'blutut': 'bluetooth',
        'imprimant': 'printer',
        'skané': 'scanner',
        'klavyé': 'keyboard',
        'souri': 'mouse',
        'ékrann': 'screen',
        'monitér': 'monitor',
        'prosesér': 'processor',
        'mémoir': 'memory',
        'stokaz': 'storage',
        'disk dur': 'hard drive',
        'klod': 'cloud',
        'souvégard': 'backup',
        'sibérsékirité': 'cybersecurity',
        'virus': 'virus',
        'pirataz': 'hacking',
        'intélijans artisyisyèl': 'artificial intelligence',
        'robot': 'robot',
        'otomatisazon': 'automation',
        'réalité virtièl': 'virtual reality',
        'réalité ogmenté': 'augmented reality',
        'inovasyon': 'innovation',
        'sers': 'research',
        'dévelopman': 'development',
        'syans': 'science',
        'syantifik': 'scientific',
        'laboratwar': 'laboratory',
        'éksérimantasyon': 'experimentation',
        'dékouvèrt': 'discovery',
        'anvansyon': 'invention',
        'fizik': 'physics',
        'chimi': 'chemistry',
        'bioloji': 'biology',
        'matématik': 'mathematics',
        'astronomi': 'astronomy',
        'zéoloji': 'geology',
        'météoroloji': 'meteorology',
        'ékoloji': 'ecology',
        'anvironman': 'environment',
        'klima': 'climate',
        'polisyon': 'pollution',
        'réchaufman klimatik': 'global warming',
        'énerzi': 'energy',
        'renouvlabl': 'renewable',
        'solèr': 'solar',
        'éolyen': 'wind',
        'dévelopman durabl': 'sustainable development',
        'siklaz': 'recycling',
        'zèsyon dé déché': 'waste management',
        'byodivérsité': 'biodiversity',
        'espés an danzé': 'endangered species',
        'konèrvasyon': 'conservation',
        'prézèrvasyon': 'preservation',
        'ékonomi': 'economy',
        'finans': 'finance',
        'monay': 'currency',
        'budzé': 'budget',
        'épargn': 'savings',
        'anvestisman': 'investment',
        'bank': 'bank',
        'krédi': 'credit',
        'anpran': 'loan',
        'pré': 'loan',
        'bours': 'stock market',
        'aksyon': 'share',
        'marché finansyé': 'financial market',
        'antrepriz': 'company',
        'komèrs': 'commerce',
        'indistri': 'industry',
        'prodiksyon': 'production',
        'konsozmasyon': 'consumption',
        'anportasyon': 'importation',
        'ékspòrtasyon': 'exportation',
        'komèrs entèrnasyonal': 'international trade',
        'marketing': 'marketing',
        'piblisité': 'advertising',
        'promosyon': 'promotion',
        'vant': 'sale',
        'acha': 'purchase',
        'négosiasyon': 'negotiation',
        'kontra': 'contract',
        'travay': 'work',
        'anploé': 'employment',
        'karyér': 'career',
        'profésyon': 'profession',
        'salèr': 'salary',
        'revénu': 'income',
        'anpo': 'tax',
        'taks': 'tax',
        'rètrait': 'retirement',
        'sékirité sosyal': 'social security',
        'édikasyon': 'education',
        'formazon': 'training',
        'aprantisaz': 'apprenticeship',
        'konpétans': 'skill',
        'kalifikasyon': 'qualification',
        'sèrtifikat': 'certificate',
        'diplom': 'diploma',
        'linivèrsité': 'university',
        'étyd': 'studies',
        'politik': 'politics',
        'gouvanman': 'government',
        'démokrasi': 'democracy',
        'éléksyon': 'election',
        'vot': 'vote',
        'kandida': 'candidate (male/female)',
        'parti politik': 'political party',
        'kanpan élèktoral': 'electoral campaign',
        'parlman': 'parliament',
        'séna': 'senate',
        'asanblé': 'assembly',
        'lwa': 'law',
        'lézislasion': 'legislation',
        'régliman': 'regulation',
        'zistis': 'justice',
        'tribinal': 'court',
        'kour': 'court',
        'polis': 'police',
        'armé': 'army',
        'défans': 'defense',
        'relasyon entèrnasyonal': 'international relations',
        'diplomasi': 'diplomacy',
        'tréyé': 'treaty',
        'akor': 'agreement',
        'alyans': 'alliance',
        'konfli': 'conflict',
        'gèr': 'war',
        'pé': 'peace',
        'térorism': 'terrorism',
        'menas': 'threat',
        'dwa dé lom': 'human rights',
        'libèrté': 'freedom',
        'égalité': 'equality',
        'fratérnité': 'fraternity',
        'solidarité': 'solidarity',
        'modèrnité': 'modernity',
        'progrè': 'progress',
        'globalizasyon': 'globalization',
        'mondyalizasyon': 'globalization',
        'komynikasyon': 'communication',
        'informazon': 'information',
        'médya': 'media',
        'zournalism': 'journalism',
        'télevizyon': 'television',
        'radio': 'radio',
        'prés': 'press',
        'rézo sosyo': 'social networks',
        'opinyon piblik': 'public opinion',
        'rélijyon': 'religion',
        'fwa': 'faith',
        'kroyans': 'belief',
        'dyé': 'god',
        'légliz': 'church',
        'moské': 'mosque',
        'tanpl': 'temple',
        'sinagòg': 'synagogue',
        'priyèr': 'prayer',
        'ritiyèl': 'ritual',
        'sérémoni': 'ceremony',
        'spiritwalité': 'spirituality',
        'filozofi': 'philosophy',
        'étik': 'ethics',
        'moral': 'morality',
        'valé': 'values',
        'ar': 'art',
        'estétik': 'aesthetics',
        'bauté': 'beauty',
        'armoni': 'harmony',
        'kréativité': 'creativity',
        'éksprésyon': 'expression',
        'inspirasyon': 'inspiration',
        'talan': 'talent',
        'lwazir': 'leisure',
        'divèrtisman': 'entertainment',
        'vakans': 'vacations',
        'tourism': 'tourism',
        'vwiyaz': 'travel',
        'avantir': 'adventure',
        'éksplorazon': 'exploration',
        'natiir': 'nature',
        'agrikiltir': 'agriculture',
        'péché': 'fishing',
        'élévaz': 'livestock farming',
        'rékolt': 'harvest',
        'kultivazon': 'cultivation',
        'kizin': 'kitchen/cuisine',
        'gastronomi': 'gastronomy',
        'van': 'wine',
        'spiritié': 'spirits',
        'koktéy': 'cocktail',
        'fèt': 'party',
        'sélébrasyon': 'celebration',
        'festival': 'festival',
        'konsèr': 'concert',
        'spètakl': 'show',
        'éksposisyon': 'exhibition',
        'pèrformans': 'performance',
        'form fizik': 'physical form',
        'transpor': 'transport',
        'déplasman': 'movement',
        'sirkilasyon': 'circulation',
        'irbanism': 'urbanism',
        'konstriksyon': 'construction',
        'abita': 'habitat',
        'lozman': 'housing',
        'imobilié': 'real estate',
        'résours': 'resources',
        'matyèr prémyé': 'raw materials',
        'météo': 'weather',
        'durabilité': 'durability',
        'ékosistém': 'ecosystem',
        'kroysans': 'growth',
        'patrimwan': 'heritage',
        'idantité': 'identity',
        'apartnans': 'belonging',
        'rasin': 'roots',
        'divèrsité': 'diversity',
        'tolérans': 'tolerance',
        'respè': 'respect',
        'antréid': 'mutual aid',
        'koopérasyon': 'cooperation',
        'ékilibr': 'balance',
        'sitwayanneté': 'citizenship',
        'partisipasyon': 'participation',
        'réponsabilité': 'responsibility',
        'angazman': 'commitment',
        'implikasyon': 'involvement',
        'dévelopman pèrsonèl': 'personal development',
        'épanisman': 'fulfillment',
        'konésans dé lwa-mèm': 'self-knowledge',
        'réflèksyon': 'reflection',
        'sazès': 'wisdom',
        'éksperyans': 'experience',
        'matirité': 'maturity',
        'évolisyon': 'evolution',
        'transformazon': 'transformation',
        'zanzman': 'change',
        'adaptazon': 'adaptation',
        'rézilyans': 'resilience',
        'kouraz': 'courage',
        'dépasman dé lwa-mèm': 'self-transcendence',
        'dépasman': 'surpassing',
        'akomplisman': 'accomplishment',
        'réalizasyon': 'realization',
        'siksé': 'success',
        'bonèr': 'happiness',
        'plénitid': 'fullness',
        'lamour': 'love',
        'amitié': 'friendship',
        'relasyon imén': 'human relations',
        'kupl': 'couple',
        'parténaria': 'partnership',
        'dyalog': 'dialogue',
        'ékout': 'listening',
        'konprénsyon': 'understanding',
        'anpati': 'empathy',
        'konpasyon': 'compassion',
        'partaz': 'sharing',
        'zénérosité': 'generosity',
        'altrism': 'altruism',
        'konfyans': 'trust',
        'konsidérasyon': 'consideration',
        'estim': 'esteem',
        'rekonésans': 'recognition',
        'valorizasyon': 'valorization',
        'otantisité': 'authenticity',
        'sinsérité': 'sincerity',
        'onèté': 'honesty',
        'intégrité': 'integrity',
        'droitir': 'rectitude',
        'transparans': 'transparency',
        'vérité': 'truth',
        'klarté': 'clarity',
        'lisidité': 'lucidity',
        'vizilans': 'vigilance',
        'atansyon': 'attention',
        'présans': 'presence',
        'mindfulness': 'mindfulness',
        'plén konfyans': 'full awareness',
        'kontanplasyon': 'contemplation',
        'manz': 'to eat',
        'bwar': 'to drink',
        'dormi': 'to sleep',
        'travay': 'to work',
        'étidyé': 'to study',
        'zoué': 'to play',
        'chanté': 'to sing',
        'dansé': 'to dance',
        'kouri': 'to run',
        'mars': 'to walk',
        'soté': 'to jump',
        'nagé': 'to swim',
        'volé': 'to fly/to steal',
        'gripé': 'to climb',
        'désan': 'to descend',
        'monté': 'to ascend',
        'arivé': 'to arrive',
        'parti': 'to leave',
        'rvini': 'to come back',
        'rourné': 'to return',
        'soti': 'to go out',
        'antré': 'to enter',
        'rété': 'to stay',
        'dmoré': 'to remain',
        'viv': 'to live',
        'abité': 'to inhabit',
        'nèss': 'to be born',
        'mouri': 'to die',
        'dévini': 'to become',
        'granndir': 'to grow up',
        'vyéyir': 'to grow old',
        'zanzé': 'to change',
        'apran': 'to learn',
        'anségné': 'to teach',
        'ékspliké': 'to explain',
        'konprann': 'to understand',
        'koné': 'to know',
        'dékouvr': 'to discover',
        'trouvé': 'to find',
        'sersé': 'to search',
        'pèrd': 'to lose',
        'oublié': 'to forget',
        'souvnir': 'to remember',
        'pansé': 'to think',
        'réfléchi': 'to reflect',
        'imaziné': 'to imagine',
        'kwar': 'to believe',
        'douté': 'to doubt',
        'éspéré': 'to hope',
        'atann': 'to wait',
        'pasyanté': 'to be patient',
        'vlé': 'to want',
        'déziré': 'to desire',
        'souété': 'to wish',
        'préféré': 'to prefer',
        'aimé': 'to love/like',
        'adoré': 'to adore',
        'détésté': 'to hate',
        'é': 'to hate',
        'kapav': 'to be able to',
        'dwar': 'to have to',
        'falwar': 'to be necessary',
        'sanblé': 'to seem',
        'aparètr': 'to appear',
        'lé': 'to be',
        'gagn': 'to have',
        'fé': 'to do/make',
        'dir': 'to say',
        'war': 'to see',
        'pran': 'to take',
        'donn': 'to give',
        'résouwar': 'to receive',
        'ofrir': 'to offer',
        'achté': 'to buy',
        'vand': 'to sell',
        'payé': 'to pay',
        'kouté': 'to cost',
        'valwar': 'to be worth',
        'pézé': 'to weigh',
        'mezuré': 'to measure',
        'konté': 'to count',
        'kalkilé': 'to calculate',
        'adisyoné': 'to add',
        'soustré': 'to subtract',
        'multiplié': 'to multiply',
        'divizé': 'to divide',
        'éstimé': 'to estimate',
        'zjugé': 'to judge',
        'désidé': 'to decide',
        'chwazi': 'to choose',
        'détérminé': 'to determine',
        'fixé': 'to fix',
        'nomé': 'to name',
        'dézigné': 'to designate',
        'apélé': 'to call',
        'kalifyé': 'to qualify',
        'définir': 'to define',
        'karaktérizé': 'to characterize',
        'dékrir': 'to describe',
        'reprézanté': 'to represent',
        'simbolizé': 'to symbolize',
        'signifyé': 'to signify',
        'andiké': 'to indicate',
        'montré': 'to show',
        'démontré': 'to demonstrate',
        'révéler': 'to reveal',
        'dévwalyé': 'to unveil',
        'ékspozé': 'to expose',
        'prézanté': 'to present',
        'antrouir': 'to introduce',
        'anséré': 'to insert',
        'ankorporé': 'to incorporate',
        'anlégré': 'to integrate',
        'ajouté': 'to add',
        'konplété': 'to complete',
        'séplémanté': 'to supplement',
        'anrichir': 'to enrich',
        'anélyoré': 'to improve',
        'parfèr': 'to perfect',
        'achévér': 'to complete',
        'parachévér': 'to complete thoroughly',
        'finalizé': 'to finalize',
        'términé': 'to finish',
        'konkly': 'to conclude',
        'anteromp': 'to interrupt',
        'sispan': 'to suspend',
        'sésé': 'to cease',
        'arété': 'to stop',
        'stopé': 'to stop',
        'abandoné': 'to abandon',
        'rononsé': 'to renounce',
        'sédé': 'to cede',
        'laché': 'to let go',
        'relaché': 'to release',
        'délivré': 'to deliver',
        'libéré': 'to free',
        'afranchir': 'to enfranchise',
        'émasipé': 'to emancipate',
        'sové': 'to save',
        'sékourir': 'to rescue',
        'édé': 'to help',
        'asisté': 'to assist',
        'souténir': 'to support',
        'manténir': 'to maintain',
        'préservé': 'to preserve',
        'konservé': 'to conserve',
        'gardé': 'to keep',
        'protégé': 'to protect',
        'défand': 'to defend',
        'abrité': 'to shelter',
        'kouvri': 'to cover',
        'anvelopé': 'to wrap',
        'anbalé': 'to pack',
        'anbwaté': 'to fit together',
        'anfermé': 'to lock up',
        'anklor': 'to enclose',
        'anouré': 'to surround',
        'ansèrklé': 'to encircle',
        'séparé': 'to separate',
        'distangé': 'to distinguish',
        'diféransyé': 'to differentiate',
        'komparé': 'to compare',
        'analizé': 'to analyze',
        'égzaminé': 'to examine',
        'anspèkté': 'to inspect',
        'obsèrvé': 'to observe',
        'sirvéyé': 'to monitor',
        'kontrolé': 'to control',
        'vérifyé': 'to verify',
        'tésté': 'to test',
        'ésayé': 'to try',
        'éksérimanté': 'to experiment',
        'prouvé': 'to prove',
        'établir': 'to establish',
        'konfirmé': 'to confirm',
        'sèrtifyé': 'to certify',
        'garantir': 'to guarantee',
        'asiré': 'to assure',
        'épyé': 'to spy on',
        'éspyoné': 'to spy',
        'pèrsoar': 'to perceive',
        'disèrné': 'to discern',
        'anterprété': 'to interpret',
        'tradwir': 'to translate',
        'rakonté': 'to tell',
        'narré': 'to narrate',
        's-éksprimé': 'to express oneself',
        'artikilé': 'to articulate',
        'prononsé': 'to pronounce',
        'éonsé': 'to state',
        'déklaré': 'to declare',
        'anonsé': 'to announce',
        'anformé': 'to inform',
        'prévénir': 'to prevent',
        'avertir': 'to warn',
        'alarté': 'to alert',
        'signalé': 'to signal',
        'dénonsé': 'to denounce',
        'akuzé': 'to accuse',
        'ankilpé': 'to indict',
        'kondanné': 'to condemn',
        'punir': 'to punish',
        'pardoné': 'to forgive',
        'ékuzé': 'to excuse',
        'absoudr': 'to absolve',
        'grasié': 'to grant amnesty',
        'anmistié': 'to amnesty',
        's-rapélé': 'to remember',
        'mémorizé': 'to memorize',
        's-antrené': 'to train oneself',
        'pratiké': 'to practice',
        'égsèrsé': 'to exercise',
        's-égsèrsé': 'to exercise oneself',
        'progréssé': 'to progress',
        'avansé': 'to advance',
        's-dévelopé': 'to develop oneself',
        'évolyé': 'to evolve',
        'transformé': 'to transform',
        'modifyé': 'to modify',
        'altéré': 'to alter',
        'adapté': 'to adapt',
        'azusté': 'to adjust',
        'akrwatr': 'to increase',
        'ogmanté': 'to augment',
        'diminyé': 'to diminish',
        'réduir': 'to reduce',
        'bésé': 'to lower',
        's-miltiplié': 'to multiply oneself',
        's-reprodwir': 'to reproduce oneself',
        'émérzé': 'to emerge',
        'sirvénir': 'to occur',
        's-prodwir': 'to occur',
        'disparètr': 'to disappear',
        's-évanwir': 'to faint',
        'désédé': 'to pass away',
        'trépasé': 'to pass away',
        'résisité': 'to resurrect',
        'rénèss': 'to be reborn',
        'réaparètr': 'to reappear',
        'réémérzé': 'to re-emerge',
        'égzisté': 'to exist',
        'sizisté': 'to subsist',
        'sirviv': 'to survive',
        'diré': 'to last',
        'persisté': 'to persist',
        'kontinyé': 'to continue',
        's-manténir': 'to maintain oneself',
        'aparténir': 'to belong',
        'dépan': 'to depend',
        'rpozé sur': 'to rest on',
        'konserné': 'to concern',
        'anpliké': 'to apply',
        'afekté': 'to affect',
        'touché': 'to affect',
        'anflansé': 'to influence',
        'provoqué': 'to provoke',
        'kozé': 'to cause',
        'antrénné': 'to train/to cause',
        'déklanché': 'to trigger',
        'prodwir': 'to produce',
        'zénéré': 'to generate',
        'anzandré': 'to beget',
        'prokréé': 'to procreate',
        'fabriké': 'to manufacture',
        'manifaktiré': 'to manufacture',
        'konféksyoné': 'to make',
        'élabaré': 'to elaborate',
        'kompozé': 'to compose',
        'konstitwé': 'to constitute',
        'formé': 'to form',
        'batir': 'to build',
        'érizé': 'to erect',
        'édifyé': 'to edify',
        'anstalé': 'to install',
        'dépozé': 'to arrange',
        'plasé': 'to place',
        'pozisyoné': 'to position',
        'situé': 'to situate',
        'lokalizé': 'to locate',
        'organizé': 'to organize',
        'amanazé': 'to arrange',
        'aranjé': 'to arrange',
        'préparé': 'to prepare',
        'ranzé': 'to tidy up',
        'klasé': 'to classify',
        'ordonné': 'to order',
        'triyé': 'to sort',
        'sélèksyoné': 'to select',
        'opté': 'to opt',
        'ézigé': 'to demand',
        'mandé': 'to ask',
        'priyé': 'to pray',
        'souplié': 'to beg',
        'anploré': 'to implore',
        'nésésité': 'to necessitate',
        'ansisté': 'to insist',
        'poursivir': 'to pursue',
        'atén': 'to reach',
        'obténir': 'to obtain',
        'gagné': 'to win/to earn',
        'ranporté': 'to bring back',
        'triomfé': 'to triumph',
        'réyisi': 'to succeed',
        'échwé': 'to fail',
        'manké': 'to miss',
        'raté': 'to miss',
        'loupé': 'to miss',
        'ézité': 'to hesitate',
        'krén': 'to fear',
        'rédouté': 'to dread',
        'apréandé': 'to apprehend',
        'ozé': 'to dare',
        'avoué': 'to admit',
        'konfésé': 'to confess',
        'rekonèt': 'to recognize',
        'admetr': 'to admit',
        'nié': 'to deny',
        'déméntir': 'to contradict',
        'kontradir': 'to contradict',
        'réfuté': 'to refute',
        'argimanté': 'to argue',
        'diskuté': 'to discuss',
        'débatt': 'to debate',
        'négosyé': 'to negotiate',
        'dialogé': 'to dialogue',
        'komyniké': 'to communicate',
        'transmèt': 'to transmit',
        'anvoyé': 'to send',
        'éspédyé': 'to expedite',
        'posté': 'to post',
        'livré': 'to deliver',
        'distribyé': 'to distribute',
        'rasanblé': 'to gather',
        'réynir': 'to reunite',
        'goupé': 'to group',
        'asosyé': 'to associate',
        'lyé': 'to link',
        'konèkté': 'to connect',
        'branché': 'to plug in',
        'rlyé': 'to connect',
        'zwan': 'to join',
        'ynir': 'to unite',
        'gardé': 'to look at/to keep',
        'ékouté': 'to listen',
        'tand': 'to hear',
        'sésir': 'to grasp',
        'kozé': 'to speak',
        'tomber': 'to fall',
        'pousé': 'to push',
        'krwatr': 'to grow',
        'diri': 'rice',
        'may': 'corn',
        'pwa': 'beans',
        'légim': 'vegetables',
        'fri': 'fries',
        'viann': 'meat',
        'poul': 'chicken',
        'pwason': 'fish',
        'kri': 'shrimp',
        'bannann': 'banana',
        'mang': 'mango',
        'zorey': 'pineapple',
        'pam': 'bread',
        'lapen': 'rabbit',
        'kabri': 'goat',
        'zef': 'egg',
        'lèt': 'milk',
        'dilo': 'water',
        'sik': 'sugar',
        'sèl': 'salt',
        'pimant': 'pepper',
        'bwa': 'wood/tree',
        'fwi': 'fruit',
        'legim': 'vegetable',
        'kari': 'curry',
        'rougay': 'spicy sauce',
        'briyad': 'fried rice',
        'samoussa': 'samosa',
        'bouchon': 'dumpling',
        'massalé': 'meat curry',
        'carry': 'curry',
        'kaldu': 'broth',
        'soup': 'soup',
        'salad': 'salad',
        'desè': 'dessert',
        'gato': 'cake',
        'sòflé': 'soufflé',
        'krèm': 'cream',
        'glasy': 'ice cream',
        'chokola': 'chocolate',
        'bonbon': 'candy',
        'biskwit': 'biscuit',
        'kafé': 'coffee',
        'té': 'tea',
        'sok': 'juice',
        'limonad': 'lemonade',
        'biér': 'beer',
        'vin': 'wine',
        'rhom': 'rum',
        'koko': 'coconut',
        'vanil': 'vanilla',
        'kanel': 'cinnamon',
        'klouvis': 'clove',
        'mitch': 'ginger',
        'kari': 'curry leaf',
        'zamann': 'tamarind',
        'karambol': 'starfruit',
        'litchi': 'lychee',
        'longan': 'longan',
        'friz': 'pea',
        'zolive': 'olive',
        'fromaz': 'cheese',
        'bèr': 'butter',
        'lék': 'oil',
        'vinaigr': 'vinegar',
        'sos': 'sauce',
        'mayonéz': 'mayonnaise',
        'moutad': 'mustard',
        'kéchap': 'ketchup',
        'kétchap': 'ketchup',
        'konfitir': 'jam',
        'miel': 'honey',
        'patis': 'pastry',
        'krouasan': 'croissant',
        'panin': 'sandwich',
        'pizza': 'pizza',
        'pasta': 'pasta',
        'riz': 'rice',
        'nwid': 'noodles',
        'choucrout': 'sauerkraut',
        'toufu': 'tofu',
        'soja': 'soy',
        'zaboka': 'avocado',
        'tomat': 'tomato',
        'zonyon': 'onion',
        'lalo': 'spinach',
        'chocho': 'chayote',
        'brèd': 'broad beans',
        'pwa koulé': 'lentils',
        'sousouma': 'watercress',
        'was': 'pumpkin',
        'kourz': 'courgette',
        'konkonb': 'cucumber',
        'chou': 'cabbage',
        'karòt': 'carrot',
        'navet': 'turnip',
        'pòtiron': 'pumpkin',
        'patat': 'sweet potato',
        'piman': 'pepper',
        'piman do': 'chili pepper',
        'lay': 'garlic',
        'persil': 'parsley',
        'koriandr': 'coriander',
        'bwan': 'thyme',
        'romarin': 'rosemary',
        'lauri': 'bay leaf',
        'basilik': 'basil',
        'sari': 'curry',
        'masala': 'masala',
        'tandoori': 'tandoori',
        'tikka': 'tikka',
        'naan': 'naan bread',
        'roti': 'roti',
        'dosa': 'dosa',
        'idli': 'idli',
        'samosa': 'samosa',
        'pakora': 'pakora',
        'vada': 'vada',
        'idli': 'idli',
        'chatni': 'chutney',
        'achar': 'pickle',
        'salad': 'salad',
        'caviar': 'caviar',
        'foi gras': 'foie gras',
        'truf': 'truffle',
        'kaviar': 'caviar',
        'omlèt': 'omelette',
        'krèp': 'pancake',
        'vafèl': 'waffle',
        'gofr': 'waffle',
        'beignet': 'doughnut',
        'kroasan': 'croissant',
        'pain': 'bread',
        'bagèt': 'baguette',
        'sandwich': 'sandwich',
        'hamburger': 'hamburger',
        'hotdog': 'hot dog',
        'pizza': 'pizza',
        'tako': 'taco',
        'burito': 'burrito',
        'kebab': 'kebab',
        'falafel': 'falafel',
        'sushi': 'sushi',
        'sashimi': 'sashimi',
        'ramen': 'ramen',
        'tempura': 'tempura',
        'yakitori': 'yakitori',
        'satay': 'satay',
        'spring roll': 'spring roll',
        'dim sum': 'dim sum',
        'dumpling': 'dumpling',
        'noodle': 'noodle',
        'poulet': 'chicken',
        'canard': 'duck',
        'dinde': 'turkey',
        'agneau': 'lamb',
        'mouton': 'sheep',
        'veau': 'veal',
        'porc': 'pork',
        'bœuf': 'beef',
        'jambon': 'ham',
        'saucisse': 'sausage',
        'bacon': 'bacon',
        'côtelette': 'chop',
        'steak': 'steak',
        'côte de bœuf': 'rib steak',
        'entrecôte': 'entrecote',
        'filet': 'fillet',
        'rôti': 'roast',
        'bouilli': 'boiled',
        'frit': 'fried',
        'grillé': 'grilled',
        'cuit': 'cooked',
        'cru': 'raw',
        'mûr': 'ripe',
        'pas mûr': 'unripe',
        'frais': 'fresh',
        'congelé': 'frozen',
        'en conserve': 'canned',
        'séché': 'dried',
        'salé': 'salty',
        'sucré': 'sweet',
        'acide': 'sour',
        'amer': 'bitter',
        'épicé': 'spicy',
        'fade': 'bland',
        'délicieux': 'delicious',
        'savoureux': 'tasty',
        'fade': 'tasteless',
        'mauvais': 'bad',
        'pourri': 'rotten',
        'cuit': 'cooked',
        'brûlé': 'burnt',
        'croquant': 'crunchy',
        'mou': 'soft',
        'dur': 'hard',
        'chaud': 'hot',
        'froid': 'cold',
        'tiède': 'warm',
        'glacé': 'iced',
        'bouillant': 'boiling',
        'petit-déjeuner': 'breakfast',
        'déjeuner': 'lunch',
        'dîner': 'dinner',
        'collation': 'snack',
        'goûter': 'snack',
        'apéritif': 'appetizer',
        'digestif': 'digestif',
        'recette': 'recipe',
        'cuisine': 'cuisine',
        'cuisinier': 'cook (male)',
        'cuisinière': 'cook (female)',
        'chef': 'chef',
        'restaurant': 'restaurant',
        'café': 'cafe',
        'bistro': 'bistro',
        'brasserie': 'brasserie',
        'fast food': 'fast food',
        'livraison': 'delivery',
        'emporter': 'takeaway',
        'service': 'service',
        'menu': 'menu',
        'carte': 'menu',
        'plat du jour': 'dish of the day',
        'spécialité': 'specialty',
        'formule': 'set menu',
        'buffet': 'buffet',
        'self-service': 'self-service',
        'boisson': 'drink',
        'alcool': 'alcohol',
        'boisson alcoolisée': 'alcoholic beverage',
        'boisson non alcoolisée': 'non-alcoholic beverage',
        'cocktail': 'cocktail',
        'apéritif': 'aperitif',
        'digestif': 'digestif',
        'vin rouge': 'red wine',
        'vin blanc': 'white wine',
        'vin rosé': 'rose wine',
        'champagne': 'champagne',
        'bière': 'beer',
        'cider': 'cider',
        'whisky': 'whisky',
        'vodka': 'vodka',
        'gin': 'gin',
        'rhum': 'rum',
        'liqueur': 'liqueur',
        'jus': 'juice',
        'nectar': 'nectar',
        'nectar de fruits': 'fruit nectar',
        'smoothie': 'smoothie',
        'milkshake': 'milkshake',
        'soda': 'soda',
        'eau minérale': 'mineral water',
        'eau gazeuse': 'sparkling water',
        'eau plate': 'still water',
        'thé': 'tea',
        'thé glacé': 'iced tea',
        'infusion': 'herbal tea',
        'café': 'coffee',
        'café au lait': 'coffee with milk',
        'expresso': 'espresso',
        'cappuccino': 'cappuccino',
        'latte': 'latte',
        'chocolat chaud': 'hot chocolate',
        'sirop': 'syrup',
        'boisson énergisante': 'energy drink',
        'boisson sportive': 'sports drink',
        'cannette': 'can',
        'bouteille': 'bottle',
        'verre': 'glass',
        'tasse': 'cup',
        'mug': 'mug',
        'pichet': 'pitcher',
        'carafe': 'carafe',
        'bol': 'bowl',
        'assiette': 'plate',
        'couvert': 'cutlery',
        'fourchette': 'fork',
        'couteau': 'knife',
        'cuillère': 'spoon',
        'cuillère à soupe': 'tablespoon',
        'cuillère à café': 'teaspoon',
        'verre': 'glass',
        'tasse': 'cup',
        'bol': 'bowl',
        'assiette': 'plate',
        'plat': 'dish',
        'poêle': 'pan',
        'casserole': 'casserole',
        'faitout': 'stockpot',
        'marmite': 'pot',
        'passoire': 'colander',
        'passoire': 'strainer',
        'fouet': 'whisk',
        'rouleau à pâtisserie': 'rolling pin',
        'planche à découper': 'cutting board',
        'balance': 'scale',
        'mesure': 'measure',
        'four': 'oven',
        'micro-ondes': 'microwave',
        'plaque de cuisson': 'stove',
        'grill': 'grill',
        'frigo': 'fridge',
        'congélateur': 'freezer',
        'lave-vaisselle': 'dishwasher',
        'évier': 'sink',
        'robinet': 'tap',
        'table': 'table',
        'chaise': 'chair',
        'tabouret': 'stool',
        'nappe': 'tablecloth',
        'serviette': 'napkin',
        'napperon': 'placemat',
        'dessert': 'dessert',
        'fruit': 'fruit',
        'légume': 'vegetable',
        'viande': 'meat',
        'poisson': 'fish',
        'fruits de mer': 'seafood',
        'volaille': 'poultry',
        'charcuterie': 'deli meat',
        'fromage': 'cheese',
        'pain': 'bread',
        'viennoiserie': 'pastry',
        'pâtisserie': 'pastry',
        'confiserie': 'confectionery',
        'épicerie': 'grocery',
        'marché': 'market',
        'supermarché': 'supermarket',
        'hypermarché': 'hypermarket',
        'épicerie fine': 'delicatessen',
        'boulangerie': 'bakery',
        'pâtisserie': 'pastry shop',
        'boucher': 'butcher',
        'poissonnier': 'fishmonger',
        'crémier': 'dairy',
        'marchand de vin': 'wine merchant',
        'primeur': 'greengrocer',
        'cuisinier': 'cook',
        'chef': 'chef',
        'pâtissier': 'pastry chef',
        'boulanger': 'baker',
        'serveur': 'waiter',
        'serveuse': 'waitress',
        'sommelier': 'sommelier',
        'barman': 'bartender',
        'barmaid': 'barmaid',
        'plongeur': 'dishwasher',
        'restaurateur': 'restaurateur',
        'cuisinier': 'cook',
        'chef de cuisine': 'head chef',
        'sous-chef': 'sous-chef',
        'commis de cuisine': 'kitchen assistant',
        'pâtissier': 'pastry chef',
        'boulanger': 'baker',
        'chocolatier': 'chocolatier',
        'glacier': 'ice cream maker',
        'traiteur': 'caterer',
        'livreur': 'delivery person',
        'client': 'customer',
        'habitué': 'regular customer',
        'critique gastronomique': 'food critic',
        'guide gastronomique': 'restaurant guide',
        'étoile Michelin': 'Michelin star',
        'repas': 'meal',
        'festin': 'feast',
        'banquet': 'banquet',
        'buffet': 'buffet',
        'casse-croûte': 'snack',
        'en-cas': 'snack',
        'picnic': 'picnic',
        'barbecue': 'barbecue',
        'grillade': 'grill',
        'cuisine': 'cuisine',
        'recette': 'recipe',
        'ingrédient': 'ingredient',
        'préparation': 'preparation',
        'cuisson': 'cooking',
        'assaisonnement': 'seasoning',
        'épice': 'spice',
        'herbe aromatique': 'herb',
        'condiment': 'condiment',
        'sauce': 'sauce',
        'vinaigrette': 'vinaigrette',
        'marinade': 'marinade',
        'fumage': 'smoking',
        'saumure': 'brine',
        'conservation': 'preservation',
        'stérilisation': 'sterilization',
        'pasteurisation': 'pasteurization',
        'congélation': 'freezing',
        'lyophilisation': 'freeze-drying',
        'déshydratation': 'dehydration',
        'mise en conserve': 'canning',
        'saumure': 'brine',
        'saumurage': 'brining',
        'salaison': 'salting',
        'séchage': 'drying',
        'fumage': 'smoking',
        'macération': 'maceration',
        'fermentation': 'fermentation',
        'levure': 'yeast',
        'levain': 'sourdough',
        'pâte': 'dough',
        'pâte levée': 'leavened dough',
        'pâte feuilletée': 'puff pastry',
        'pâte brisée': 'shortcrust pastry',
        'pâte sablée': 'sweet shortcrust pastry',
        'pâte à choux': 'choux pastry',
        'pâte à pizza': 'pizza dough',
        'pâte à pain': 'bread dough',
        'pâte à tarte': 'pie dough',
        'pâte à crêpes': 'crêpe batter',
        'pâte à gaufres': 'waffle batter',
        'pâte à beignets': 'doughnut batter',
        'pâte à biscuits': 'cookie dough',
        'pâte à gâteau': 'cake batter',
        'génoise': 'sponge cake',
        'biscuit': 'biscuit',
        'biscuit sec': 'dry biscuit',
        'biscuit moelleux': 'soft biscuit',
        'biscuit au beurre': 'butter biscuit',
        'biscuit au chocolat': 'chocolate biscuit',
        'biscuit à la confiture': 'jam biscuit',
        'biscuit à la vanille': 'vanilla biscuit',
        'biscuit à la cannelle': 'cinnamon biscuit',
        'biscuit au gingembre': 'ginger biscuit',
        'biscuit au citron': 'lemon biscuit',
        'biscuit à l\'orange': 'orange biscuit',
        'biscuit à la fraise': 'strawberry biscuit',
        'biscuit à la framboise': 'raspberry biscuit',
        'biscuit à la myrtille': 'blueberry biscuit',
        'biscuit à la pomme': 'apple biscuit',
        'biscuit à la poire': 'pear biscuit',
        'biscuit à la pêche': 'peach biscuit',
        'biscuit à l\'abricot': 'apricot biscuit',
        'biscuit à la cerise': 'cherry biscuit',
        'biscuit à la prune': 'plum biscuit',
        'biscuit à la figue': 'fig biscuit',
        'biscuit à la noix': 'nut biscuit',
        'biscuit à la noisette': 'hazelnut biscuit',
        'biscuit à l\'amande': 'almond biscuit',
        'biscuit à la cacahuète': 'peanut biscuit',
        'biscuit à la pistache': 'pistachio biscuit',
        'biscuit à la noix de coco': 'coconut biscuit',
        'biscuit au chocolat blanc': 'white chocolate biscuit',
        'biscuit au chocolat au lait': 'milk chocolate biscuit',
        'biscuit au chocolat noir': 'dark chocolate biscuit',
        'biscuit au caramel': 'caramel biscuit',
        'biscuit au miel': 'honey biscuit',
        'biscuit à la mélasse': 'molasses biscuit',
        'biscuit à la réglisse': 'licorice biscuit',
        'biscuit à la menthe': 'mint biscuit',
        'biscuit à la rose': 'rose biscuit',
        'biscuit au thé': 'tea biscuit',
        'biscuit au café': 'coffee biscuit',
        'biscuit au rhum': 'rum biscuit',
        'biscuit au kirsch': 'kirsch biscuit',
        'biscuit au cognac': 'cognac biscuit',
        'biscuit à l\'armagnac': 'armagnac biscuit',
        'biscuit au calvados': 'calvados biscuit',
        'biscuit au whisky': 'whisky biscuit',
        'biscuit au gin': 'gin biscuit',
        'biscuit à la vodka': 'vodka biscuit',
        'biscuit au champagne': 'champagne biscuit',
        'biscuit au vin rouge': 'red wine biscuit',
        'biscuit au vin blanc': 'white wine biscuit',
        'biscuit au vin rosé': 'rosé wine biscuit',
        'biscuit à la bière': 'beer biscuit',
        'biscuit au cidre': 'cider biscuit',
        'biscuit au jus de pomme': 'apple juice biscuit',
        'biscuit au jus d\'orange': 'orange juice biscuit',
        'biscuit au jus de citron': 'lemon juice biscuit',
        'biscuit au jus de pamplemousse': 'grapefruit juice biscuit',
        'biscuit au jus de tomate': 'tomato juice biscuit',
        'biscuit au jus de carotte': 'carrot juice biscuit',
        'biscuit au jus de betterave': 'beetroot juice biscuit',
        'biscuit au jus de céleri': 'celery juice biscuit',
        'biscuit au jus de concombre': 'cucumber juice biscuit',
        'biscuit au jus de poivron': 'pepper juice biscuit',
        'biscuit au jus d\'oignon': 'onion juice biscuit',
        'biscuit au jus d\'ail': 'garlic juice biscuit',
        'biscuit au jus de gingembre': 'ginger juice biscuit',
        'biscuit au jus de curcuma': 'turmeric juice biscuit',
        'biscuit au jus de paprika': 'paprika juice biscuit',
        'biscuit au jus de piment': 'chili juice biscuit',
        'biscuit au jus de vanille': 'vanilla juice biscuit',
        'biscuit au jus de cannelle': 'cinnamon juice biscuit',
        'biscuit au jus de muscade': 'nutmeg juice biscuit',
        'biscuit au jus de clou de girofle': 'clove juice biscuit',
        'biscuit au jus de cardamome': 'cardamom juice biscuit',
        'biscuit au jus d\'anis': 'anise juice biscuit',
        'biscuit au jus de fenouil': 'fennel juice biscuit',
        'biscuit au jus de coriandre': 'coriander juice biscuit',
        'biscuit au jus de persil': 'parsley juice biscuit',
        'biscuit au jus de cerfeuil': 'chervil juice biscuit',
        'biscuit au jus de ciboulette': 'chives juice biscuit',
        'biscuit au jus de menthe': 'mint juice biscuit',
        'biscuit au jus de basilic': 'basil juice biscuit',
        'biscuit au jus de thym': 'thyme juice biscuit',
        'biscuit au jus de romarin': 'rosemary juice biscuit',
        'biscuit au jus de laurier': 'bay leaf juice biscuit',
        'biscuit au jus de sauge': 'sage juice biscuit',
        'biscuit au jus de marjolaine': 'marjoram juice biscuit',
        'biscuit au jus d\'origan': 'oregano juice biscuit',
        'biscuit au jus de sarriette': 'savory juice biscuit',
        'biscuit au jus de livèche': 'lovage juice biscuit',
        'biscuit au jus d\'angélique': 'angelica juice biscuit',
        'biscuit au jus de mélisse': 'lemon balm juice biscuit',
        'biscuit au jus de verveine': 'verbena juice biscuit',
        'biscuit au jus de camomille': 'chamomile juice biscuit',
        'biscuit au jus de tilleul': 'linden juice biscuit',
        'biscuit au jus de hibiscus': 'hibiscus juice biscuit',
        'biscuit au jus de rose': 'rose juice biscuit',
        'biscuit au jus de jasmin': 'jasmine juice biscuit',
        'biscuit au jus de violette': 'violet juice biscuit',
        'biscuit au jus de lavande': 'lavender juice biscuit',
        'biscuit au jus de géranium': 'geranium juice biscuit',
        'biscuit au jus de muguet': 'lily of the valley juice biscuit',
        'biscuit au jus de réséda': 'mignonette juice biscuit',
        'biscuit au jus de myrte': 'myrtle juice biscuit',
        'biscuit au jus de laurier-rose': 'oleander juice biscuit',
        'biscuit au jus de gardénia': 'gardenia juice biscuit',
        'biscuit au jus de magnolia': 'magnolia juice biscuit',
        'biscuit au jus de camélia': 'camellia juice biscuit',
        'biscuit au jus d\'azalée': 'azalea juice biscuit',
        'biscuit au jus de rhododendron': 'rhododendron juice biscuit',
        'biscuit au jus d\'hortensia': 'hydrangea juice biscuit',
        'biscuit au jus de pivoine': 'peony juice biscuit',
        'biscuit au jus de dahlia': 'dahlia juice biscuit',
        'biscuit au jus de glaïeul': 'gladiolus juice biscuit',
        'biscuit au jus de lys': 'lily juice biscuit',
        'bwa': 'tree/wood',
        'zanimal': 'animal',
        'lozazor': 'bird',
        'flèr': 'flower',
        'larivaz': 'river',
        'lamer': 'sea',
        'monlan': 'mountain',
        'lapli': 'rain',
        'lonoraz': 'thunder',
        'larkansyel': 'rainbow',
        'van': 'wind',
        'zon': 'sun',
        'lalinn': 'moon',
        'zetwal': 'star',
        'nwar': 'black',
        'blan': 'white',
        'rouz': 'red',
        'zho': 'yellow',
        'ble': 'blue',
        'vert': 'green',
        'lor': 'gold',
        'arzan': 'silver/money',
        'lakaz': 'house',
        'zardin': 'garden',
        'labou': 'mud',
        'lérz': 'rock',
        'sabl': 'sand',
        'fôrè': 'forest',
        'plenn': 'plain',
        'kaskad': 'waterfall',
        'volkan': 'volcano',
        'lezil': 'island',
        'lakot': 'coast',
        'baryé': 'reef',
        'koral': 'coral',
        'krik': 'creek',
        'zanimo': 'animal',
        'chenn': 'dog',
        'chat': 'cat',
        'souris': 'mouse',
        'lezan': 'insects',
        'papillon': 'butterfly',
        'aragn': 'spider',
        'serpan': 'snake',
        'lezard': 'lizard',
        'krapod': 'toad',
        'grenouill': 'frog',
        'sikal': 'cicada',
        'moustik': 'mosquito',
        'lèz': 'lizard',
        'koko': 'rooster',
        'poule': 'hen',
        'kan': 'dog',
        'chval': 'horse',
        'zébr': 'zebra',
        'lion': 'lion',
        'tigr': 'tiger',
        'léléfan': 'elephant',
        'siraf': 'giraffe',
        'singe': 'monkey',
        'bik': 'ox',
        'vach': 'cow',
        'mouton': 'sheep',
        'chèvr': 'goat',
        'kochon': 'pig',
        'lapen': 'rabbit',
        'cerf': 'deer',
        'bich': 'doe',
        'loup': 'wolf',
        'renar': 'fox',
        'our': 'bear',
        'laman': 'shark',
        'balen': 'whale',
        'dofen': 'dolphin',
        'tortu': 'turtle',
        'krab': 'crab',
        'langoust': 'rock lobster',
        'ourit': 'octopus',
        'kalmar': 'squid',
        'korn': 'horn',
        'pied': 'foot',
        'zil': 'eye',
        'bouch': 'mouth',
        'nez': 'nose',
        'loréy': 'ear',
        'chev': 'hair',
        'lapo': 'skin',
        'zan': 'tooth',
        'lépang': 'tongue',
        'lé': 'blood',
        'kè': 'heart',
        'poumon': 'lung',
        'léstri': 'stomach',
        'sé': 'intestines',
        'bwa': 'bone',
        'klé': 'key',
        'pòrt': 'door',
        'fénètr': 'window',
        'toit': 'roof',
        'mur': 'wall',
        'solyé': 'floor',
        'lakou': 'yard',
        'rout': 'road',
        'chinmin': 'path',
        'pon': 'bridge',
        'lékòl': 'school',
        'lopital': 'hospital',
        'lamari': 'town hall',
        'légliz': 'church',
        'lapost': 'post office',
        'labank': 'bank',
        'magasin': 'shop/store',
        'marché': 'market',
        'restoran': 'restaurant',
        'otèl': 'hotel',
        'kinnema': 'cinema',
        'mizé': 'museum',
        'bibliyotèk': 'library',
        'park': 'park',
        'plas': 'square',
        'stad': 'stadium',
        'pist': 'airport',
        'gaz': 'gas station',
        'arèt-bis': 'bus stop',
        'taxi': 'taxi',
        'bus': 'bus',
        'minibus': 'minibus',
        'voitur': 'car',
        'moto': 'motorcycle',
        'bisiklèt': 'bicycle',
        'bato': 'boat',
        'navir': 'ship',
        'avion': 'airplane',
        'élykoptèr': 'helicopter',
        'tyren': 'train',
        'tram': 'tramway',
        'métro': 'subway',
        'lindi': 'Monday',
        'mardi': 'Tuesday',
        'merkredi': 'Wednesday',
        'zedi': 'Thursday',
        'vandredi': 'Friday',
        'samdi': 'Saturday',
        'dimans': 'Sunday',
        'zanvi': 'January',
        'fevriye': 'February',
        'mars': 'March',
        'avril': 'April',
        'me': 'May',
        'zin': 'June',
        'zilye': 'July',
        'out': 'August',
        'septam': 'September',
        'oktob': 'October',
        'novam': 'November',
        'desam': 'December',
        'lézanné': 'the year',
        'lmwa': 'the month',
        'lasémenn': 'the week',
        'lzour': 'the day',
        'lanuit': 'the night',
        'lèr': 'time',
        'momant': 'moment',
        'matin': 'morning',
        'laprémidi': 'afternoon',
        'swar': 'evening',
        'midi': 'noon',
        'minwi': 'midnight',
        'bofor': 'before',
        'aprésa': 'after',
        'koman': 'when/how',
        'kan': 'when',
        'alèr': 'then',
        'anmwin': 'meanwhile',
        'aktièlman': 'currently',
        'souvan': 'often',
        'parfoi': 'sometimes',
        'rar': 'rarely',
        'touzour': 'always',
        'zamè': 'never',
        'jòdla': 'today',
        'yèr': 'yesterday',
        'demin': 'tomorrow',
        'aprdemin': 'the day after tomorrow',
        'avanyèr': 'the day before yesterday',
        'lasézon': 'the season',
        'livé': 'summer',
        'livèr': 'winter',
        'loton': 'autumn',
        'laprintan': 'spring',
        'fè': 'hot',
        'frèt': 'cold',
        'bon': 'good',
        'mové': 'bad',
        'bwa': 'windy',
        'plenouaz': 'cloudy',
        'soléy': 'sunny',
        'lapli': 'rainy',
        'loraz': 'thunderstorm',
        'tèrfom': 'earthquake',
        'siklon': 'cyclone/hurricane',
        'razdemaré': 'tidal wave/tsunami',
        'innondasyon': 'flood',
        'sècherès': 'drought',
        'oraz': 'storm',
        'briz': 'breeze',
        'brouyar': 'fog',
        'nwaz': 'mist',
        'ròzéman': 'dew',
        'glasyé': 'ice',
        'lanèz': 'snow',
        'grèl': 'hail',
        'arkansyel': 'rainbow',
        'léklèr': 'lightning',
        'lonoraz': 'thunder',
        'van': 'wind',
        'lapli': 'rain',
        'zon': 'sun',
        'lalinn': 'moon',
        'zetwal': 'star',
        'linivèr': 'universe',
        'galaksi': 'galaxy',
        'sistém solèr': 'solar system',
        'latèr': 'earth',
        'planèt': 'planet',
        'satelit': 'satellite',
        'komèt': 'comet',
        'astéroyid': 'asteroid',
        'météorit': 'meteorite',
        'trou nwèr': 'black hole',
        'nébilèz': 'nebula',
        'kosmos': 'cosmos',
        'éspas': 'space',
        'anfini': 'infinity',
        'éternité': 'eternity',
        'zéro': 'zero',
        'inn': 'one',
        'dè': 'two',
        'trwa': 'three',
        'kat': 'four',
        'senk': 'five',
        'sis': 'six',
        'sèt': 'seven',
        'wit': 'eight',
        'nèf': 'nine',
        'dis': 'ten',
        'on': 'eleven',
        'douz': 'twelve',
        'trèz': 'thirteen',
        'katòz': 'fourteen',
        'kenz': 'fifteen',
        'sèz': 'sixteen',
        'dizèt': 'seventeen',
        'dizwit': 'eighteen',
        'diznèf': 'nineteen',
        'ven': 'twenty',
        'vent-inn': 'twenty-one',
        'trant': 'thirty',
        'karant': 'forty',
        'senkant': 'fifty',
        'souasant': 'sixty',
        'karant-ven': 'eighty',
        'katsan': 'one hundred',
        'dé-katsan': 'two hundred',
        'mil': 'one thousand',
        'dé-mil': 'two thousand',
        'on milyon': 'one million',
        'premyé': 'first',
        'dèzyèm': 'second',
        'trwazyèm': 'third',
        'katriyèm': 'fourth',
        'senkyèm': 'fifth',
        'sizyèm': 'sixth',
        'sètyèm': 'seventh',
        'uityèm': 'eighth',
        'nevyèm': 'ninth',
        'dizyèm': 'tenth',
        'dèrnyé': 'last',
        'pakè': 'a few',
        'ben': 'many',
        'anpil': 'a lot',
        'tros': 'too much',
        'pwi': 'a little',
        'loin': 'far',
        'près': 'near',
        'i': 'here',
        'la': 'there',
        'partout': 'everywhere',
        'nyèrpartout': 'nowhere',
        'koté': 'side',
        'anlé': 'above',
        'anba': 'below',
        'andan': 'inside',
        'andé': 'outside',
        'devan': 'in front of',
        'dèryèr': 'behind',
        'antre': 'between',
        'parmi': 'among',
        'kont': 'against',
        'sou': 'under',
        'sur': 'on',
        'dans': 'in',
        'ak': 'with',
        'san': 'without',
        'pour': 'for',
        'par': 'by',
        'a': 'at/to',
        'de': 'of/from',
        'dépi': 'since',
        'juska': 'until',
        'avan': 'before',
        'aprè': 'after',
        'ki': 'who/which',
        'kosa': 'what',
        'ki koté': 'where',
        'kan': 'when',
        'koman': 'how',
        'poukwa': 'why',
        'kanmwin': 'how much/many',
        'ki lè': 'what time',
        'ki nonm': 'which man',
        'ki la': 'whose',
        'ki bann': 'which ones',
        'kossa': 'what (informal)',
        'kofé': 'why (informal)',
        'komentsa': 'how come (informal)',
        'ki pé': 'who can',
        'ki vlé': 'who wants',
        'ki sa': 'what is that',
        'sa ki': 'who is that',
        'ki dir': 'what did you say',
        'ki bann la': 'what are those',
        'é': 'and',
        'mé': 'but',
        'ou': 'or',
        'si': 'if',
        'parék': 'because',
        'alors': 'so',
        'donk': 'therefore',
        'kar': 'because',
        'konsékan': 'consequently',
        'mémsi': 'even if',
        'tandisk': 'while',
        'pandan': 'during',
        'fin': 'so that',
        'afin': 'in order to',
        'osinon': 'otherwise',
        'nein': 'neither',
        'so': 'either',
        'so... so...': 'either... or...',
        'ni... ni...': 'neither... nor...',
        'pa selman... mé osi': 'not only... but also',
        'konm': 'like/as',
        'pari': 'compared to',
        'akonpan': 'accompanied by',
        'gras a': 'thanks to',
        'malgré': 'despite',
        'sanz': 'without',
        'lo': 'far from',
        'prè': 'close to',
        'vizav': 'opposite',
        'a koté': 'next to',
        'anviron': 'around',
        'otr': 'other than',
        'sak': 'except for',
        'pandan': 'during',
        'avan': 'before',
        'aprè': 'after',
        'just aprè': 'right after',
        'just avan': 'right before',
        'dipi': 'since',
        'jiska': 'until',
        'a partir de': 'starting from',
        'a': 'at/to',
        'de': 'of/from',
        'a la': 'to the',
        'au': 'to the (masc)',
        'dans': 'in',
        'sur': 'on',
        'sou': 'under',
        'anba': 'below',
        'anlé': 'above',
        'par': 'by',
        'pour': 'for',
        'avec': 'with',
        'sans': 'without',
        'chez': 'at someone\'s place',
        'entre': 'between',
        'parmi': 'among',
        'contre': 'against',
        'vers': 'towards',
        'selon': 'according to',
        'hors': 'outside of',
        'dedan': 'inside',
        'dehors': 'outside',
        'partout': 'everywhere',
        'quelque part': 'somewhere',
        'nulle part': 'nowhere',
        'ici': 'here',
        'là': 'there',
        'là-bas': 'over there',
        'd ici': 'from here',
        'de là': 'from there',
        'jusqu ici': 'until here',
        'jusqu  là': 'until there',
        'depuis': 'since',
        'depuis quand': 'since when',
        'depuis longtemps': 'for a long time',
        'depuis peu': 'recently',
        'pendant que': 'while',
        'avant que': 'before',
        'après que': 'after',
        'aussitôt que': 'as soon as',
        'chaque fois que': 'every time that',
        'la première fois que': 'the first time that',
        'la dernière fois que': 'the last time that',
        'toutes les fois que': 'every time that',
        'bien que': 'although',
        'quoique': 'although',
        'même si': 'even if',
        'comme si': 'as if',
        'si... que': 'so... that',
        'tellement... que': 'so... that',
        'trop... pour': 'too... to',
        'assez... pour': 'enough... to',
        'prêt à': 'ready to',
        'en train de': 'in the process of',
        'sur le point de': 'about to',
        'obliger de': 'obliged to',
        'forcer de': 'forced to',
        'habitué à': 'used to',
        'sensé': 'supposed to',
        'capab de': 'capable of',
        'en mesure de': 'able to',
        'dans l\'impossibilité de': 'unable to',
        'faute de': 'for lack of',
        'à cause de': 'because of',
        'en raison de': 'due to',
        'grâce à': 'thanks to',
        'en dépit de': 'despite',
        'au lieu de': 'instead of',
        'à force de': 'by dint of',
        'faute de': 'for lack of',
        'par manque de': 'for lack of',
        'par excès de': 'by excess of',
        'au risque de': 'at the risk of',
        'dans le but de': 'with the aim of',
        'dans l\'espoir de': 'in the hope of',
        'en vue de': 'with a view to',
        'pour ce qui est de': 'as for',
        'quant à': 'as for',
        'en ce qui concerne': 'concerning',
        'au sujet de': 'about',
        'touchant': 'concerning',
        'relativement à': 'relative to',
        'vis-à-vis de': 'in relation to',
        'par rapport à': 'in relation to',
        'en fonction de': 'depending on',
        'selon': 'according to',
        'conformément à': 'in accordance with',
        'suivant': 'according to',
        'outre': 'besides',
        'en plus de': 'in addition to',
        'y compris': 'including',
        'notamment': 'in particular',
        'spécialement': 'especially',
        'particulièrement': 'particularly',
        'surtout': 'above all',
        'principalement': 'mainly',
        'essentiellement': 'essentially',
        'fondamentalement': 'fundamentally',
        'généralement': 'generally',
        'habituellement': 'usually',
        'normalement': 'normally',
        'ordinairement': 'ordinarily',
        'couramment': 'commonly',
        'fréquemment': 'frequently',
        'régulièrement': 'regularly',
        'occasionnellement': 'occasionally',
        'rarement': 'rarely',
        'exceptionnellement': 'exceptionally',
        'parfois': 'sometimes',
        'de temps en temps': 'from time to time',
        'de temps à autre': 'from time to time',
        'temps à autre': 'from time to time',
        'jamais': 'never',
        'ne... jamais': 'never',
        'toujours': 'always',
        'toujours est-il que': 'be that as it may',
        'en tout cas': 'in any case',
        'dans tous les cas': 'in any case',
        'dans tous les cas de figure': 'in all cases',
        'quoi qu\'il en soit': 'be that as it may',
        'en définitive': 'ultimately',
        'finalement': 'finally',
        'au final': 'in the end',
        'à la fin': 'at the end',
        'à terme': 'in the long run',
        'sur le long terme': 'in the long term',
        'sur le court terme': 'in the short term',
        'à court terme': 'in the short term',
        'à moyen terme': 'in the medium term',
        'à long terme': 'in the long term',
        'dès maintenant': 'from now on',
        'désormais': 'from now on',
        'à partir de maintenant': 'from now on',
        'à compter de ce jour': 'from this day forward',
        'd\'ores et déjà': 'as of now',
        'déjà': 'already',
        'encore': 'still/yet',
        'ne... plus': 'no longer',
        'ne... point': 'not at all',
        'ne... guère': 'hardly',
        'ne... nulle part': 'nowhere',
        'ne... jamais': 'never',
        'ne... rien': 'nothing',
        'ne... personne': 'nobody',
        'ne... que': 'only',
        'ne... aucun': 'no',
        'ne... nul': 'no',
        'seulement': 'only',
        'uniquement': 'only',
        'simplement': 'simply',
        'juste': 'just',
        'exactement': 'exactly',
        'précisément': 'precisely',
        'approximativement': 'approximately',
        'environ': 'approximately',
        'à peu près': 'approximately',
        'presque': 'almost',
        'quasiment': 'almost',
        'pratiquement': 'practically',
        'virtuellement': 'virtually',
        'réellement': 'really',
        'réellement': 'really',
        'effectivement': 'indeed',
        'vraiment': 'truly',
        'sincèrement': 'sincerely',
        'franchement': 'frankly',
        'honnêtement': 'honestly',
        'carrément': 'frankly/blatantly',
        'absolument': 'absolutely',
        'certainement': 'certainly',
        'sûrement': 'surely',
        'probablement': 'probably',
        'peut-être': 'maybe',
        'éventuellement': 'possibly',
        'potentiellement': 'potentially',
        'naturellement': 'naturally',
        'logiquement': 'logically',
        'normalement': 'normally',
        'évidemment': 'obviously',
        'bien sûr': 'of course',
        'bien entendu': 'of course',
        'sans doute': 'without a doubt',
        'sans aucun doute': 'without any doubt',
        'indubitablement': 'indubitably',
        'certainement': 'certainly',
        'assurément': 'assuredly',
        'manifestement': 'manifestly',
        'clairement': 'clearly',
        'nettement': 'clearly',
        'distinctement': 'distinctly',
        'précisément': 'precisely',
        'exactement': 'exactly',
        'spécifiquement': 'specifically',
        'particulièrement': 'particularly',
        'spécialement': 'especially',
        'notamment': 'notably',
        'surtout': 'above all',
        'principalement': 'mainly',
        'essentiellement': 'essentially',
        'fondamentalement': 'fundamentally',
        'généralement': 'generally',
        'habituellement': 'usually',
        'couramment': 'commonly',
        'fréquemment': 'frequently',
        'régulièrement': 'regularly',
        'occasionnellement': 'occasionally',
        'rarement': 'rarely',
        'exceptionnellement': 'exceptionally',
        'parfois': 'sometimes',
        'de temps en temps': 'from time to time',
        'jamais': 'never',
        'toujours': 'always',
        'souvent': 'often',
        'de temps en temps': 'from time to time',
        'temps à autre': 'from time to time',
        'de temps à autre': 'from time to time',
        'parfois': 'sometimes',
	}
};
