const FRENCH_ENGLISH_DICTIONARY = {
    'fr-en': {
        // Salutations et Expressions de Base
        'bonjour': 'hello',
        'salut': 'hi',
        'bonsoir': 'good evening',
        'bonne nuit': 'good night',
        'au revoir': 'goodbye',
        'à bientôt': 'see you soon',
        'bienvenue': 'welcome',
        'merci': 'thank you',
        's\'il vous plaît': 'please',
        'pardon': 'sorry',
        'excusez-moi': 'excuse me',
        'désolé': 'apologetic/sorry',
        'oui': 'yes',
        'non': 'no',
        'peut-être': 'maybe',
        'bien sûr': 'of course',
        'absolument': 'absolutely',
        'je ne sais pas': 'I don\'t know',
        'je comprends': 'I understand',
        'je ne comprends pas': 'I don\'t understand',
        'comment ça va': 'how are you',
        'ça va': 'it\'s going',
        'ça va bien': 'it\'s going well',
        'ça va mal': 'it\'s going badly',
        'pas de problème': 'no problem',
        'pas question': 'no question',
        'à plus tard': 'see you later',
        'bon appétit': 'enjoy your meal',
        'santé': 'health/cheers',
        'bonne chance': 'good luck',
        'joyeux anniversaire': 'happy birthday',
        'Joyeux Noël': 'Merry Christmas',
        'Bonne année': 'Happy New Year',
        'je t\'aime': 'I love you',
        'je t\'aime bien': 'I like you',
        'tu me manques': 'I miss you',
        'prends soin de toi': 'take care of yourself',
        'bon voyage': 'have a good trip',
        'bon rétablissement': 'get well soon',
        'félicitations': 'congratulations',
        'enchanté': 'nice to meet you',
        'à tout à l\'heure': 'see you later today',
        'à demain': 'see you tomorrow',
        'fais de beaux rêves': 'sweet dreams',
        'passe une bonne journée': 'have a good day',
        'bon week-end': 'good weekend',
        'bonnes vacances': 'happy holidays',

        // Pronoms
        'je': 'I',
        'tu': 'you',
        'il': 'he/she/it',
        'elle': 'he/she/it',
        'nous': 'we',
        'vous': 'you (plural)/they',
        'moi': 'me',
        'le mien': 'mine',
        'le tien': 'yours',
        'le sien': 'his/hers/its',
        'les miens': 'mine (plural)',
        'les tiens': 'yours (plural)',
        'les siens': 'his/hers/its (plural)',
        'le nôtre': 'ours',
        'le vôtre': 'yours (formal/plural)',
        'le leur': 'theirs',
        'mon': 'my',
        'ma': 'my (feminine)',
        'mes': 'my (plural)',
        'ton': 'your',
        'ta': 'your (feminine)',
        'tes': 'your (plural)',
        'son': 'his/her/its',
        'sa': 'his/her/its (feminine)',
        'ses': 'his/her/its (plural)',
        'notre': 'our',
        'nos': 'our (plural)',
        'votre': 'your (formal/plural)',
        'vos': 'your (formal/plural, plural)',
        'leur': 'their',

        // Famille
        'famille': 'family',
        'père': 'father',
        'mère': 'mother',
        'parents': 'parents',
        'enfant': 'child/children',
        'fils': 'son/daughter',
        'fille': 'son/daughter',
        'frère': 'brother',
        'sœur': 'sister',
        'grand-père': 'grandfather',
        'grand-mère': 'grandmother',
        'oncle': 'uncle',
        'tante': 'aunt',
        'cousin': 'cousin (male/female)',
        'cousine': 'cousin (male/female)',
        'neveu': 'nephew',
        'nièce': 'niece',
        'époux': 'spouse (male)',
        'épouse': 'spouse (female)',
        'mari': 'husband',
        'femme': 'wife/woman',
        'mariage': 'marriage',
        'marié': 'married (male/female)',
        'divorce': 'divorce',
        'divorcé': 'divorced (male/female)',
        'célibataire': 'single (male/female)',
        'fiancé': 'engaged (male/female)',
        'fiancée': 'engaged (male/female)',
        'beau-père': 'father-in-law',
        'belle-mère': 'mother-in-law',
        'beau-frère': 'brother-in-law',
        'belle-sœur': 'sister-in-law',
        'gendre': 'son-in-law',
        'belle-fille': 'daughter-in-law',
        'belle-famille': 'in-laws',
        'parrain': 'godfather',
        'marraine': 'godmother',
        'filleul': 'godson',
        'filleule': 'godson',
        'ancêtre': 'ancestor',
        'descendant': 'descendant',
        'postérité': 'posterity',
        'génération': 'generation',
        'héritier': 'heir (male)',
        'héritière': 'heir (female)',
        'orphelin': 'orphan (male)',
        'orpheline': 'orphan (female)',
        'jumeau': 'twin (male)',
        'jumelle': 'twin (female)',
        'aîné': 'elder (male/female)',
        'aînée': 'elder (male/female)',
        'cadet': 'younger (male/female)',
        'cadette': 'younger (male/female)',
        'benjamin': 'youngest (male/female)',
        'benjamine': 'youngest (male/female)',
        'parenté': 'kinship',
        'lien familial': 'family tie',
        'arbre généalogique': 'family tree',
        'membre': 'member',
        'proche': 'relative/close one',
        'tuteur': 'guardian (male)',
        'tutrice': 'guardian (female)',
        'protégé': 'protégé (male/female)',
        'protégée': 'protégé (male/female)',
        'compagnon': 'companion (male)',
        'compagne': 'companion (female)',
        'partenaire': 'partner',
        'associé': 'associate (male/female)',
        'associée': 'associate (male/female)',
        'collègue': 'colleague',
        'camarade': 'comrade/friend',
        'ami': 'friend (male/female)',
        'amie': 'friend (male/female)',
        'copain': 'buddy (male)',
        'copine': 'buddy (female)',
        'voisin': 'neighbor (male)',
        'voisine': 'neighbor (female)',
        'connaissance': 'acquaintance',
        'relations': 'relations',
        'contacts': 'contacts',
        'famille nucléaire': 'nuclear family',
        'famille élargie': 'extended family',
        'ménage': 'household',
        'foyer': 'home',
        'domicile': 'residence',
        'maison': 'house',

        // Personnes
        'homme': 'man',
        'personne': 'person',
        'gens': 'people',
        'individu': 'individual',
        'être humain': 'human being',
        'personnage': 'character',
        'personnalité': 'personality',
        'célébrité': 'celebrity',
        'vedette': 'star',
        'adulte': 'adult',
        'majeur': 'major/adult',
        'mineur': 'minor',
        'adolescent': 'adolescent (male)',
        'adolescente': 'adolescent (female)',
        'jeune': 'young (male/female)',
        'jeune homme': 'young man',
        'jeune femme': 'young woman',
        'jeunesse': 'youth',
        'bébé': 'baby',
        'nouveau-né': 'newborn (male/female)',
        'nouveau-née': 'newborn (male/female)',
        'vieux': 'old (male)',
        'vieille': 'old (female)',
        'personne âgée': 'elderly person',
        'vétéran': 'veteran',
        'étranger': 'foreigner (male)',
        'étrangère': 'foreigner (female)',
        'immigré': 'immigrant (male/female)',
        'immigrée': 'immigrant (male/female)',
        'touriste': 'tourist',
        'habitant': 'inhabitant (male/female)',
        'habitant': 'inhabitant (male/female)',
        'citoyen': 'citizen (male)',
        'citoyenne': 'citizen (female)',
        'national': 'national',
        'résident': 'resident (male/female)',
        'résidente': 'resident (male/female)',
        'local': 'local (male/female)',
        'locale': 'local (male/female)',

        // Professions
        'professionnel': 'professional (male/female)',
        'professionnelle': 'professional (male/female)',
        'expert': 'expert (male/female)',
        'experte': 'expert (male/female)',
        'spécialiste': 'specialist',
        'technicien': 'technician (male/female)',
        'technicienne': 'technician (male/female)',
        'artisan': 'artisan (male/female)',
        'artisane': 'artisan (male/female)',
        'ouvrier': 'worker (male)',
        'ouvrière': 'worker (female)',
        'employé': 'employee (male/female)',
        'employée': 'employee (male/female)',
        'travailleur': 'worker (male)',
        'travailleuse': 'worker (female)',
        'chef': 'boss/chief',
        'directeur': 'director (male)',
        'directrice': 'director (female)',
        'manager': 'manager',
        'gérant': 'manager',
        'patron': 'boss (male)',
        'patronne': 'boss (female)',
        'supérieur': 'superior (male)',
        'supérieure': 'superior (female)',
        'subordonné': 'subordinate (male/female)',
        'subordonnée': 'subordinate (male/female)',
        'collaborateur': 'collaborator (male)',
        'collaboratrice': 'collaborator (female)',
        'concurrent': 'competitor (male/female)',
        'concurrente': 'competitor (male/female)',
        'rival': 'rival (male/female)',
        'rivale': 'rival (male/female)',
        'adversaire': 'opponent (male)',
        'adversaire': 'opponent (female)',
        'allié': 'ally (male/female)',
        'alliée': 'ally (male/female)',
        'ennemi': 'enemy (male/female)',
        'ennemie': 'enemy (male/female)',
        'inconnu': 'stranger (male/female)',
        'inconnue': 'stranger (male/female)',
        'visiteur': 'visitor (male)',
        'visiteuse': 'visitor (female)',
        'invité': 'guest (male)',
        'invitée': 'guest (female)',
        'hôte': 'host (male)',
        'hôtesse': 'hostess',
        'client': 'client (male)',
        'cliente': 'client (female)',
        'acheteur': 'buyer (male)',
        'acheteuse': 'buyer (female)',
        'consommateur': 'consumer (male)',
        'consommatrice': 'consumer (female)',
        'vendeur': 'seller (male)',
        'vendeuse': 'seller (female)',
        'commerçant': 'merchant (male/female)',
        'commerçante': 'merchant (male/female)',
        'fournisseur': 'supplier (male)',
        'fournisseuse': 'supplier (female)',
        'prestataire': 'service provider (male/female)',
        'créateur': 'creator (male)',
        'créatrice': 'creator (female)',
        'artiste': 'artist',
        'peintre': 'painter (male)',
        'peintre': 'painter (female)',
        'sculpteur': 'sculptor (male)',
        'sculptrice': 'sculptor (female)',
        'musicien': 'musician (male)',
        'musicienne': 'musician (female)',
        'chanteur': 'singer (male)',
        'chanteuse': 'singer (female)',
        'danseur': 'dancer (male)',
        'danseuse': 'dancer (female)',
        'acteur': 'actor',
        'actrice': 'actress',
        'écrivain': 'writer (male/female)',
        'écrivaine': 'writer (male/female)',
        'poète': 'poet (male)',
        'poétesse': 'poet (female)',
        'journaliste': 'journalist',
        'reporter': 'reporter (male)',
        'reportere': 'reporter (female)',
        'présentateur': 'presenter (male)',
        'présentatrice': 'presenter (female)',
        'animateur': 'animator (male)',
        'animatrice': 'animator (female)',
        'modérateur': 'moderator (male)',
        'modératrice': 'moderator (female)',
        'professeur': 'professor',
        'enseignant': 'teacher (male)',
        'enseignante': 'teacher (female)',
        'éducateur': 'educator (male)',
        'éducatrice': 'educator (female)',
        'étudiant': 'student (male)',
        'étudiante': 'student (female)',
        'élève': 'pupil',
        'apprenti': 'apprentice (male)',
        'apprentie': 'apprentice (female)',
        'chercheur': 'researcher (male)',
        'chercheuse': 'researcher (female)',
        'scientifique': 'scientist',
        'inventeur': 'inventor (male)',
        'inventrice': 'inventor (female)',
        'médecin': 'doctor',
        'docteur': 'doctor',
        'chirurgien': 'surgeon (male)',
        'chirurgienne': 'surgeon (female)',
        'infirmier': 'nurse (male)',
        'infirmière': 'nurse (female)',
        'pharmacien': 'pharmacist (male)',
        'pharmacienne': 'pharmacist (female)',
        'dentiste': 'dentist',
        'vétérinaire': 'veterinarian',
        'psychologue': 'psychologist',
        'psychiatre': 'psychiatrist',
        'avocat': 'lawyer (male/female)',
        'avocate': 'lawyer (male/female)',
        'juge': 'judge',
        'procureur': 'prosecutor (male)',
        'procureure': 'prosecutor (female)',
        'policier': 'police officer',
        'gendarme': 'gendarmerie',
        'militaire': 'military',
        'soldat': 'soldier',
        'officier': 'officer',
        'capitaine': 'captain',
        'général': 'general',
        'homme politique': 'politician (male)',
        'femme politique': 'politician (female)',
        'député': 'deputy (male/female)',
        'députée': 'deputy (male/female)',
        'sénateur': 'senator (male)',
        'sénatrice': 'senator (female)',
        'ministre': 'minister',
        'président': 'president (male)',
        'présidente': 'president (female)',
        'maire': 'mayor',
        'conseiller': 'councilor (male)',
        'conseillère': 'councilor (female)',
        'administrateur': 'administrator (male)',
        'administratrice': 'administrator (female)',
        'fonctionnaire': 'civil servant',
        'employé public': 'public employee',
        'représentant': 'representative (male)',
        'représentante': 'representative (female)',
        'délégué': 'delegate (male/female)',
        'déléguée': 'delegate (male/female)',
        'ambassadeur': 'ambassador (male)',
        'ambassadrice': 'ambassador (female)',
        'consul': 'consul (male/female)',
        'consule': 'consul (male/female)',
        'diplomate': 'diplomat',
        'agent': 'agent',
        'espion': 'spy (male)',
        'espionne': 'spy (female)',
        'détective': 'detective',
        'enquêteur': 'investigator (male)',
        'enquêtrice': 'investigator (female)',
        'témoin': 'witness (male/female)',
        'témoin': 'witness (male/female)',
        'suspect': 'suspect (male/female)',
        'suspecte': 'suspect (male/female)',
        'criminel': 'criminal (male/female)',
        'criminelle': 'criminal (male/female)',
        'voleur': 'thief (male)',
        'voleuse': 'thief (female)',
        'assassin': 'assassin (male)',
        'assassine': 'assassin (female)',
        'bandit': 'bandit',
        'gangster': 'gangster',
        'prisonnier': 'prisoner (male)',
        'prisonnière': 'prisoner (female)',
        'délinquant': 'delinquent (male/female)',
        'délinquante': 'delinquent (male/female)',
        'victime': 'victim',
        'plaignant': 'plaintiff (male)',
        'plaignante': 'plaintiff (female)',
        'sauveteur': 'rescuer (male)',
        'sauveteuse': 'rescuer (female)',
        'héros': 'hero (male)',
        'héroïne': 'heroine',

        // Adjectifs
        'courageux': 'brave (male)',
        'courageuse': 'brave (female)',
        'brave': 'brave (male/female)',
        'timide': 'shy (male/female)',
        'audacieux': 'daring (male)',
        'audacieuse': 'daring (female)',
        'gentil': 'nice/kind (male/female)',
        'gentille': 'nice/kind (male/female)',
        'méchant': 'mean (male/female)',
        'méchante': 'mean (male/female)',
        'intelligent': 'intelligent (male/female)',
        'intelligente': 'intelligent (male/female)',
        'bête': 'stupid (male/female)',
        'sérieux': 'serious (male/female)',
        'sérieuse': 'serious (male/female)',
        'drôle': 'funny (male/female)',
        'heureux': 'happy (male)',
        'heureuse': 'happy (female)',
        'malheureux': 'unhappy (male)',
        'malheureuse': 'unhappy (female)',
        'content': 'happy/content (male/female)',
        'contente': 'happy/content (male/female)',
        'triste': 'sad (male/female)',
        'calme': 'calm (male/female)',
        'agité': 'agitated (male/female)',
        'agitée': 'agitated (male/female)',
        'beau': 'beautiful (male)',
        'belle': 'beautiful (female)',
        'joli': 'pretty (male/female)',
        'jolie': 'pretty (male/female)',
        'grand': 'big/large (male/female)',
        'grande': 'big/large (male/female)',
        'petit': 'small (male/female)',
        'petite': 'small (male/female)',
        'gros': 'fat (male/female)',
        'grosse': 'fat (male/female)',
        'maigre': 'thin (male/female)',
        'maigre': 'thin (male/female)',
        'haut': 'tall/high (male/female)',
        'haute': 'tall/high (male/female)',
        'bas': 'short/low (male/female)',
        'basse': 'short/low (male/female)',
        'long': 'long (male/female)',
        'longue': 'long (male/female)',
        'court': 'short (male/female)',
        'courte': 'short (male/female)',
        'large': 'wide (male/female)',
        'large': 'wide (male/female)',
        'étroit': 'narrow (male/female)',
        'étroite': 'narrow (male/female)',
        'riche': 'rich (male/female)',
        'riche': 'rich (male/female)',
        'pauvre': 'poor (male/female)',
        'pauvre': 'poor (male/female)',
        'fort': 'strong (male/female)',
        'forte': 'strong (male/female)',
        'faible': 'weak (male/female)',
        'faible': 'weak (male/female)',
        'sain': 'healthy (male/female)',
        'saine': 'healthy (male/female)',
        'malade': 'sick (male/female)',
        'malade': 'sick (male/female)',
        'propre': 'clean (male/female)',
        'propre': 'clean (male/female)',
        'sale': 'dirty (male/female)',
        'sale': 'dirty (male/female)',
        'chaud': 'hot (male/female)',
        'chaude': 'hot (male/female)',
        'froid': 'cold (male/female)',
        'froide': 'cold (male/female)',
        'rapide': 'fast (male/female)',
        'rapide': 'fast (male/female)',
        'lent': 'slow (male/female)',
        'lente': 'slow (male/female)',
        'facile': 'easy (male/female)',
        'facile': 'easy (male/female)',
        'difficile': 'difficult (male/female)',
        'difficile': 'difficult (male/female)',
        'nouveau': 'new (male)',
        'nouvelle': 'new (female)',
        'ancien': 'old (male)',
        'ancienne': 'old (female)',
        'premier': 'first (male)',
        'première': 'first (female)',
        'dernier': 'last (male)',
        'dernière': 'last (female)',
        'seul': 'alone (male/female)',
        'seule': 'alone (male/female)',
        'ensemble': 'together',
        'libre': 'free (male/female)',
        'libre': 'free (male/female)',
        'mort': 'dead (male)',
        'morte': 'dead (female)',
        'vivant': 'alive (male/female)',
        'vivante': 'alive (male/female)',

        // Lieux
        'ville': 'city',
        'cité': 'city',
        'métropole': 'metropolis',
        'capitale': 'capital',
        'village': 'village',
        'bourg': 'town',
        'hameau': 'hamlet',
        'quartier': 'neighborhood',
        'région': 'region',
        'province': 'province',
        'département': 'department',
        'canton': 'canton',
        'pays': 'country',
        'nation': 'nation',
        'état': 'state',
        'territoire': 'territory',
        'continent': 'continent',
        'monde': 'world',
        'planète': 'planet',
        'univers': 'universe',
        'terre': 'earth',
        'ciel': 'sky',
        'enfer': 'hell',
        'paradis': 'paradise',
        'soleil': 'sun',
        'lune': 'moon',
        'étoile': 'star',
        'galaxie': 'galaxy',
        'nébuleuse': 'nebula',
        'comète': 'comet',
        'astéroïde': 'asteroid',
        'cosmos': 'cosmos',
        'espace': 'space',
        'vide': 'void',
        'infini': 'infinity',
        'temps': 'time',
        'éternité': 'eternity',
        'instant': 'instant',
        'moment': 'moment',
        'passé': 'past',
        'présent': 'present',
        'futur': 'future',
        'avenir': 'future',
        'histoire': 'history',
        'mémoire': 'memory',
        'souvenir': 'souvenir',
        'tradition': 'tradition',
        'coutume': 'custom',
        'habitude': 'habit',
        'culture': 'culture',
        'civilisation': 'civilization',
        'société': 'society',
        'communauté': 'community',
        'peuple': 'people',
        'langue': 'language',
        'dialecte': 'dialect',
        'accent': 'accent',
        'prononciation': 'pronunciation',
        'mot': 'word',
        'vocabulaire': 'vocabulary',
        'dictionnaire': 'dictionary',
        'grammaire': 'grammar',
        'alphabet': 'alphabet',
        'lettre': 'letter',
        'phrase': 'sentence',
        'texte': 'text',
        'livre': 'book',
        'page': 'page',
        'chapitre': 'chapter',
        'paragraphe': 'paragraph',
        'titre': 'title',
        'auteur': 'author',
        'roman': 'novel',
        'nouvelle': 'short story',
        'conte': 'tale',
        'poésie': 'poetry',
        'théâtre': 'theater',
        'pièce': 'play',
        'acte': 'act',
        'scène': 'scene',
        'cinéma': 'cinema',
        'film': 'film',
        'réalisateur': 'director (male)',
        'réalisatrice': 'director (female)',
        'producteur': 'producer (male)',
        'productrice': 'producer (female)',
        'musique': 'music',
        'chanson': 'song',
        'mélodie': 'melody',
        'rythme': 'rhythm',
        'instrument': 'instrument',
        'orchestre': 'orchestra',
        'chorale': 'choir',
        'opéra': 'opera',
        'ballet': 'ballet',
        'danse': 'dance',
        'chorégraphie': 'choreography',
        'peinture': 'painting',
        'tableau': 'painting/canvas',
        'couleur': 'color',
        'sculpture': 'sculpture',
        'dessin': 'drawing',
        'dessinateur': 'drawer (male)',
        'dessinatrice': 'drawer (female)',
        'photographie': 'photography',
        'photographe': 'photographer (male/female)',
        'photo': 'photo',
        'architecture': 'architecture',
        'architecte': 'architect',
        'bâtiment': 'building',
        'design': 'design',
        'designer': 'designer (male)',
        'designere': 'designer (female)',
        'création': 'creation',
        'mode': 'fashion',
        'couturier': 'designer (male)',
        'couturière': 'designer (female)',
        'vêtement': 'clothing',
        'bijou': 'jewelry',
        'bijoutier': 'jeweler (male)',
        'bijoutière': 'jeweler (female)',
        'or': 'gold',
        'argent': 'silver/money',
        'diamant': 'diamond',
        'pierres précieuses': 'precious stones',
        'sport': 'sport',
        'athlétisme': 'athletics',
        'football': 'football',
        'basketball': 'basketball',
        'tennis': 'tennis',
        'golf': 'golf',
        'natation': 'swimming',
        'cyclisme': 'cycling',
        'ski': 'skiing',
        'alpinisme': 'mountaineering',
        'escalade': 'climbing',
        'plongée': 'diving',
        'surf': 'surfing',
        'voile': 'sailing',
        'aviron': 'rowing',
        'équitation': 'horse riding',
        'boxe': 'boxing',
        'judo': 'judo',
        'karaté': 'karate',
        'arts martiaux': 'martial arts',
        'compétition': 'competition',
        'match': 'match',
        'tournoi': 'tournament',
        'championnat': 'championship',
        'joueur': 'player (male)',
        'joueuse': 'player (female)',
        'équipe': 'team',
        'entraîneur': 'coach (male)',
        'entraîneuse': 'coach (female)',
        'arbitre': 'referee',
        'stade': 'stadium',
        'terrain': 'field',
        'piscine': 'swimming pool',
        'gymnase': 'gymnasium',
        'santé': 'health',
        'médecine': 'medicine',
        'maladie': 'illness',
        'symptôme': 'symptom',
        'douleur': 'pain',
        'fièvre': 'fever',
        'grippe': 'flu',
        'rhume': 'cold',
        'cancer': 'cancer',
        'diabète': 'diabetes',
        'cœur': 'heart',
        'pression': 'pressure',
        'traitement': 'treatment',
        'médicament': 'medication',
        'opération': 'operation',
        'guérison': 'healing',
        'rétablissement': 'recovery',
        'convalescence': 'convalescence',
        'alimentation': 'food/nutrition',
        'régime': 'diet',
        'diététique': 'dietetics',
        'vitamines': 'vitamins',
        'minéraux': 'minerals',
        'protéines': 'proteins',
        'glucides': 'carbohydrates',
        'nutrition': 'nutrition',
        'équilibre': 'balance',
        'poids': 'weight',
        'obésité': 'obesity',
        'exercice': 'exercise',
        'entraînement': 'training',
        'condition physique': 'physical condition',
        'bien-être': 'well-being',
        'relaxation': 'relaxation',
        'méditation': 'meditation',
        'stress': 'stress',
        'fatigue': 'fatigue',
        'épuisement': 'exhaustion',
        'burn-out': 'burnout',
        'sommeil': 'sleep',
        'insomnie': 'insomnia',
        'rêve': 'dream',
        'cauchemar': 'nightmare',
        'psychologie': 'psychology',
        'thérapie': 'therapy',
        'psychanalyse': 'psychoanalysis',
        'dépression': 'depression',
        'anxiété': 'anxiety',
        'phobie': 'phobia',
        'traumatisme': 'trauma',
        'addiction': 'addiction',
        'dépendance': 'dependence',
        'sevrage': 'withdrawal',
        'prévention': 'prevention',
        'vaccination': 'vaccination',
        'hygiène': 'hygiene',
        'sécurité': 'security',
        'protection': 'protection',
        'danger': 'danger',
        'risque': 'risk',
        'accident': 'accident',
        'urgence': 'emergency',
        'secours': 'help',
        'premiers secours': 'first aid',
        'assurance': 'insurance',
        'couverture': 'coverage',
        'remboursement': 'reimbursement',
        'technologie': 'technology',
        'informatique': 'computer science',
        'ordinateur': 'computer',
        'internet': 'internet',
        'web': 'web',
        'site web': 'website',
        'email': 'email',
        'smartphone': 'smartphone',
        'tablette': 'tablet',
        'application': 'application',
        'logiciel': 'software',
        'programme': 'program',
        'système': 'system',
        'réseau': 'network',
        'wifi': 'wifi',
        'bluetooth': 'bluetooth',
        'imprimante': 'printer',
        'scanner': 'scanner',
        'clavier': 'keyboard',
        'souris': 'mouse',
        'écran': 'screen',
        'moniteur': 'monitor',
        'processeur': 'processor',
        'mémoire': 'memory',
        'stockage': 'storage',
        'disque dur': 'hard drive',
        'cloud': 'cloud',
        'sauvegarde': 'backup',
        'cybersécurité': 'cybersecurity',
        'virus': 'virus',
        'piratage': 'hacking',
        'intelligence artificielle': 'artificial intelligence',
        'robot': 'robot',
        'automatisation': 'automation',
        'réalité virtuelle': 'virtual reality',
        'réalité augmentée': 'augmented reality',
        'innovation': 'innovation',
        'recherche': 'research',
        'développement': 'development',
        'science': 'science',
        'scientifique': 'scientific',
        'laboratoire': 'laboratory',
        'expérimentation': 'experimentation',
        'découverte': 'discovery',
        'invention': 'invention',
        'physique': 'physics',
        'chimie': 'chemistry',
        'biologie': 'biology',
        'mathématiques': 'mathematics',
        'astronomie': 'astronomy',
        'géologie': 'geology',
        'météorologie': 'meteorology',
        'écologie': 'ecology',
        'environnement': 'environment',
        'climat': 'climate',
        'pollution': 'pollution',
        'réchauffement climatique': 'global warming',
        'énergie': 'energy',
        'renouvelable': 'renewable',
        'solaire': 'solar',
        'éolien': 'wind',
        'développement durable': 'sustainable development',
        'recyclage': 'recycling',
        'gestion des déchets': 'waste management',
        'biodiversité': 'biodiversity',
        'espèce en danger': 'endangered species',
        'conservation': 'conservation',
        'préservation': 'preservation',
        'économie': 'economy',
        'finance': 'finance',
        'monnaie': 'currency',
        'budget': 'budget',
        'épargne': 'savings',
        'investissement': 'investment',
        'banque': 'bank',
        'crédit': 'credit',
        'emprunt': 'loan',
        'prêt': 'loan',
        'bourse': 'stock market',
        'action': 'share',
        'marché financier': 'financial market',
        'entreprise': 'company',
        'commerce': 'commerce',
        'industrie': 'industry',
        'production': 'production',
        'consommation': 'consumption',
        'importation': 'importation',
        'exportation': 'exportation',
        'commerce international': 'international trade',
        'marketing': 'marketing',
        'publicité': 'advertising',
        'promotion': 'promotion',
        'vente': 'sale',
        'achat': 'purchase',
        'négociation': 'negotiation',
        'contrat': 'contract',
        'travail': 'work',
        'emploi': 'employment',
        'carrière': 'career',
        'profession': 'profession',
        'salaire': 'salary',
        'revenu': 'income',
        'impôt': 'tax',
        'taxe': 'tax',
        'retraite': 'retirement',
        'sécurité sociale': 'social security',
        'éducation': 'education',
        'formation': 'training',
        'apprentissage': 'apprenticeship',
        'compétence': 'skill',
        'qualification': 'qualification',
        'certificat': 'certificate',
        'diplôme': 'diploma',
        'université': 'university',
        'études': 'studies',
        'politique': 'politics',
        'gouvernement': 'government',
        'démocratie': 'democracy',
        'élection': 'election',
        'vote': 'vote',
        'candidat': 'candidate (male/female)',
        'candidat': 'candidate (male/female)',
        'parti politique': 'political party',
        'campagne électorale': 'electoral campaign',
        'parlement': 'parliament',
        'sénat': 'senate',
        'assemblée': 'assembly',
        'loi': 'law',
        'législation': 'legislation',
        'règlement': 'regulation',
        'justice': 'justice',
        'tribunal': 'court',
        'cour': 'court',
        'police': 'police',
        'armée': 'army',
        'défense': 'defense',
        'relations internationales': 'international relations',
        'diplomatie': 'diplomacy',
        'traité': 'treaty',
        'accord': 'agreement',
        'alliance': 'alliance',
        'conflit': 'conflict',
        'guerre': 'war',
        'paix': 'peace',
        'terrorisme': 'terrorism',
        'menace': 'threat',
        'droits de l\'homme': 'human rights',
        'liberté': 'freedom',
        'égalité': 'equality',
        'fraternité': 'fraternity',
        'solidarité': 'solidarity',
        'modernité': 'modernity',
        'progrès': 'progress',
        'mondialisation': 'globalization',
        'mondialisation': 'globalization',
        'communication': 'communication',
        'information': 'information',
        'médias': 'media',
        'journalisme': 'journalism',
        'télévision': 'television',
        'radio': 'radio',
        'presse': 'press',
        'réseaux sociaux': 'social networks',
        'opinion publique': 'public opinion',
        'religion': 'religion',
        'foi': 'faith',
        'croyance': 'belief',
        'dieu': 'god',
        'église': 'church',
        'mosquée': 'mosque',
        'temple': 'temple',
        'synagogue': 'synagogue',
        'prière': 'prayer',
        'rituel': 'ritual',
        'cérémonie': 'ceremony',
        'spiritualité': 'spirituality',
        'philosophie': 'philosophy',
        'éthique': 'ethics',
        'moral': 'morality',
        'valeurs': 'values',
        'art': 'art',
        'esthétique': 'aesthetics',
        'beauté': 'beauty',
        'harmonie': 'harmony',
        'créativité': 'creativity',
        'expression': 'expression',
        'inspiration': 'inspiration',
        'talent': 'talent',
        'loisir': 'leisure',
        'divertissement': 'entertainment',
        'vacances': 'vacations',
        'tourisme': 'tourism',
        'voyage': 'travel',
        'aventure': 'adventure',
        'exploration': 'exploration',
        'nature': 'nature',
        'agriculture': 'agriculture',
        'pêche': 'fishing',
        'élevage': 'livestock farming',
        'récolte': 'harvest',
        'cultivation': 'cultivation',
        'cuisine': 'kitchen/cuisine',
        'gastronomie': 'gastronomy',
        'vin': 'wine',
        'spiritueux': 'spirits',
        'cocktail': 'cocktail',
        'fête': 'party',
        'célébration': 'celebration',
        'festival': 'festival',
        'concert': 'concert',
        'spectacle': 'show',
        'exposition': 'exhibition',
        'performance': 'performance',
        'forme physique': 'physical form',
        'transport': 'transport',
        'déplacement': 'movement',
        'circulation': 'circulation',
        'urbanisme': 'urbanism',
        'construction': 'construction',
        'habitat': 'habitat',
        'logement': 'housing',
        'immobilier': 'real estate',
        'ressources': 'resources',
        'matières premières': 'raw materials',
        'météo': 'weather',
        'durabilité': 'durability',
        'écosystème': 'ecosystem',
        'croissance': 'growth',
        'patrimoine': 'heritage',
        'identité': 'identity',
        'appartenance': 'belonging',
        'racines': 'roots',
        'diversité': 'diversity',
        'tolérance': 'tolerance',
        'respect': 'respect',
        'entraide': 'mutual aid',
        'coopération': 'cooperation',
        'équilibre': 'balance',
        'citoyenneté': 'citizenship',
        'participation': 'participation',
        'responsabilité': 'responsibility',
        'engagement': 'commitment',
        'implication': 'involvement',
        'développement personnel': 'personal development',
        'épanouissement': 'fulfillment',
        'connaissance de soi': 'self-knowledge',
        'réflexion': 'reflection',
        'sagesse': 'wisdom',
        'expérience': 'experience',
        'maturité': 'maturity',
        'évolution': 'evolution',
        'transformation': 'transformation',
        'changement': 'change',
        'adaptation': 'adaptation',
        'résilience': 'resilience',
        'courage': 'courage',
        'dépassement de soi': 'self-transcendence',
        'dépassement': 'surpassing',
        'accomplissement': 'accomplishment',
        'réalisation': 'realization',
        'succès': 'success',
        'bonheur': 'happiness',
        'plénitude': 'fullness',
        'amour': 'love',
        'amitié': 'friendship',
        'relations humaines': 'human relations',
        'couple': 'couple',
        'partenariat': 'partnership',
        'dialogue': 'dialogue',
        'écoute': 'listening',
        'compréhension': 'understanding',
        'empathie': 'empathy',
        'compassion': 'compassion',
        'partage': 'sharing',
        'générosité': 'generosity',
        'altruisme': 'altruism',
        'confiance': 'trust',
        'considération': 'consideration',
        'estime': 'esteem',
        'reconnaissance': 'recognition',
        'valorisation': 'valorization',
        'authenticité': 'authenticity',
        'sincérité': 'sincerity',
        'honnêteté': 'honesty',
        'intégrité': 'integrity',
        'droiture': 'rectitude',
        'transparence': 'transparency',
        'vérité': 'truth',
        'clarté': 'clarity',
        'lucidité': 'lucidity',
        'vigilance': 'vigilance',
        'attention': 'attention',
        'présence': 'presence',
        'mindfulness': 'mindfulness',
        'pleine conscience': 'full awareness',
        'contemplation': 'contemplation',

        // Verbes
        'manger': 'to eat',
        'boire': 'to drink',
        'dormir': 'to sleep',
        'travailler': 'to work',
        'étudier': 'to study',
        'jouer': 'to play',
        'chanter': 'to sing',
        'danser': 'to dance',
        'courir': 'to run',
        'marcher': 'to walk',
        'sauter': 'to jump',
        'nager': 'to swim',
        'voler': 'to fly/to steal',
        'grimper': 'to climb',
        'descendre': 'to descend',
        'monter': 'to ascend',
        'arriver': 'to arrive',
        'partir': 'to leave',
        'revenir': 'to come back',
        'retourner': 'to return',
        'sortir': 'to go out',
        'entrer': 'to enter',
        'rester': 'to stay',
        'demeurer': 'to remain',
        'vivre': 'to live',
        'habiter': 'to inhabit',
        'naître': 'to be born',
        'mourir': 'to die',
        'devenir': 'to become',
        'grandir': 'to grow up',
        'vieillir': 'to grow old',
        'changer': 'to change',
        'apprendre': 'to learn',
        'enseigner': 'to teach',
        'expliquer': 'to explain',
        'comprendre': 'to understand',
        'savoir': 'to know',
        'découvrir': 'to discover',
        'trouver': 'to find',
        'chercher': 'to search',
        'perdre': 'to lose',
        'oublier': 'to forget',
        'se souvenir': 'to remember',
        'penser': 'to think',
        'réfléchir': 'to reflect',
        'imaginer': 'to imagine',
        'croire': 'to believe',
        'douter': 'to doubt',
        'espérer': 'to hope',
        'attendre': 'to wait',
        'être patient': 'to be patient',
        'vouloir': 'to want',
        'désirer': 'to desire',
        'souhaiter': 'to wish',
        'préférer': 'to prefer',
        'aimer': 'to love/like',
        'adorer': 'to adore',
        'détester': 'to hate',
        'haïr': 'to hate',
        'pouvoir': 'to be able to',
        'devoir': 'to have to',
        'falloir': 'to be necessary',
        'sembler': 'to seem',
        'paraître': 'to appear',
        'être': 'to be',
        'avoir': 'to have',
        'faire': 'to do/make',
        'dire': 'to say',
        'voir': 'to see',
        'prendre': 'to take',
        'donner': 'to give',
        'recevoir': 'to receive',
        'offrir': 'to offer',
        'acheter': 'to buy',
        'vendre': 'to sell',
        'payer': 'to pay',
        'coûter': 'to cost',
        'valoir': 'to be worth',
        'peser': 'to weigh',
        'mesurer': 'to measure',
        'compter': 'to count',
        'calculer': 'to calculate',
        'additionner': 'to add',
        'soustraire': 'to subtract',
        'multiplier': 'to multiply',
        'diviser': 'to divide',
        'estimer': 'to estimate',
        'juger': 'to judge',
        'décider': 'to decide',
        'choisir': 'to choose',
        'déterminer': 'to determine',
        'fixer': 'to fix',
        'nommer': 'to name',
        'désigner': 'to designate',
        'appeler': 'to call',
        'qualifier': 'to qualify',
        'définir': 'to define',
        'caractériser': 'to characterize',
        'décrire': 'to describe',
        'représenter': 'to represent',
        'symboliser': 'to symbolize',
        'signifier': 'to signify',
        'indiquer': 'to indicate',
        'montrer': 'to show',
        'démontrer': 'to demonstrate',
        'révéler': 'to reveal',
        'dévoiler': 'to unveil',
        'exposer': 'to expose',
        'présenter': 'to present',
        'introduire': 'to introduce',
        'insérer': 'to insert',
        'incorporer': 'to incorporate',
        'intégrer': 'to integrate',
        'ajouter': 'to add',
        'compléter': 'to complete',
        'supplémenter': 'to supplement',
        'enrichir': 'to enrich',
        'améliorer': 'to improve',
        'parfaire': 'to perfect',
        'achever': 'to complete',
        'parachever': 'to complete thoroughly',
        'finaliser': 'to finalize',
        'terminer': 'to finish',
        'conclure': 'to conclude',
        'interrompre': 'to interrupt',
        'suspendre': 'to suspend',
        'cesser': 'to cease',
        'arrêter': 'to stop',
        'stopper': 'to stop',
        'abandonner': 'to abandon',
        'renoncer': 'to renounce',
        'céder': 'to cede',
        'lâcher': 'to let go',
        'relâcher': 'to release',
        'délivrer': 'to deliver',
        'libérer': 'to free',
        'affranchir': 'to enfranchise',
        'émanciper': 'to emancipate',
        'sauver': 'to save',
        'secourir': 'to rescue',
        'aider': 'to help',
        'assister': 'to assist',
        'soutenir': 'to support',
        'maintenir': 'to maintain',
        'préserver': 'to preserve',
        'conserver': 'to conserve',
        'garder': 'to keep',
        'protéger': 'to protect',
        'défendre': 'to defend',
        'abriter': 'to shelter',
        'couvrir': 'to cover',
        'envelopper': 'to wrap',
        'emballer': 'to pack',
        'emboîter': 'to fit together',
        'enfermer': 'to lock up',
        'enclore': 'to enclose',
        'entourer': 'to surround',
        'encercler': 'to encircle',
        'séparer': 'to separate',
        'distinguer': 'to distinguish',
        'différencier': 'to differentiate',
        'comparer': 'to compare',
        'analyser': 'to analyze',
        'examiner': 'to examine',
        'inspecter': 'to inspect',
        'observer': 'to observe',
        'surveiller': 'to monitor',
        'contrôler': 'to control',
        'vérifier': 'to verify',
        'tester': 'to test',
        'essayer': 'to try',
        'expérimenter': 'to experiment',
        'prouver': 'to prove',
        'établir': 'to establish',
        'confirmer': 'to confirm',
        'certifier': 'to certify',
        'garantir': 'to guarantee',
        'assurer': 'to assure',
        'épier': 'to spy on',
        'espionner': 'to spy',
        'percevoir': 'to perceive',
        'discerner': 'to discern',
        'interpréter': 'to interpret',
        'traduire': 'to translate',
        'raconter': 'to tell',
        'narrer': 'to narrate',
        's\'exprimer': 'to express oneself',
        'articuler': 'to articulate',
        'prononcer': 'to pronounce',
        'énoncer': 'to state',
        'déclarer': 'to declare',
        'annoncer': 'to announce',
        'informer': 'to inform',
        'prévenir': 'to prevent',
        'avertir': 'to warn',
        'alerter': 'to alert',
        'signaler': 'to signal',
        'dénoncer': 'to denounce',
        'accuser': 'to accuse',
        'inculper': 'to indict',
        'condamner': 'to condemn',
        'punir': 'to punish',
        'pardonner': 'to forgive',
        'excuser': 'to excuse',
        'absoudre': 'to absolve',
        'gracier': 'to grant amnesty',
        'amnistier': 'to amnesty',
        'se rappeler': 'to remember',
        'mémoriser': 'to memorize',
        's\'entraîner': 'to train oneself',
        'pratiquer': 'to practice',
        's\'exercer': 'to exercise oneself',
        'progresser': 'to progress',
        'avancer': 'to advance',
        'se développer': 'to develop oneself',
        'évoluer': 'to evolve',
        'se transformer': 'to transform',
        'modifier': 'to modify',
        'altérer': 'to alter',
        's\'adapter': 'to adapt',
        'ajuster': 'to adjust',
        'accroître': 'to increase',
        'augmenter': 'to augment',
        'diminuer': 'to diminish',
        'réduire': 'to reduce',
        'baisser': 'to lower',
        'se multiplier': 'to multiply oneself',
        'se reproduire': 'to reproduce oneself',
        'apparaître': 'to appear',
        'survenir': 'to occur',
        'se produire': 'to occur',
        'disparaître': 'to disappear',
        's\'évanouir': 'to faint',
        'décéder': 'to pass away',
        'trépasser': 'to pass away',
        'ressusciter': 'to resurrect',
        'renaître': 'to be reborn',
        'réapparaître': 'to reappear',
        'réémerger': 'to re-emerge',
        'exister': 'to exist',
        'subsister': 'to subsist',
        'survivre': 'to survive',
        'durer': 'to last',
        'persister': 'to persist',
        'continuer': 'to continue',
        'se maintenir': 'to maintain oneself',
        'appartenir': 'to belong',
        'dépendre': 'to depend',
        'reposer sur': 'to rest on',
        'concerner': 'to concern',
        'appliquer': 'to apply',
        'affecter': 'to affect',
        'toucher': 'to affect',
        'influencer': 'to influence',
        'provoquer': 'to provoke',
        'causer': 'to cause',
        'entraîner': 'to train/to cause',
        'déclencher': 'to trigger',
        'produire': 'to produce',
        'générer': 'to generate',
        'engendrer': 'to beget',
        'procréer': 'to procreate',
        'fabriquer': 'to manufacture',
        'manufacturer': 'to manufacture',
        'confectionner': 'to make',
        'élaborer': 'to elaborate',
        'composer': 'to compose',
        'constituer': 'to constitute',
        'former': 'to form',
        'bâtir': 'to build',
        'ériger': 'to erect',
        'édifier': 'to edify',
        'installer': 'to install',
        'disposer': 'to arrange',
        'placer': 'to place',
        'positionner': 'to position',
        'situer': 'to situate',
        'localiser': 'to locate',
        'organiser': 'to organize',
        'aménager': 'to arrange',
        'arranger': 'to arrange',
        'préparer': 'to prepare',
        'ranger': 'to tidy up',
        'classer': 'to classify',
        'ordonner': 'to order',
        'trier': 'to sort',
        'sélectionner': 'to select',
        'opter': 'to opt',
        'exiger': 'to demand',
        'demander': 'to ask',
        'prier': 'to pray',
        'supplier': 'to beg',
        'implorer': 'to implore',
        'nécessiter': 'to necessitate',
        'insister': 'to insist',
        'poursuivre': 'to pursue',
        'atteindre': 'to reach',
        'obtenir': 'to obtain',
        'gagner': 'to win/to earn',
        'rapporter': 'to bring back',
        'triompher': 'to triumph',
        'réussir': 'to succeed',
        'échouer': 'to fail',
        'manquer': 'to miss',
        'rater': 'to miss',
        'louper': 'to miss',
        'hésiter': 'to hesitate',
        'craindre': 'to fear',
        'redouter': 'to dread',
        'appréhender': 'to apprehend',
        'oser': 'to dare',
        'avouer': 'to admit',
        'confesser': 'to confess',
        'reconnaître': 'to recognize',
        'admettre': 'to admit',
        'nier': 'to deny',
        'démentir': 'to contradict',
        'contradire': 'to contradict',
        'réfuter': 'to refute',
        'argumenter': 'to argue',
        'discuter': 'to discuss',
        'débattre': 'to debate',
        'négocier': 'to negotiate',
        'dialoguer': 'to dialogue',
        'communiquer': 'to communicate',
        'transmettre': 'to transmit',
        'envoyer': 'to send',
        'expédier': 'to expedite',
        'poster': 'to post',
        'livrer': 'to deliver',
        'distribuer': 'to distribute',
        'rassembler': 'to gather',
        'réunir': 'to reunite',
        'grouper': 'to group',
        'associer': 'to associate',
        'lier': 'to link',
        'connecter': 'to connect',
        'brancher': 'to plug in',
        'relier': 'to connect',
        'joindre': 'to join',
        'unir': 'to unite',
        'garder': 'to look at/to keep',
        'écouter': 'to listen',
        'entendre': 'to hear',
        'saisir': 'to grasp',
        'parler': 'to speak',
        'tomber': 'to fall',
        'pousser': 'to push',
        'pousser': 'to grow'
    }
};