const CREOLE_FRENCH_DICTIONARY = {
    'creole-fr': {
        // Greetings and Basic Expressions
        'bonzour': 'bonjour',
        'sava': 'salut',
        'bonswar': 'bonsoir',
        'bonn nwi': 'bonne nuit',
        'aouarvoir': 'au revoir',
        'o byento': 'à bientôt',
        'byenvini': 'bienvenue',
        'mèrsi': 'merci',
        'si ou plé': 's\'il vous plaît',
        'pardon': 'pardon',
        'ekskiz-mwa': 'excusez-moi',
        'dézolé': 'désolé(e)',
        'wi': 'oui',
        'non': 'non',
        'petèt': 'peut-être',
        'byen sir': 'bien sûr',
        'absoliman': 'absolument',
        'mi pa koné': 'je ne sais pas',
        'mi konprann': 'je comprends',
        'mi pa konprann': 'je ne comprends pas',
        'komman i alé': 'comment allez-vous',
        'i alé': 'ça va',
        'i alé byen': 'ça va bien',
        'i alé mal': 'ça va mal',
        'pa problèm': 'pas de problème',
        'pa kwésyon': 'pas de question',
        'aplita': 'à plus tard',
        'bonapéti': 'bon appétit',
        'santé': 'santé/tchin',
        'bon chans': 'bonne chance',
        'bonn anivèrsèr': 'joyeux anniversaire',
        'bon Nwèl': 'Joyeux Noël',
        'bonn anné': 'Bonne année',
        'mon ti aim': 'je t\'aime',
        'mon ti kontan ou': 'je t\'aime bien',
        'mon mank ou': 'tu me manques',
        'pran swen dou': 'prends soin de toi',
        'bon voyaz': 'bon voyage',
        'bon rétablisman': 'bon rétablissement',
        'félicitazon': 'félicitations',
        'ou plézi': 'enchanté(e)',
        'o tou à lèr': 'à plus tard aujourd\'hui',
        'o demin': 'à demain',
        'fé bèl rèv': 'fais de beaux rêves',
        'pas bon zourné': 'passez une bonne journée',
        'bon wikenn': 'bon week-end',
        'bon vakans': 'bonnes vacances',
        
        // Pronouns
        'mi': 'je',
        'ou': 'tu',
        'li': 'il/elle',
        'nou': 'nous',
        'zot': 'vous/ils',
        'mwin': 'moi',
        'la mwin': 'le mien',
        'la tou': 'le tien',
        'la li': 'le sien',
        'lé mwin': 'les miens',
        'lé tou': 'les tiens',
        'lé li': 'les siens',
        'la notr': 'le nôtre',
        'la votr': 'le vôtre',
        'la lor': 'le leur',
        'mon': 'mon',
        'ma': 'ma',
        'mé': 'mes',
        'ton': 'ton',
        'ta': 'ta',
        'té': 'tes',
        'son': 'son',
        'sa': 'sa',
        'sé': 'ses',
        'notr': 'notre',
        'no': 'nos',
        'votr': 'votre',
        'vo': 'vos',
        'lor': 'leur',
        
        // Family
        'famill': 'famille',
        'pèr': 'père',
        'mèr': 'mère',
        'paran': 'parents',
        'zanfan': 'enfant/enfants',
        'fiy': 'fils/fille',
        'frèr': 'frère',
        'sér': 'sœur',
        'granpèr': 'grand-père',
        'granmèr': 'grand-mère',
        'onkl': 'oncle',
        'tant': 'tante',
        'kouzin': 'cousin/cousine',
        'névé': 'neveu',
        'niès': 'nièce',
        'épou': 'époux',
        'épous': 'épouse',
        'mari': 'mari',
        'fanm': 'femme',
        'mariaz': 'mariage',
        'marié': 'marié(e)',
        'divors': 'divorce',
        'divorsé': 'divorcé(e)',
        'sélibatèr': 'célibataire',
        'fiyansé': 'fiancé(e)',
        'bopèr': 'beau-père',
        'bèlmèr': 'belle-mère',
        'bofrèr': 'beau-frère',
        'bèlsér': 'belle-sœur',
        'zanndr': 'gendre',
        'bèlfiy': 'belle-fille',
        'bofiy': 'beau-fils',
        'bèlfamill': 'belle-famille',
        'parrén': 'parrain',
        'maren': 'marraine',
        'fiyul': 'filleul',
        'ansètr': 'ancêtre',
        'déandan': 'descendant',
        'postérité': 'postérité',
        'zénérasyon': 'génération',
        'éritié': 'héritier',
        'érityèr': 'héritière',
        'orfan': 'orphelin',
        'orfanin': 'orpheline',
        'zomò': 'jumeau',
        'zomòl': 'jumelle',
        'aîné': 'aîné(e)',
        'kadé': 'cadet(te)',
        'benjamin': 'benjamin',
        'paranté': 'parenté',
        'lyen famiyal': 'lien familial',
        'arbr zénéralojik': 'arbre généalogique',
        'mimbr': 'membre',
        'proch': 'proche',
        'titér': 'tuteur',
        'titris': 'tutrice',
        'protéjé': 'protégé(e)',
        'konpagnon': 'compagnon',
        'konpagn': 'compagne',
        'parténèr': 'partenaire',
        'asosyé': 'associé(e)',
        'kolèg': 'collègue',
        'kamarad': 'camarade',
        'lami': 'ami(e)',
        'kopén': 'copain',
        'kopin': 'copine',
        'voazén': 'voisin',
        'voazin': 'voisine',
        'konésans': 'connaissance',
        'relasyon': 'relations',
        'kontak': 'contacts',
        'famill nikléèr': 'famille nucléaire',
        'famill élarzi': 'famille élargie',
        'ménaz': 'ménage',
        'foyé': 'foyer',
        'domicil': 'résidence',
        'lakaz': 'maison',
        
        // People
        'nonm': 'homme',
        'moun': 'personne',
        'zanmoun': 'gens',
        'endividi': 'individu',
        'èr imen': 'être humain',
        'pèrsonaz': 'personnage',
        'pèrsonalité': 'personnalité',
        'sélébrité': 'célébrité',
        'védèt': 'vedette',
        'adilt': 'adulte',
        'mazé': 'majeur',
        'miné': 'mineur',
        'adolésan': 'adolescent',
        'adolésant': 'adolescente',
        'zenn': 'jeune',
        'zenn nonm': 'jeune homme',
        'zenn fanm': 'jeune femme',
        'zennés': 'jeunesse',
        'bébé': 'bébé',
        'novo-né': 'nouveau-né',
        'vyé': 'vieux',
        'vyéy': 'vieille',
        'moun azé': 'personne âgée',
        'vétéran': 'vétéran',
        'étrazé': 'étranger',
        'étrazér': 'étrangère',
        'imigré': 'immigré(e)',
        'tourist': 'touriste',
        'abitan': 'habitant',
        'sitoyé': 'citoyen',
        'sitoyénn': 'citoyenne',
        'nasyonal': 'national',
        'rézidan': 'résident',
        'lokal': 'local(e)',
        
        // Professions
        'profésyonèl': 'professionnel(le)',
        'ékspar': 'expert(e)',
        'spésyalist': 'spécialiste',
        'téknisyen': 'technicien(ne)',
        'artizan': 'artisan(e)',
        'ouvré': 'ouvrier',
        'ouvrir': 'ouvrière',
        'anplwayé': 'employé(e)',
        'travayé': 'travailleur',
        'travayéz': 'travailleuse',
        'chéf': 'chef',
        'dirèktèr': 'directeur',
        'dirèktris': 'directrice',
        'manazé': 'manager',
        'zéran': 'gérant',
        'patron': 'patron',
        'patronn': 'patronne',
        'sipéryé': 'supérieur',
        'sipéryér': 'supérieure',
        'sibordoné': 'subordonné(e)',
        'kolaboratér': 'collaborateur',
        'kolaboratris': 'collaboratrice',
        'konkiran': 'concurrent(e)',
        'rival': 'rivale',
        'advèrsèr': 'adversaire',
        'advèrsèr': 'adversaire',
        'alyé': 'allié(e)',
        'anmi': 'ennemi(e)',
        'inkonu': 'inconnu(e)',
        'vizité': 'visiteur',
        'vizitéz': 'visiteuse',
        'anvit': 'invité',
        'anvité': 'invitée',
        'ot': 'hôte',
        'otés': 'hôtesse',
        'klyan': 'client',
        'klyant': 'cliente',
        'achté': 'acheteur',
        'achtéz': 'acheteuse',
        'konzomatér': 'consommateur',
        'konzomatris': 'consommatrice',
        'vandé': 'vendeur',
        'vandéz': 'vendeuse',
        'komérsan': 'commerçant(e)',
        'fournisé': 'fournisseur',
        'fourniséz': 'fournisseuse',
        'préstatèr': 'prestataire de services',
        'kréatér': 'créateur',
        'kréatris': 'créatrice',
        'artist': 'artiste',
        'péntr': 'peintre',
        'skilptér': 'sculpteur',
        'skilptris': 'sculptrice',
        'mizisyen': 'musicien',
        'mizisyenn': 'musicienne',
        'chanté': 'chanteur',
        'chantéz': 'chanteuse',
        'dansé': 'danseur',
        'danséz': 'danseuse',
        'akté': 'acteur',
        'aktris': 'actrice',
        'ékrivén': 'écrivain(e)',
        'poét': 'poète',
        'poétés': 'poétesse',
        'zournalist': 'journaliste',
        'rporté': 'reporter',
        'prézantatér': 'présentateur',
        'prézantatris': 'présentatrice',
        'animatér': 'animateur',
        'animatris': 'animatrice',
        'modératér': 'modérateur',
        'modératris': 'modératrice',
        'profésé': 'professeur',
        'anségnan': 'enseignant',
        'anségnant': 'enseignante',
        'édikatér': 'éducateur',
        'édikatris': 'éducatrice',
        'étydyan': 'étudiant',
        'étydiant': 'étudiante',
        'élév': 'élève',
        'apran': 'apprenti',
        'aprant': 'apprentie',
        'sersé': 'chercheur',
        'serséz': 'chercheuse',
        'syantifik': 'scientifique',
        'anvantér': 'inventeur',
        'anvantris': 'inventrice',
        'médésin': 'médecin',
        'doktèr': 'docteur',
        'sirizyen': 'chirurgien',
        'sirizyenn': 'chirurgienne',
        'infirmyé': 'infirmier',
        'infirmyér': 'infirmière',
        'farmasyen': 'pharmacien',
        'farmasyenn': 'pharmacienne',
        'dantis': 'dentiste',
        'vétérinèr': 'vétérinaire',
        'psikolog': 'psychologue',
        'psikiatr': 'psychiatre',
        'avoka': 'avocat(e)',
        'zuj': 'juge',
        'prokiré': 'procureur',
        'prokirér': 'procureure',
        'polisyé': 'policier',
        'zandarm': 'gendarme',
        'militèr': 'militaire',
        'solda': 'soldat',
        'ofisyé': 'officier',
        'kapitén': 'capitaine',
        'zénéral': 'général',
        'politisyen': 'homme politique',
        'politisyenn': 'femme politique',
        'dépyé': 'député(e)',
        'sénatér': 'sénateur',
        'sénatris': 'sénatrice',
        'ministr': 'ministre',
        'prézidan': 'président',
        'prézidant': 'présidente',
        'mèr': 'maire',
        'konséyé': 'conseiller',
        'konséyér': 'conseillère',
        'administratér': 'administrateur',
        'administratris': 'administratrice',
        'fonksyonèr': 'fonctionnaire',
        'anplwayé piblik': 'employé public',
        'réprézantan': 'représentant',
        'réprézantant': 'représentante',
        'délégué': 'délégué(e)',
        'anbasadé': 'ambassadeur',
        'anbasadris': 'ambassadrice',
        'konsul': 'consul',
        'diplomat': 'diplomate',
        'azan': 'agent',
        'éspyon': 'espion',
        'éspyonn': 'espionne',
        'déktiv': 'détective',
        'ankètér': 'enquêteur',
        'ankètris': 'enquêtrice',
        'témwan': 'témoin',
        'suspèk': 'suspect(e)',
        'kriminel': 'criminel(le)',
        'volé': 'voleur',
        'voléz': 'voleuse',
        'asasan': 'assassin',
        'asasinn': 'assassine',
        'bandi': 'bandit',
        'gangstér': 'gangster',
        'prizonyé': 'prisonnier',
        'prizonyér': 'prisonnière',
        'délinkan': 'délinquant(e)',
        'viktim': 'victime',
        'plénian': 'plaignant',
        'plényant': 'plaignante',
        'souvété': 'sauveteur',
        'souvétéz': 'sauveteuse',
        'éro': 'héros',
        'éroyn': 'héroïne',
        
        // Adjectives
        'kourazé': 'courageux',
        'kourazéz': 'courageuse',
        'brav': 'brave',
        'timid': 'timide',
        'odasié': 'audacieux',
        'odasiéz': 'audacieuse',
        'zanmèl': 'gentil(le)',
        'méchan': 'méchant(e)',
        'intélijan': 'intelligent(e)',
        'bèt': 'bête',
        'séryé': 'sérieux/sérieuse',
        'dròl': 'drôle',
        'éré': 'heureux',
        'éréz': 'heureuse',
        'maléré': 'malheureux',
        'maléréz': 'malheureuse',
        'kontan': 'content(e)',
        'trist': 'triste',
        'kalm': 'calme',
        'azité': 'agité(e)',
        'bo': 'beau',
        'bèl': 'belle',
        'joli': 'joli(e)',
        'gran': 'grand(e)',
        'ti': 'petit(e)',
        'gro': 'gros(se)',
        'mains': 'maigre',
        'ho': 'haut(e)',
        'ba': 'bas/basse',
        'lon': 'long(longue)',
        'kour': 'court(e)',
        'larz': 'large',
        'étrèt': 'étroit(e)',
        'rich': 'riche',
        'povr': 'pauvre',
        'for': 'fort(e)',
        'fèb': 'faible',
        'sén': 'sain(e)',
        'malad': 'malade',
        'propr': 'propre',
        'sal': 'sale',
        'cho': 'chaud(e)',
        'frèt': 'froid(e)',
        'rapit': 'rapide',
        'lan': 'lent(e)',
        'fasil': 'facile',
        'difisil': 'difficile',
        'nouvò': 'nouveau',
        'nouvèl': 'nouvelle',
        'ansyen': 'ancien',
        'ansyenn': 'ancienne',
        'premyé': 'premier',
        'premyér': 'première',
        'dényé': 'dernier',
        'dényér': 'dernière',
        'sèl': 'seul(e)',
        'ansanbl': 'ensemble',
        'libr': 'libre',
        'mor': 'mort',
        'mòr': 'morte',
        'vivan': 'vivant(e)',
        
        // Places
        'vil': 'ville',
        'sité': 'cité',
        'métropol': 'métropole',
        'kapital': 'capitale',
        'vilaz': 'village',
        'bor': 'bourg',
        'amò': 'hameau',
        'kartié': 'quartier',
        'rézion': 'région',
        'provinss': 'province',
        'départman': 'département',
        'kanton': 'canton',
        'péyi': 'pays',
        'nasyon': 'nation',
        'éta': 'état',
        'teritwar': 'territoire',
        'kontinan': 'continent',
        'mond': 'monde',
        'planèt': 'planète',
        'linivèr': 'univers',
        'latèr': 'terre',
        'siel': 'ciel',
        'anfèr': 'enfer',
        'paradi': 'paradis',
        'soléy': 'soleil',
        'lalin': 'lune',
        'zétwal': 'étoile',
        'galaksi': 'galaxie',
        'nébilis': 'nébuleuse',
        'komèt': 'comète',
        'astéroid': 'astéroïde',
        'kosmos': 'cosmos',
        'espas': 'espace',
        'vid': 'vide',
        'anfini': 'infini',
        'tan': 'temps',
        'éternité': 'éternité',
        'instan': 'instant',
        'momàn': 'moment',
        'pasé': 'passé',
        'prézan': 'présent',
        'fitir': 'futur',
        'avenir': 'avenir',
        'istwar': 'histoire',
        'mémoir': 'mémoire',
        'souvnir': 'souvenir',
        'tradisyon': 'tradition',
        'koutim': 'coutume',
        'abitid': 'habitude',
        'kiltir': 'culture',
        'sivilizasyon': 'civilisation',
        'sosyété': 'société',
        'komynoté': 'communauté',
        'pèp': 'peuple',
        'lang': 'langue',
        'dyalèkt': 'dialecte',
        'aksan': 'accent',
        'prononsasyon': 'prononciation',
        'mo': 'mot',
        'vokabilèr': 'vocabulaire',
        'diksyonnèr': 'dictionnaire',
        'gramèr': 'grammaire',
        'alfabé': 'alphabet',
        'lètr': 'lettre',
        'fraz': 'phrase',
        'téks': 'texte',
        'livr': 'livre',
        'paz': 'page',
        'chapitr': 'chapitre',
        'paragraf': 'paragraphe',
        'titr': 'titre',
        'oté': 'auteur',
        'roman': 'roman',
        'nuvèl': 'nouvelle',
        'kont': 'conte',
        'poézi': 'poésie',
        'téatr': 'théâtre',
        'pyès': 'pièce',
        'akt': 'acte',
        'sén': 'scène',
        'sinéma': 'cinéma',
        'film': 'film',
        'réalizatér': 'réalisateur',
        'réalizatris': 'réalisatrice',
        'prodikté': 'producteur',
        'prodiktris': 'productrice',
        'mizik': 'musique',
        'chanson': 'chanson',
        'mélodi': 'mélodie',
        'ritm': 'rythme',
        'instruman': 'instrument',
        'orkèstr': 'orchestre',
        'koral': 'chœur',
        'opéra': 'opéra',
        'balé': 'ballet',
        'dans': 'danse',
        'korégrafi': 'chorégraphie',
        'péntir': 'peinture',
        'tablo': 'tableau',
        'koulèr': 'couleur',
        'skilptir': 'sculpture',
        'désén': 'dessin',
        'désinatér': 'dessinateur',
        'désinatris': 'dessinatrice',
        'fotografi': 'photographie',
        'fotograf': 'photographe',
        'foto': 'photo',
        'arkitektir': 'architecture',
        'arkitekt': 'architecte',
        'batiman': 'bâtiment',
        'dézén': 'design',
        'dézénér': 'designer',
        'kréasyon': 'création',
        'mod': 'mode',
        'koutiryé': 'couturier',
        'kouturiér': 'couturière',
        'vètman': 'vêtement',
        'bijou': 'bijou',
        'zwayé': 'bijoutier',
        'zwayér': 'bijoutière',
        'lor': 'or',
        'arzan': 'argent',
        'dyaman': 'diamant',
        'pyèr présyé': 'pierres précieuses',
        'spor': 'sport',
        'atlétism': 'athlétisme',
        'futbòl': 'football',
        'basketbòl': 'basketball',
        'ténis': 'tennis',
        'gòlf': 'golf',
        'natason': 'natation',
        'siklism': 'cyclisme',
        'ski': 'ski',
        'alpinism': 'alpinisme',
        'éskalad': 'escalade',
        'plonzé': 'plongée',
        'surf': 'surf',
        'voal': 'voile',
        'aviron': 'aviron',
        'ékitasyon': 'équitation',
        'boks': 'boxe',
        'zudo': 'judo',
        'karaté': 'karaté',
        'ar martiyo': 'arts martiaux',
        'konpétisyon': 'compétition',
        'match': 'match',
        'tournwa': 'tournoi',
        'chanpionna': 'championnat',
        'zoué': 'joueur',
        'zouzé': 'joueuse',
        'ékip': 'équipe',
        'antrénné': 'entraîneur',
        'antrénnéz': 'entraîneuse',
        'arbitr': 'arbitre',
        'stad': 'stade',
        'térén': 'terrain',
        'pisin': 'piscine',
        'zimnaz': 'gymnase',
        'santé': 'santé',
        'médésin': 'médecine',
        'maladi': 'maladie',
        'simptom': 'symptôme',
        'doulér': 'douleur',
        'fyèvr': 'fièvre',
        'grip': 'grippe',
        'rum': 'rhume',
        'kansér': 'cancer',
        'dyabèt': 'diabète',
        'kèr': 'cœur',
        'présyon': 'pression',
        'trétmman': 'traitement',
        'médikaman': 'médicament',
        'opérasyon': 'opération',
        'gyérizon': 'guérison',
        'rétablisman': 'rétablissement',
        'konvalésans': 'convalescence',
        'alimantasyon': 'alimentation',
        'rézim': 'régime',
        'dyététik': 'diététique',
        'vitamin': 'vitamines',
        'minéro': 'minéraux',
        'protéin': 'protéines',
        'glisid': 'glucides',
        'nitrisyon': 'nutrition',
        'ékilibr': 'équilibre',
        'pwa': 'poids',
        'obézité': 'obésité',
        'égsèrsis': 'exercice',
        'antrénnman': 'entraînement',
        'kondisyon fizik': 'condition physique',
        'byenètr': 'bien-être',
        'relaksazon': 'relaxation',
        'méditasyon': 'méditation',
        'strès': 'stress',
        'fatig': 'fatigue',
        'épizman': 'épuisement',
        'burn-ot': 'burn-out',
        'soméy': 'sommeil',
        'inzomni': 'insomnie',
        'rèv': 'rêve',
        'kochmar': 'cauchemar',
        'psikoloji': 'psychologie',
        'térapie': 'thérapie',
        'psikanaliz': 'psychanalyse',
        'déprésyon': 'dépression',
        'anksyété': 'anxiété',
        'fobi': 'phobie',
        'tròtism': 'traumatisme',
        'adiksion': 'addiction',
        'dépadans': 'dépendance',
        'sévraz': 'sevrage',
        'prévansyon': 'prévention',
        'vaksinasyon': 'vaccination',
        'yizyén': 'hygiène',
        'sékirité': 'sécurité',
        'proteksyon': 'protection',
        'danzé': 'danger',
        'risk': 'risque',
        'aksidan': 'accident',
        'irzans': 'urgence',
        'sékou': 'secours',
        'premyé sékou': 'premiers secours',
        'asirans': 'assurance',
        'kouvèrtir': 'couverture',
        'ranbourseman': 'remboursement',
        'téknoloji': 'technologie',
        'informatik': 'informatique',
        'ordinatér': 'ordinateur',
        'intèrnèt': 'internet',
        'web': 'web',
        'sit web': 'site web',
        'imèl': 'email',
        'smartfon': 'smartphone',
        'tablèt': 'tablette',
        'aplikasyon': 'application',
        'lojisyèl': 'logiciel',
        'progrann': 'programme',
        'sistém': 'système',
        'rézo': 'réseau',
        'wifi': 'wifi',
        'blutut': 'bluetooth',
        'imprimant': 'imprimante',
        'skané': 'scanner',
        'klavyé': 'clavier',
        'souri': 'souris',
        'ékrann': 'écran',
        'monitér': 'moniteur',
        'prosesér': 'processeur',
        'mémoir': 'mémoire',
        'stokaz': 'stockage',
        'disk dur': 'disque dur',
        'klod': 'cloud',
        'souvégard': 'sauvegarde',
        'sibérsékirité': 'cybersécurité',
        'virus': 'virus',
        'pirataz': 'piratage',
        'intélijans artisyisyèl': 'intelligence artificielle',
        'robot': 'robot',
        'otomatisazon': 'automatisation',
        'réalité virtièl': 'réalité virtuelle',
        'réalité ogmenté': 'réalité augmentée',
        'inovasyon': 'innovation',
        'sers': 'recherche',
        'dévelopman': 'développement',
        'syans': 'science',
        'syantifik': 'scientifique',
        'laboratwar': 'laboratoire',
        'éksérimantasyon': 'expérimentation',
        'dékouvèrt': 'découverte',
        'anvansyon': 'invention',
        'fizik': 'physique',
        'chimi': 'chimie',
        'bioloji': 'biologie',
        'matématik': 'mathématiques',
        'astronomi': 'astronomie',
        'zéoloji': 'géologie',
        'météoroloji': 'météorologie',
        'ékoloji': 'écologie',
        'anvironman': 'environnement',
        'klima': 'climat',
        'polisyon': 'pollution',
        'réchaufman klimatik': 'réchauffement climatique',
        'énerzi': 'énergie',
        'renouvlabl': 'renouvelable',
        'solèr': 'solaire',
        'éolyen': 'éolien',
        'dévelopman durabl': 'développement durable',
        'siklaz': 'recyclage',
        'zèsyon dé déché': 'gestion des déchets',
        'byodivérsité': 'biodiversité',
        'espés an danzé': 'espèces en danger',
        'konèrvasyon': 'conservation',
        'prézèrvasyon': 'préservation',
        'ékonomi': 'économie',
        'finans': 'finance',
        'monay': 'monnaie',
        'budzé': 'budget',
        'épargn': 'épargne',
        'anvestisman': 'investissement',
        'bank': 'banque',
        'krédi': 'crédit',
        'anpran': 'prêt',
        'pré': 'prêt',
        'bours': 'bourse',
        'aksyon': 'action',
        'marché finansyé': 'marché financier',
        'antrepriz': 'entreprise',
        'komèrs': 'commerce',
        'indistri': 'industrie',
        'prodiksyon': 'production',
        'konsozmasyon': 'consommation',
        'anportasyon': 'importation',
        'ékspòrtasyon': 'exportation',
        'komèrs entèrnasyonal': 'commerce international',
        'marketing': 'marketing',
        'piblisité': 'publicité',
        'promosyon': 'promotion',
        'vant': 'vente',
        'acha': 'achat',
        'négosiasyon': 'négociation',
        'kontra': 'contrat',
        'travay': 'travail',
        'anploé': 'emploi',
        'karyér': 'carrière',
        'profésyon': 'profession',
        'salèr': 'salaire',
        'revénu': 'revenu',
        'anpo': 'impôt',
        'taks': 'taxe',
        'rètrait': 'retraite',
        'sékirité sosyal': 'sécurité sociale',
        'édikasyon': 'éducation',
        'formazon': 'formation',
        'aprantisaz': 'apprentissage',
        'konpétans': 'compétence',
        'kalifikasyon': 'qualification',
        'sèrtifikat': 'certificat',
        'diplom': 'diplôme',
        'linivèrsité': 'université',
        'étyd': 'études',
        'politik': 'politique',
        'gouvanman': 'gouvernement',
        'démokrasi': 'démocratie',
        'éléksyon': 'élection',
        'vot': 'vote',
        'kandida': 'candidat(e)',
        'parti politik': 'parti politique',
        'kanpan élèktoral': 'campagne électorale',
        'parlman': 'parlement',
        'séna': 'sénat',
        'asanblé': 'assemblée',
        'lwa': 'loi',
        'lézislasion': 'législation',
        'régliman': 'règlement',
        'zistis': 'justice',
        'tribinal': 'tribunal',
        'kour': 'cour',
        'polis': 'police',
        'armé': 'armée',
        'défans': 'défense',
        'relasyon entèrnasyonal': 'relations internationales',
        'diplomasi': 'diplomatie',
        'tréyé': 'traité',
        'akor': 'accord',
        'alyans': 'alliance',
        'konfli': 'conflit',
        'gèr': 'guerre',
        'pé': 'paix',
        'térorism': 'terrorisme',
        'menas': 'menace',
        'dwa dé lom': 'droits de l\'homme',
        'libèrté': 'liberté',
        'égalité': 'égalité',
        'fratérnité': 'fraternité',
        'solidarité': 'solidarité',
        'modèrnité': 'modernité',
        'progrè': 'progrès',
        'globalizasyon': 'mondialisation',
        'mondyalizasyon': 'mondialisation',
        'komynikasyon': 'communication',
        'informazon': 'information',
        'médya': 'médias',
        'zournalism': 'journalisme',
        'télevizyon': 'télévision',
        'radio': 'radio',
        'prés': 'presse',
        'rézo sosyo': 'réseaux sociaux',
        'opinyon piblik': 'opinion publique',
        'rélijyon': 'religion',
        'fwa': 'foi',
        'kroyans': 'croyance',
        'dyé': 'dieu',
        'légliz': 'église',
        'moské': 'mosquée',
        'tanpl': 'temple',
        'sinagòg': 'synagogue',
        'priyèr': 'prière',
        'ritiyèl': 'rituel',
        'sérémoni': 'cérémonie',
        'spiritwalité': 'spiritualité',
        'filozofi': 'philosophie',
        'étik': 'éthique',
        'moral': 'morale',
        'valé': 'valeurs',
        'ar': 'art',
        'estétik': 'esthétique',
        'bauté': 'beauté',
        'armoni': 'harmonie',
        'kréativité': 'créativité',
        'éksprésyon': 'expression',
        'inspirasyon': 'inspiration',
        'talan': 'talent',
        'lwazir': 'loisir',
        'divèrtisman': 'divertissement',
        'vakans': 'vacances',
        'tourism': 'tourisme',
        'vwiyaz': 'voyage',
        'avantir': 'aventure',
        'éksplorazon': 'exploration',
        'natiir': 'nature',
        'agrikiltir': 'agriculture',
        'péché': 'pêche',
        'élévaz': 'élevage',
        'rékolt': 'récolte',
        'kultivazon': 'culture',
        'kizin': 'cuisine',
        'gastronomi': 'gastronomie',
        'van': 'vin',
        'spiritié': 'spiritueux',
        'koktéy': 'cocktail',
        'fèt': 'fête',
        'sélébrasyon': 'célébration',
        'festival': 'festival',
        'konsèr': 'concert',
        'spètakl': 'spectacle',
        'éksposisyon': 'exposition',
        'pèrformans': 'performance',
        'form fizik': 'forme physique',
        'transpor': 'transport',
        'déplasman': 'déplacement',
        'sirkilasyon': 'circulation',
        'irbanism': 'urbanisme',
        'konstriksyon': 'construction',
        'abita': 'habitat',
        'lozman': 'logement',
        'imobilié': 'immobilier',
        'résours': 'ressources',
        'matyèr prémyé': 'matières premières',
        'météo': 'météo',
        'durabilité': 'durabilité',
        'ékosistém': 'écosystème',
        'kroysans': 'croissance',
        'patrimwan': 'patrimoine',
        'idantité': 'identité',
        'apartnans': 'appartenance',
        'rasin': 'racines',
        'divèrsité': 'diversité',
        'tolérans': 'tolérance',
        'respè': 'respect',
        'antréid': 'entraide',
        'koopérasyon': 'coopération',
        'ékilibr': 'équilibre',
        'sitwayanneté': 'citoyenneté',
        'partisipasyon': 'participation',
        'réponsabilité': 'responsabilité',
        'angazman': 'engagement',
        'implikasyon': 'implication',
        'dévelopman pèrsonèl': 'développement personnel',
        'épanisman': 'épanouissement',
        'konésans dé lwa-mèm': 'connaissance de soi',
        'réflèksyon': 'réflexion',
        'sazès': 'sagesse',
        'éksperyans': 'expérience',
        'matirité': 'maturité',
        'évolisyon': 'évolution',
        'transformazon': 'transformation',
        'zanzman': 'changement',
        'adaptazon': 'adaptation',
        'rézilyans': 'résilience',
        'kouraz': 'courage',
        'dépasman dé lwa-mèm': 'dépassement de soi',
        'dépasman': 'dépassement',
        'akomplisman': 'accomplissement',
        'réalizasyon': 'réalisation',
        'siksé': 'succès',
        'bonèr': 'bonheur',
        'plénitid': 'plénitude',
        'lamour': 'amour',
        'amitié': 'amitié',
        'relasyon imén': 'relations humaines',
        'kupl': 'couple',
        'parténaria': 'partenariat',
        'dyalog': 'dialogue',
        'ékout': 'écoute',
        'konprénsyon': 'compréhension',
        'anpati': 'empathie',
        'konpasyon': 'compassion',
        'partaz': 'partage',
        'zénérosité': 'générosité',
        'altrism': 'altruisme',
        'konfyans': 'confiance',
        'konsidérasyon': 'considération',
        'estim': 'estime',
        'rekonésans': 'reconnaissance',
        'valorizasyon': 'valorisation',
        'otantisité': 'authenticité',
        'sinsérité': 'sincérité',
        'onèté': 'honnêteté',
        'intégrité': 'intégrité',
        'droitir': 'droiture',
        'transparans': 'transparence',
        'vérité': 'vérité',
        'klarté': 'clarté',
        'lisidité': 'lucidité',
        'vizilans': 'vigilance',
        'atansyon': 'attention',
        'présans': 'présence',
        'mindfulness': 'pleine conscience',
        'plén konfyans': 'pleine conscience',
        'kontanplasyon': 'contemplation',
        
        // Verbs
        'manz': 'manger',
        'bwar': 'boire',
        'dormi': 'dormir',
        'travay': 'travailler',
        'étidyé': 'étudier',
        'zoué': 'jouer',
        'chanté': 'chanter',
        'dansé': 'danser',
        'kouri': 'courir',
        'mars': 'marcher',
        'soté': 'sauter',
        'nagé': 'nager',
        'volé': 'voler',
        'gripé': 'grimper',
        'désan': 'descendre',
        'monté': 'monter',
        'arivé': 'arriver',
        'parti': 'partir',
        'rvini': 'revenir',
        'rourné': 'retourner',
        'soti': 'sortir',
        'antré': 'entrer',
        'rété': 'rester',
        'dmoré': 'demeurer',
        'viv': 'vivre',
        'abité': 'habiter',
        'nèss': 'naître',
        'mouri': 'mourir',
        'dévini': 'devenir',
        'granndir': 'grandir',
        'vyéyir': 'vieillir',
        'zanzé': 'changer',
        'apran': 'apprendre',
        'anségné': 'enseigner',
        'ékspliké': 'expliquer',
        'konprann': 'comprendre',
        'koné': 'connaître',
        'dékouvr': 'découvrir',
        'trouvé': 'trouver',
        'sersé': 'chercher',
        'pèrd': 'perdre',
        'oublié': 'oublier',
        'souvnir': 'se souvenir',
        'pansé': 'penser',
        'réfléchi': 'réfléchir',
        'imaziné': 'imaginer',
        'kwar': 'croire',
        'douté': 'douter',
        'éspéré': 'espérer',
        'atann': 'attendre',
        'pasyanté': 'être patient',
        'vlé': 'vouloir',
        'déziré': 'désirer',
        'souété': 'souhaiter',
        'préféré': 'préférer',
        'aimé': 'aimer',
        'adoré': 'adorer',
        'détésté': 'détester',
        'é': 'haïr',
        'kapav': 'pouvoir',
        'dwar': 'devoir',
        'falwar': 'falloir',
        'sanblé': 'sembler',
        'aparètr': 'apparaître',
        'lé': 'être',
        'gagn': 'avoir',
        'fé': 'faire',
        'dir': 'dire',
        'war': 'voir',
        'pran': 'prendre',
        'donn': 'donner',
        'résouwar': 'recevoir',
        'ofrir': 'offrir',
        'achté': 'acheter',
        'vand': 'vendre',
        'payé': 'payer',
        'kouté': 'coûter',
        'valwar': 'valoir',
        'pézé': 'peser',
        'mezuré': 'mesurer',
        'konté': 'compter',
        'kalkilé': 'calculer',
        'adisyoné': 'additionner',
        'soustré': 'soustraire',
        'multiplié': 'multiplier',
        'divizé': 'diviser',
        'éstimé': 'estimer',
        'zjugé': 'juger',
        'désidé': 'décider',
        'chwazi': 'choisir',
        'détérminé': 'déterminer',
        'fixé': 'fixer',
        'nomé': 'nommer',
        'dézigné': 'désigner',
        'apélé': 'appeler',
        'kalifyé': 'qualifier',
        'définir': 'définir',
        'karaktérizé': 'caractériser',
        'dékrir': 'décrire',
        'reprézanté': 'représenter',
        'simbolizé': 'symboliser',
        'signifyé': 'signifier',
        'andiké': 'indiquer',
        'montré': 'montrer',
        'démontré': 'démontrer',
        'révéler': 'révéler',
        'dévwalyé': 'dévoiler',
        'ékspozé': 'exposer',
        'prézanté': 'présenter',
        'antrouir': 'introduire',
        'anséré': 'insérer',
        'ankorporé': 'incorporer',
        'anlégré': 'intégrer',
        'ajouté': 'ajouter',
        'konplété': 'compléter',
        'séplémanté': 'supplémenter',
        'anrichir': 'enrichir',
        'anélyoré': 'améliorer',
        'parfèr': 'parfaire',
        'achévér': 'achever',
        'parachévér': 'parachever',
        'finalizé': 'finaliser',
        'términé': 'terminer',
        'konkly': 'conclure',
        'anteromp': 'interrompre',
        'sispan': 'suspendre',
        'sésé': 'cesser',
        'arété': 'arrêter',
        'stopé': 'stopper',
        'abandoné': 'abandonner',
        'rononsé': 'renoncer',
        'sédé': 'céder',
        'laché': 'lâcher',
        'relaché': 'relâcher',
        'délivré': 'délivrer',
        'libéré': 'libérer',
        'afranchir': 'affranchir',
        'émasipé': 'émanciper',
        'sové': 'sauver',
        'sékourir': 'secourir',
        'édé': 'aider',
        'asisté': 'assister',
        'souténir': 'soutenir',
        'manténir': 'maintenir',
        'préservé': 'préserver',
        'konservé': 'conserver',
        'gardé': 'garder',
        'protégé': 'protéger',
        'défand': 'défendre',
        'abrité': 'abriter',
        'kouvri': 'couvrir',
        'anvelopé': 'envelopper',
        'anbalé': 'emballer',
        'anbwaté': 'emboîter',
        'anfermé': 'enfermer',
        'anklor': 'enclôturer',
        'anouré': 'entourer',
        'ansèrklé': 'encercler',
        'séparé': 'séparer',
        'distangé': 'distinguer',
        'diféransyé': 'différencier',
        'komparé': 'comparer',
        'analizé': 'analyser',
        'égzaminé': 'examiner',
        'anspèkté': 'inspecter',
        'obsèrvé': 'observer',
        'sirvéyé': 'surveiller',
        'kontrolé': 'contrôler',
        'vérifyé': 'vérifier',
        'tésté': 'tester',
        'ésayé': 'essayer',
        'éksérimanté': 'expérimenter',
        'prouvé': 'prouver',
        'établir': 'établir',
        'konfirmé': 'confirmer',
        'sèrtifyé': 'certifier',
        'garantir': 'garantir',
        'asiré': 'assurer',
        'épyé': 'épier',
        'éspyoné': 'espionner',
        'pèrsoar': 'percevoir',
        'disèrné': 'discerner',
        'anterprété': 'interpréter',
        'tradwir': 'traduire',
        'rakonté': 'raconter',
        'narré': 'narrer',
        's-éksprimé': 's\'exprimer',
        'artikilé': 'articuler',
        'prononsé': 'prononcer',
        'éonsé': 'énoncer',
        'déklaré': 'déclarer',
        'anonsé': 'annoncer',
        'anformé': 'informer',
        'prévénir': 'prévenir',
        'avertir': 'avertir',
        'alarté': 'alerter',
        'signalé': 'signaler',
        'dénonsé': 'dénoncer',
        'akuzé': 'accuser',
        'ankilpé': 'inculper',
        'kondanné': 'condamner',
        'punir': 'punir',
        'pardoné': 'pardonner',
        'ékuzé': 'excuser',
        'absoudr': 'absoudre',
        'grasié': 'gracier',
        'anmistié': 'amnistier',
        's-rapélé': 'se rappeler',
        'mémorizé': 'mémoriser',
        's-antrené': 's\'entraîner',
        'pratiké': 'pratiquer',
        'égsèrsé': 'exercer',
        's-égsèrsé': 's\'exercer',
        'progréssé': 'progresser',
        'avansé': 'avancer',
        's-dévelopé': 'se développer',
        'évolyé': 'évoluer',
        'transformé': 'transformer',
        'modifyé': 'modifier',
        'altéré': 'altérer',
        'adapté': 'adapter',
        'azusté': 'ajuster',
        'akrwatr': 'accroître',
        'ogmanté': 'augmenter',
        'diminyé': 'diminuer',
        'réduir': 'réduire',
        'bésé': 'baisser',
        's-miltiplié': 'se multiplier',
        's-reprodwir': 'se reproduire',
        'émérzé': 'émerger',
        'sirvénir': 'survenir',
        's-prodwir': 'se produire',
        'disparètr': 'disparaître',
        's-évanwir': 's\'évanouir',
        'désédé': 'décéder',
        'trépasé': 'trépasser',
        'résisité': 'ressusciter',
        'rénèss': 'renaître',
        'réaparètr': 'réapparaître',
        'réémérzé': 'réémerger',
        'égzisté': 'exister',
        'sizisté': 'subsister',
        'sirviv': 'survivre',
        'diré': 'durer',
        'persisté': 'persister',
        'kontinyé': 'continuer',
        's-manténir': 'se maintenir',
        'aparténir': 'appartenir',
        'dépan': 'dépendre',
        'rpozé sur': 'reposer sur',
        'konserné': 'concerner',
        'anpliké': 'appliquer',
        'afekté': 'affecter',
        'touché': 'affecter',
        'anflansé': 'influencer',
        'provoqué': 'provoquer',
        'kozé': 'causer',
        'antrénné': 'entraîner',
        'déklanché': 'déclencher',
        'prodwir': 'produire',
        'zénéré': 'générer',
        'anzandré': 'engendrer',
        'prokréé': 'procréer',
        'fabriké': 'fabriquer',
        'manifaktiré': 'manufacturer',
        'konféksyoné': 'confectionner',
        'élabaré': 'élaborer',
        'kompozé': 'composer',
        'konstitwé': 'constituer',
        'formé': 'former',
        'batir': 'bâtir',
        'érizé': 'ériger',
        'édifyé': 'édifier',
        'anstalé': 'installer',
        'dépozé': 'disposer',
        'plasé': 'placer',
        'pozisyoné': 'positionner',
        'situé': 'situer',
        'lokalizé': 'localiser',
        'organizé': 'organiser',
        'amanazé': 'aménager',
        'aranjé': 'arranger',
        'préparé': 'préparer',
        'ranzé': 'ranger',
        'klasé': 'classer',
        'ordonné': 'ordonner',
        'triyé': 'trier',
        'sélèksyoné': 'sélectionner',
        'opté': 'opter',
        'ézigé': 'exiger',
        'mandé': 'demander',
        'priyé': 'prier',
        'souplié': 'supplier',
        'anploré': 'implorer',
        'nésésité': 'nécessiter',
        'ansisté': 'insister',
        'poursivir': 'poursuivre',
        'atén': 'atteindre',
        'obténir': 'obtenir',
        'gagné': 'gagner',
        'ranporté': 'rapporter',
        'triomfé': 'triompher',
        'réyisi': 'réussir',
        'échwé': 'échouer',
        'manké': 'manquer',
        'raté': 'rater',
        'loupé': 'louper',
        'ézité': 'hésiter',
        'krén': 'craindre',
        'rédouté': 'redouter',
        'apréandé': 'appréhender',
        'ozé': 'oser',
        'avoué': 'avouer',
        'konfésé': 'confesser',
        'rekonèt': 'reconnaître',
        'admetr': 'admettre',
        'nié': 'nier',
        'déméntir': 'démentir',
        'kontradir': 'contredire',
        'réfuté': 'réfuter',
        'argimanté': 'argumenter',
        'diskuté': 'discuter',
        'débatt': 'débattre',
        'négosyé': 'négocier',
        'dialogé': 'dialoguer',
        'komyniké': 'communiquer',
        'transmèt': 'transmettre',
        'anvoyé': 'envoyer',
        'éspédyé': 'expédier',
        'posté': 'poster',
        'livré': 'livrer',
        'distribyé': 'distribuer',
        'rasanblé': 'rassembler',
        'réynir': 'réunir',
        'goupé': 'grouper',
        'asosyé': 'associer',
        'lyé': 'lier',
        'konèkté': 'connecter',
        'branché': 'brancher',
        'rlyé': 'relier',
        'zwan': 'joindre',
        'ynir': 'unir',
        'gardé': 'regarder',
        'ékouté': 'écouter',
        'tand': 'entendre',
        'sésir': 'saisir',
        'kozé': 'parler',
        'tomber': 'tomber',
        'pousé': 'pousser',
        'krwatr': 'croître',
        
        // Food and Drinks
        'diri': 'riz',
        'may': 'maïs',
        'pwa': 'haricots',
        'légim': 'légumes',
        'fri': 'frites',
        'viann': 'viande',
        'poul': 'poulet',
        'pwason': 'poisson',
        'kri': 'crevettes',
        'bannann': 'banane',
        'mang': 'mangue',
        'zorey': 'ananas',
        'pam': 'pain',
        'lapen': 'lapin',
        'kabri': 'chèvre',
        'zef': 'œuf',
        'lèt': 'lait',
        'dilo': 'eau',
        'sik': 'sucre',
        'sèl': 'sel',
        'pimant': 'poivre',
        'bwa': 'bois/arbre',
        'fwi': 'fruit',
        'legim': 'légume',
        'kari': 'cari',
        'rougay': 'sauce piquante',
        'briyad': 'riz frit',
        'samoussa': 'samosa',
        'bouchon': 'ravioli',
        'massalé': 'cari de viande',
        'carry': 'cari',
        'kaldu': 'bouillon',
        'soup': 'soupe',
        'salad': 'salade',
        'desè': 'dessert',
        'gato': 'gâteau',
        'sòflé': 'soufflé',
        'krèm': 'crème',
        'glasy': 'glace',
        'chokola': 'chocolat',
        'bonbon': 'bonbon',
        'biskwit': 'biscuit',
        'kafé': 'café',
        'té': 'thé',
        'sok': 'jus',
        'limonad': 'limonade',
        'biér': 'bière',
        'vin': 'vin',
        'rhom': 'rhum',
        'koko': 'noix de coco',
        'vanil': 'vanille',
        'kanel': 'cannelle',
        'klouvis': 'clou de girofle',
        'mitch': 'gingembre',
        'kari': 'feuille de cari',
        'zamann': 'tamarin',
        'karambol': 'carambole',
        'litchi': 'litchi',
        'longan': 'longane',
        'friz': 'pois',
        'zolive': 'olive',
        'fromaz': 'fromage',
        'bèr': 'beurre',
        'lék': 'huile',
        'vinaigr': 'vinaigre',
        'sos': 'sauce',
        'mayonéz': 'mayonnaise',
        'moutad': 'moutarde',
        'kéchap': 'ketchup',
        'kétchap': 'ketchup',
        'konfitir': 'confiture',
        'miel': 'miel',
        'patis': 'pâtisserie',
        'krouasan': 'croissant',
        'panin': 'sandwich',
        'pizza': 'pizza',
        'pasta': 'pâtes',
        'riz': 'riz',
        'nwid': 'nouilles',
        'choucrout': 'choucroute',
        'toufu': 'tofu',
        'soja': 'soja',
        'zaboka': 'avocat',
        'tomat': 'tomate',
        'zonyon': 'oignon',
        'lalo': 'épinard',
        'chocho': 'chayote',
        'brèd': 'fèves',
        'pwa koulé': 'lentilles',
        'sousouma': 'cresson',
        'was': 'citrouille',
        'kourz': 'courgette',
        'konkonb': 'concombre',
        'chou': 'chou',
        'karòt': 'carotte',
        'navet': 'navet',
        'pòtiron': 'potiron',
        'patat': 'patate douce',
        'piman': 'poivre',
        'piman do': 'piment',
        'lay': 'ail',
        'persil': 'persil',
        'koriandr': 'coriandre',
        'bwan': 'thym',
        'romarin': 'romarin',
        'lauri': 'laurier',
        'basilik': 'basilic',
        'sari': 'cari',
        'masala': 'masala',
        'tandoori': 'tandoori',
        'tikka': 'tikka',
        'naan': 'pain naan',
        'roti': 'roti',
        'dosa': 'dosa',
        'idli': 'idli',
        'samosa': 'samosa',
        'pakora': 'pakora',
        'vada': 'vada',
        'idli': 'idli',
        'chatni': 'chutney',
        'achar': 'achar',
        'salad': 'salade',
        'caviar': 'caviar',
        'foi gras': 'foie gras',
        'truf': 'truffe',
        'kaviar': 'caviar',
        'omlèt': 'omelette',
        'krèp': 'crêpe',
        'vafèl': 'gaufre',
        'gofr': 'gaufre',
        'beignet': 'beignet',
        'kroasan': 'croissant',
        'pain': 'pain',
        'bagèt': 'baguette',
        'sandwich': 'sandwich',
        'hamburger': 'hamburger',
        'hotdog': 'hot dog',
        'pizza': 'pizza',
        'tako': 'taco',
        'burito': 'burrito',
        'kebab': 'kebab',
        'falafel': 'falafel',
        'sushi': 'sushi',
        'sashimi': 'sashimi',
        'ramen': 'ramen',
        'tempura': 'tempura',
        'yakitori': 'yakitori',
        'satay': 'satay',
        'spring roll': 'rouleau de printemps',
        'dim sum': 'dim sum',
        'dumpling': 'ravioli',
        'noodle': 'nouille',
        'poulet': 'poulet',
        'canard': 'canard',
        'dinde': 'dinde',
        'agneau': 'agneau',
        'mouton': 'mouton',
        'veau': 'veau',
        'porc': 'porc',
        'bœuf': 'bœuf',
        'jambon': 'jambon',
        'saucisse': 'saucisse',
        'bacon': 'bacon',
        'côtelette': 'côtelette',
        'steak': 'steak',
        'côte de bœuf': 'côte de bœuf',
        'entrecôte': 'entrecôte',
        'filet': 'filet',
        'rôti': 'rôti',
        'bouilli': 'bouilli',
        'frit': 'frit',
        'grillé': 'grillé',
        'cuit': 'cuit',
        'cru': 'cru',
        'mûr': 'mûr',
        'pas mûr': 'pas mûr',
        'frais': 'frais',
        'congelé': 'congelé',
        'en conserve': 'en conserve',
        'séché': 'séché',
        'salé': 'salé',
        'sucré': 'sucré',
        'acide': 'acide',
        'amer': 'amer',
        'épicé': 'épicé',
        'fade': 'fade',
        'délicieux': 'délicieux',
        'savoureux': 'savoureux',
        'fade': 'sans goût',
        'mauvais': 'mauvais',
        'pourri': 'pourri',
        'cuit': 'cuit',
        'brûlé': 'brûlé',
        'croquant': 'croquant',
        'mou': 'mou',
        'dur': 'dur',
        'chaud': 'chaud',
        'froid': 'froid',
        'tiède': 'tiède',
        'glacé': 'glacé',
        'bouillant': 'bouillant',
        'petit-déjeuner': 'petit-déjeuner',
        'déjeuner': 'déjeuner',
        'dîner': 'dîner',
        'collation': 'collation',
        'goûter': 'goûter',
        'apéritif': 'apéritif',
        'digestif': 'digestif',
        'recette': 'recette',
        'cuisine': 'cuisine',
        'cuisinier': 'cuisinier',
        'cuisinière': 'cuisinière',
        'chef': 'chef',
        'restaurant': 'restaurant',
        'café': 'café',
        'bistro': 'bistro',
        'brasserie': 'brasserie',
        'fast food': 'fast food',
        'livraison': 'livraison',
        'emporter': 'emporter',
        'service': 'service',
        'menu': 'menu',
        'carte': 'carte',
        'plat du jour': 'plat du jour',
        'spécialité': 'spécialité',
        'formule': 'formule',
        'buffet': 'buffet',
        'self-service': 'self-service',
        'boisson': 'boisson',
        'alcool': 'alcool',
        'boisson alcoolisée': 'boisson alcoolisée',
        'boisson non alcoolisée': 'boisson non alcoolisée',
        'cocktail': 'cocktail',
        'apéritif': 'apéritif',
        'digestif': 'digestif',
        'vin rouge': 'vin rouge',
        'vin blanc': 'vin blanc',
        'vin rosé': 'vin rosé',
        'champagne': 'champagne',
        'bière': 'bière',
        'cider': 'cidre',
        'whisky': 'whisky',
        'vodka': 'vodka',
        'gin': 'gin',
        'rhum': 'rhum',
        'liqueur': 'liqueur',
        'jus': 'jus',
        'nectar': 'nectar',
        'nectar de fruits': 'nectar de fruits',
        'smoothie': 'smoothie',
        'milkshake': 'milkshake',
        'soda': 'soda',
        'eau minérale': 'eau minérale',
        'eau gazeuse': 'eau gazeuse',
        'eau plate': 'eau plate',
        'thé': 'thé',
        'thé glacé': 'thé glacé',
        'infusion': 'infusion',
        'café': 'café',
        'café au lait': 'café au lait',
        'expresso': 'expresso',
        'cappuccino': 'cappuccino',
        'latte': 'latte',
        'chocolat chaud': 'chocolat chaud',
        'sirop': 'sirop',
        'boisson énergisante': 'boisson énergisante',
        'boisson sportive': 'boisson sportive',
        'cannette': 'canette',
        'bouteille': 'bouteille',
        'verre': 'verre',
        'tasse': 'tasse',
        'mug': 'mug',
        'pichet': 'pichet',
        'carafe': 'carafe',
        'bol': 'bol',
        'assiette': 'assiette',
        'couvert': 'couvert',
        'fourchette': 'fourchette',
        'couteau': 'couteau',
        'cuillère': 'cuillère',
        'cuillère à soupe': 'cuillère à soupe',
        'cuillère à café': 'cuillère à café',
        'verre': 'verre',
        'tasse': 'tasse',
        'bol': 'bol',
        'assiette': 'assiette',
        'plat': 'plat',
        'poêle': 'poêle',
        'casserole': 'casserole',
        'faitout': 'faitout',
        'marmite': 'marmite',
        'passoire': 'passoire',
        'passoire': 'passoire',
        'fouet': 'fouet',
        'rouleau à pâtisserie': 'rouleau à pâtisserie',
        'planche à découper': 'planche à découper',
        'balance': 'balance',
        'mesure': 'mesure',
        'four': 'four',
        'micro-ondes': 'micro-ondes',
        'plaque de cuisson': 'plaque de cuisson',
        'grill': 'grill',
        'frigo': 'frigo',
        'congélateur': 'congélateur',
        'lave-vaisselle': 'lave-vaisselle',
        'évier': 'évier',
        'robinet': 'robinet',
        'table': 'table',
        'chaise': 'chaise',
        'tabouret': 'tabouret',
        'nappe': 'nappe',
        'serviette': 'serviette',
        'napperon': 'napperon',
        'dessert': 'dessert',
        'fruit': 'fruit',
        'légume': 'légume',
        'viande': 'viande',
        'poisson': 'poisson',
        'fruits de mer': 'fruits de mer',
        'volaille': 'volaille',
        'charcuterie': 'charcuterie',
        'fromage': 'fromage',
        'pain': 'pain',
        'viennoiserie': 'viennoiserie',
        'pâtisserie': 'pâtisserie',
        'confiserie': 'confiserie',
        'épicerie': 'épicerie',
        'marché': 'marché',
        'supermarché': 'supermarché',
        'hypermarché': 'hypermarché',
        'épicerie fine': 'épicerie fine',
        'boulangerie': 'boulangerie',
        'pâtisserie': 'pâtisserie',
        'boucher': 'boucher',
        'poissonnier': 'poissonnier',
        'crémier': 'crémier',
        'marchand de vin': 'marchand de vin',
        'primeur': 'primeur',
        'cuisinier': 'cuisinier',
        'chef': 'chef',
        'pâtissier': 'pâtissier',
        'boulanger': 'boulanger',
        'serveur': 'serveur',
        'serveuse': 'serveuse',
        'sommelier': 'sommelier',
        'barman': 'barman',
        'barmaid': 'barmaid',
        'plongeur': 'plongeur',
        'restaurateur': 'restaurateur',
        'cuisinier': 'cuisinier',
        'chef de cuisine': 'chef de cuisine',
        'sous-chef': 'sous-chef',
        'commis de cuisine': 'commis de cuisine',
        'pâtissier': 'pâtissier',
        'boulanger': 'boulanger',
        'chocolatier': 'chocolatier',
        'glacier': 'glacier',
        'traiteur': 'traiteur',
        'livreur': 'livreur',
        'client': 'client',
        'habitué': 'habitué',
        'critique gastronomique': 'critique gastronomique',
        'guide gastronomique': 'guide gastronomique',
        'étoile Michelin': 'étoile Michelin',
        'repas': 'repas',
        'festin': 'festin',
        'banquet': 'banquet',
        'buffet': 'buffet',
        'casse-croûte': 'casse-croûte',
        'en-cas': 'en-cas',
        'picnic': 'pique-nique',
        'barbecue': 'barbecue',
        'grillade': 'grillade',
        'cuisine': 'cuisine',
        'recette': 'recette',
        'ingrédient': 'ingrédient',
        'préparation': 'préparation',
        'cuisson': 'cuisson',
        'assaisonnement': 'assaisonnement',
        'épice': 'épice',
        'herbe aromatique': 'herbe aromatique',
        'condiment': 'condiment',
        'sauce': 'sauce',
        'vinaigrette': 'vinaigrette',
        'marinade': 'marinade',
        'fumage': 'fumage',
        'saumure': 'saumure',
        'conservation': 'conservation',
        'stérilisation': 'stérilisation',
        'pasteurisation': 'pasteurisation',
        'congélation': 'congélation',
        'lyophilisation': 'lyophilisation',
        'déshydratation': 'déshydratation',
        'mise en conserve': 'mise en conserve',
        'saumure': 'saumure',
        'saumurage': 'saumurage',
        'salaison': 'salaison',
        'séchage': 'séchage',
        'fumage': 'fumage',
        'macération': 'macération',
        'fermentation': 'fermentation',
        'levure': 'levure',
        'levain': 'levain',
        'pâte': 'pâte',
        'pâte levée': 'pâte levée',
        'pâte feuilletée': 'pâte feuilletée',
        'pâte brisée': 'pâte brisée',
        'pâte sablée': 'pâte sablée',
        'pâte à choux': 'pâte à choux',
        'pâte à pizza': 'pâte à pizza',
        'pâte à pain': 'pâte à pain',
        'pâte à tarte': 'pâte à tarte',
        'pâte à crêpes': 'pâte à crêpes',
        'pâte à gaufres': 'pâte à gaufres',
        'pâte à beignets': 'pâte à beignets',
        'pâte à biscuits': 'pâte à biscuits',
        'pâte à gâteau': 'pâte à gâteau',
        'génoise': 'génoise',
        'biscuit': 'biscuit',
        'biscuit sec': 'biscuit sec',
        'biscuit moelleux': 'biscuit moelleux',
        'biscuit au beurre': 'biscuit au beurre',
        'biscuit au chocolat': 'biscuit au chocolat',
        'biscuit à la confiture': 'biscuit à la confiture',
        'biscuit à la vanille': 'biscuit à la vanille',
        'biscuit à la cannelle': 'biscuit à la cannelle',
        'biscuit au gingembre': 'biscuit au gingembre',
        'biscuit au citron': 'biscuit au citron',
        'biscuit à l\'orange': 'biscuit à l\'orange',
        'biscuit à la fraise': 'biscuit à la fraise',
        'biscuit à la framboise': 'biscuit à la framboise',
        'biscuit à la myrtille': 'biscuit à la myrtille',
        'biscuit à la pomme': 'biscuit à la pomme',
        'biscuit à la poire': 'biscuit à la poire',
        'biscuit à la pêche': 'biscuit à la pêche',
        'biscuit à l\'abricot': 'biscuit à l\'abricot',
        'biscuit à la cerise': 'biscuit à la cerise',
        'biscuit à la prune': 'biscuit à la prune',
        'biscuit à la figue': 'biscuit à la figue',
        'biscuit à la noix': 'biscuit à la noix',
        'biscuit à la noisette': 'biscuit à la noisette',
        'biscuit à l\'amande': 'biscuit à l\'amande',
        'biscuit à la cacahuète': 'biscuit à la cacahuète',
        'biscuit à la pistache': 'biscuit à la pistache',
        'biscuit à la noix de coco': 'biscuit à la noix de coco',
        'biscuit au chocolat blanc': 'biscuit au chocolat blanc',
        'biscuit au chocolat au lait': 'biscuit au chocolat au lait',
        'biscuit au chocolat noir': 'biscuit au chocolat noir',
        'biscuit au caramel': 'biscuit au caramel',
        'biscuit au miel': 'biscuit au miel',
        'biscuit à la mélasse': 'biscuit à la mélasse',
        'biscuit à la réglisse': 'biscuit à la réglisse',
        'biscuit à la menthe': 'biscuit à la menthe',
        'biscuit à la rose': 'biscuit à la rose',
        'biscuit au thé': 'biscuit au thé',
        'biscuit au café': 'biscuit au café',
        'biscuit au rhum': 'biscuit au rhum',
        'biscuit au kirsch': 'biscuit au kirsch',
        'biscuit au cognac': 'biscuit au cognac',
        'biscuit à l\'armagnac': 'biscuit à l\'armagnac',
        'biscuit au calvados': 'biscuit au calvados',
        'biscuit au whisky': 'biscuit au whisky',
        'biscuit au gin': 'biscuit au gin',
        'biscuit à la vodka': 'biscuit à la vodka',
        'biscuit au champagne': 'biscuit au champagne',
        'biscuit au vin rouge': 'biscuit au vin rouge',
        'biscuit au vin blanc': 'biscuit au vin blanc',
        'biscuit au vin rosé': 'biscuit au vin rosé',
        'biscuit à la bière': 'biscuit à la bière',
        'biscuit au cidre': 'biscuit au cidre',
        'biscuit au jus de pomme': 'biscuit au jus de pomme',
        'biscuit au jus d\'orange': 'biscuit au jus d\'orange',
        'biscuit au jus de citron': 'biscuit au jus de citron',
        'biscuit au jus de pamplemousse': 'biscuit au jus de pamplemousse',
        'biscuit au jus de tomate': 'biscuit au jus de tomate',
        'biscuit au jus de carotte': 'biscuit au jus de carotte',
        'biscuit au jus de betterave': 'biscuit au jus de betterave',
        'biscuit au jus de céleri': 'biscuit au jus de céleri',
        'biscuit au jus de concombre': 'biscuit au jus de concombre',
        'biscuit au jus de poivron': 'biscuit au jus de poivron',
        'biscuit au jus d\'oignon': 'biscuit au jus d\'oignon',
        'biscuit au jus d\'ail': 'biscuit au jus d\'ail',
        'biscuit au jus de gingembre': 'biscuit au jus de gingembre',
        'biscuit au jus de curcuma': 'biscuit au jus de curcuma',
        'biscuit au jus de paprika': 'biscuit au jus de paprika',
        'biscuit au jus de piment': 'biscuit au jus de piment',
        'biscuit au jus de vanille': 'biscuit au jus de vanille',
        'biscuit au jus de cannelle': 'biscuit au jus de cannelle',
        'biscuit au jus de muscade': 'biscuit au jus de muscade',
        'biscuit au jus de clou de girofle': 'biscuit au jus de clou de girofle',
        'biscuit au jus de cardamome': 'biscuit au jus de cardamome',
        'biscuit au jus d\'anis': 'biscuit au jus d\'anis',
        'biscuit au jus de fenouil': 'biscuit au jus de fenouil',
        'biscuit au jus de coriandre': 'biscuit au jus de coriandre',
        'biscuit au jus de persil': 'biscuit au jus de persil',
        'biscuit au jus de cerfeuil': 'biscuit au jus de cerfeuil',
        'biscuit au jus de ciboulette': 'biscuit au jus de ciboulette',
        'biscuit au jus de menthe': 'biscuit au jus de menthe',
        'biscuit au jus de basilic': 'biscuit au jus de basilic',
        'biscuit au jus de thym': 'biscuit au jus de thym',
        'biscuit au jus de romarin': 'biscuit au jus de romarin',
        'biscuit au jus de laurier': 'biscuit au jus de laurier',
        'biscuit au jus de sauge': 'biscuit au jus de sauge',
        'biscuit au jus de marjolaine': 'biscuit au jus de marjolaine',
        'biscuit au jus d\'origan': 'biscuit au jus d\'origan',
        'biscuit au jus de sarriette': 'biscuit au jus de sarriette',
        'biscuit au jus de livèche': 'biscuit au jus de livèche',
        'biscuit au jus d\'angélique': 'biscuit au jus d\'angélique',
        'biscuit au jus de mélisse': 'biscuit au jus de mélisse',
        'biscuit au jus de verveine': 'biscuit au jus de verveine',
        'biscuit au jus de camomille': 'biscuit au jus de camomille',
        'biscuit au jus de tilleul': 'biscuit au jus de tilleul',
        'biscuit au jus de hibiscus': 'biscuit au jus de hibiscus',
        'biscuit au jus de rose': 'biscuit au jus de rose',
        'biscuit au jus de jasmin': 'biscuit au jus de jasmin',
        'biscuit au jus de violette': 'biscuit au jus de violette',
        'biscuit au jus de lavande': 'biscuit au jus de lavande',
        'biscuit au jus de géranium': 'biscuit au jus de géranium',
        'biscuit au jus de muguet': 'biscuit au jus de muguet',
        'biscuit au jus de réséda': 'biscuit au jus de réséda',
        'biscuit au jus de myrte': 'biscuit au jus de myrte',
        'biscuit au jus de laurier-rose': 'biscuit au jus de laurier-rose',
        'biscuit au jus de gardénia': 'biscuit au jus de gardénia',
        'biscuit au jus de magnolia': 'biscuit au jus de magnolia',
        'biscuit au jus de camélia': 'biscuit au jus de camélia',
        'biscuit au jus d\'azalée': 'biscuit au jus d\'azalée',
        'biscuit au jus de rhododendron': 'biscuit au jus de rhododendron',
        'biscuit au jus d\'hortensia': 'biscuit au jus d\'hortensia',
        'biscuit au jus de pivoine': 'biscuit au jus de pivoine',
        'biscuit au jus de dahlia': 'biscuit au jus de dahlia',
        'biscuit au jus de glaïeul': 'biscuit au jus de glaïeul',
        'biscuit au jus de lys': 'biscuit au jus de lys',
        'bwa': 'arbre/bois',
        'zanimal': 'animal',
        'lozazor': 'oiseau',
        'flèr': 'fleur',
        'larivaz': 'rivière',
        'lamer': 'mer',
        'monlan': 'montagne',
        'lapli': 'pluie',
        'lonoraz': 'tonnerre',
        'larkansyel': 'arc-en-ciel',
        'van': 'vent',
        'zon': 'soleil',
        'lalinn': 'lune',
        'zetwal': 'étoile',
        'nwar': 'noir',
        'blan': 'blanc',
        'rouz': 'rouge',
        'zho': 'jaune',
        'ble': 'bleu',
        'vert': 'vert',
        'lor': 'or',
        'arzan': 'argent',
        'lakaz': 'maison',
        'zardin': 'jardin',
        'labou': 'boue',
        'lérz': 'roche',
        'sabl': 'sable',
        'fôrè': 'forêt',
        'plenn': 'plaine',
        'kaskad': 'cascade',
        'volkan': 'volcan',
        'lezil': 'île',
        'lakot': 'côte',
        'baryé': 'récif',
        'koral': 'corail',
        'krik': 'crique',
        'zanimo': 'animal',
        'chenn': 'chien',
        'chat': 'chat',
        'souris': 'souris',
        'lezan': 'insectes',
        'papillon': 'papillon',
        'aragn': 'araignée',
        'serpan': 'serpent',
        'lezard': 'lézard',
        'krapod': 'crapaud',
        'grenouill': 'grenouille',
        'sikal': 'cigale',
        'moustik': 'moustique',
        'lèz': 'lézard',
        'koko': 'coq',
        'poule': 'poule',
        'kan': 'chien',
        'chval': 'cheval',
        'zébr': 'zèbre',
        'lion': 'lion',
        'tigr': 'tigre',
        'léléfan': 'éléphant',
        'siraf': 'girafe',
        'singe': 'singe',
        'bik': 'bœuf',
        'vach': 'vache',
        'mouton': 'mouton',
        'chèvr': 'chèvre',
        'kochon': 'cochon',
        'lapen': 'lapin',
        'cerf': 'cerf',
        'bich': 'biche',
        'loup': 'loup',
        'renar': 'renard',
        'our': 'ours',
        'laman': 'requin',
        'balen': 'baleine',
        'dofen': 'dauphin',
        'tortu': 'tortue',
        'krab': 'crabe',
        'langoust': 'langouste',
        'ourit': 'pieuvre',
        'kalmar': 'calmar',
        'korn': 'corne',
        'pied': 'pied',
        'zil': 'œil',
        'bouch': 'bouche',
        'nez': 'nez',
        'loréy': 'oreille',
        'chev': 'cheveux',
        'lapo': 'peau',
        'zan': 'dent',
        'lépang': 'langue',
        'lé': 'sang',
        'kè': 'cœur',
        'poumon': 'poumon',
        'léstri': 'estomac',
        'sé': 'intestins',
        'bwa': 'os',
        'klé': 'clé',
        'pòrt': 'porte',
        'fénètr': 'fenêtre',
        'toit': 'toit',
        'mur': 'mur',
        'solyé': 'sol',
        'lakou': 'cour',
        'rout': 'route',
        'chinmin': 'chemin',
        'pon': 'pont',
        'lékòl': 'école',
        'lopital': 'hôpital',
        'lamari': 'mairie',
        'légliz': 'église',
        'lapost': 'poste',
        'labank': 'banque',
        'magasin': 'magasin',
        'marché': 'marché',
        'restoran': 'restaurant',
        'otèl': 'hôtel',
        'kinnema': 'cinéma',
        'mizé': 'musée',
        'bibliyotèk': 'bibliothèque',
        'park': 'parc',
        'plas': 'place',
        'stad': 'stade',
        'pist': 'aéroport',
        'gaz': 'station-service',
        'arèt-bis': 'arrêt de bus',
        'taxi': 'taxi',
        'bus': 'bus',
        'minibus': 'minibus',
        'voitur': 'voiture',
        'moto': 'moto',
        'bisiklèt': 'bicyclette',
        'bato': 'bateau',
        'navir': 'navire',
        'avion': 'avion',
        'élykoptèr': 'hélicoptère',
        'tyren': 'train',
        'tram': 'tramway',
        'métro': 'métro',

        // Time and Weather
        'lindi': 'lundi',
        'mardi': 'mardi',
        'merkredi': 'mercredi',
        'zedi': 'jeudi',
        'vandredi': 'vendredi',
        'samdi': 'samedi',
        'dimans': 'dimanche',
        'zanvi': 'janvier',
        'fevriye': 'février',
        'mars': 'mars',
        'avril': 'avril',
        'me': 'mai',
        'zin': 'juin',
        'zilye': 'juillet',
        'out': 'août',
        'septam': 'septembre',
        'oktob': 'octobre',
        'novam': 'novembre',
        'desam': 'décembre',
        'lézanné': 'l\'année',
        'lmwa': 'le mois',
        'lasémenn': 'la semaine',
        'lzour': 'le jour',
        'lanuit': 'la nuit',
        'lèr': 'temps',
        'momant': 'moment',
        'matin': 'matin',
        'laprémidi': 'après-midi',
        'swar': 'soir',
        'midi': 'midi',
        'minwi': 'minuit',
        'bofor': 'avant',
        'aprésa': 'après',
        'koman': 'quand/comment',
        'kan': 'quand',
        'alèr': 'alors',
        'anmwin': 'pendant ce temps',
        'aktièlman': 'actuellement',
        'souvan': 'souvent',
        'parfoi': 'parfois',
        'rar': 'rarement',
        'touzour': 'toujours',
        'zamè': 'jamais',
        'jòdla': 'aujourd\'hui',
        'yèr': 'hier',
        'demin': 'demain',
        'aprdemin': 'après-demain',
        'avanyèr': 'avant-hier',
        'lasézon': 'la saison',
        'livé': 'été',
        'livèr': 'hiver',
        'loton': 'automne',
        'laprintan': 'printemps',
        'fè': 'chaud',
        'frèt': 'froid',
        'bon': 'bon',
        'mové': 'mauvais',
        'bwa': 'venteux',
        'plenouaz': 'nuageux',
        'soléy': 'ensoleillé',
        'lapli': 'pluvieux',
        'loraz': 'orage',
        'tèrfom': 'tremblement de terre',
        'siklon': 'cyclone/ouragan',
        'razdemaré': 'raz de marée/tsunami',
        'innondasyon': 'inondation',
        'sècherès': 'sécheresse',
        'oraz': 'tempête',
        'briz': 'brise',
        'brouyar': 'brouillard',
        'nwaz': 'brume',
        'ròzéman': 'rosée',
        'glasyé': 'glace',
        'lanèz': 'neige',
        'grèl': 'grêle',
        'arkansyel': 'arc-en-ciel',
        'léklèr': 'éclair',
        'lonoraz': 'tonnerre',
        'van': 'vent',
        'lapli': 'pluie',
        'zon': 'soleil',
        'lalinn': 'lune',
        'zetwal': 'étoile',
        'linivèr': 'univers',
        'galaksi': 'galaxie',
        'sistém solèr': 'système solaire',
        'latèr': 'terre',
        'planèt': 'planète',
        'satelit': 'satellite',
        'komèt': 'comète',
        'astéroyid': 'astéroïde',
        'météorit': 'météorite',
        'trou nwèr': 'trou noir',
        'nébilèz': 'nébuleuse',
        'kosmos': 'cosmos',
        'éspas': 'espace',
        'anfini': 'infini',
        'éternité': 'éternité',
        'zéro': 'zéro',
        'inn': 'un',
        'dè': 'deux',
        'trwa': 'trois',
        'kat': 'quatre',
        'senk': 'cinq',
        'sis': 'six',
        'sèt': 'sept',
        'wit': 'huit',
        'nèf': 'neuf',
        'dis': 'dix',
        'on': 'onze',
        'douz': 'douze',
        'trèz': 'treize',
        'katòz': 'quatorze',
        'kenz': 'quinze',
        'sèz': 'seize',
        'dizèt': 'dix-sept',
        'dizwit': 'dix-huit',
        'diznèf': 'dix-neuf',
        'ven': 'vingt',
        'vent-inn': 'vingt-et-un',
        'trant': 'trente',
        'karant': 'quarante',
        'senkant': 'cinquante',
        'souasant': 'soixante',
        'karant-ven': 'quatre-vingt',
        'katsan': 'cent',
        'dé-katsan': 'deux cents',
        'mil': 'mille',
        'dé-mil': 'deux mille',
        'on milyon': 'un million',
        'premyé': 'premier',
        'dèzyèm': 'deuxième',
        'trwazyèm': 'troisième',
        'katriyèm': 'quatrième',
        'senkyèm': 'cinquième',
        'sizyèm': 'sixième',
        'sètyèm': 'septième',
        'uityèm': 'huitième',
        'nevyèm': 'neuvième',
        'dizyèm': 'dixième',
        'dèrnyé': 'dernier',
        'pakè': 'quelques',
        'ben': 'beaucoup',
        'anpil': 'beaucoup',
        'tros': 'trop',
        'pwi': 'un peu',
        'loin': 'loin',
        'près': 'près',
        'i': 'ici',
        'la': 'là',
        'partout': 'partout',
        'nyèrpartout': 'nulle part',
        'koté': 'côté',
        'anlé': 'au-dessus',
        'anba': 'en dessous',
        'andan': 'dedans',
        'andé': 'dehors',
        'devan': 'devant',
        'dèryèr': 'derrière',
        'antre': 'entre',
        'parmi': 'parmi',
        'kont': 'contre',
        'sou': 'sous',
        'sur': 'sur',
        'dans': 'dans',
        'ak': 'avec',
        'san': 'sans',
        'pour': 'pour',
        'par': 'par',
        'a': 'à',
        'de': 'de',
        'dépi': 'depuis',
        'juska': 'jusqu\'à',
        'avan': 'avant',
        'aprè': 'après',
        'ki': 'qui',
        'kosa': 'quoi',
        'ki koté': 'où',
        'kan': 'quand',
        'koman': 'comment',
        'poukwa': 'pourquoi',
        'kanmwin': 'combien',
        'ki lè': 'quelle heure',
        'ki nonm': 'quel homme',
        'ki la': 'à qui',
        'ki bann': 'lesquels',
        'kossa': 'quoi (informel)',
        'kofé': 'pourquoi (informel)',
        'komentsa': 'comment (informel)',
        'ki pé': 'qui peut',
        'ki vlé': 'qui veut',
        'ki sa': 'qu\'est-ce que c\'est',
        'sa ki': 'qui est-ce',
        'ki dir': 'qu\'as-tu dit',
        'ki bann la': 'que sont ceux-là',
        'é': 'et',
        'mé': 'mais',
        'ou': 'ou',
        'si': 'si',
        'parék': 'parce que',
        'alors': 'alors',
        'donk': 'donc',
        'kar': 'car',
        'konsékan': 'conséquemment',
        'mémsi': 'même si',
        'tandisk': 'tandis que',
        'pandan': 'pendant',
        'fin': 'afin que',
        'afin': 'afin de',
        'osinon': 'sinon',
        'nein': 'ni',
        'so': 'soit',
        'so... so...': 'soit... soit...',
        'ni... ni...': 'ni... ni...',
        'pa selman... mé osi': 'non seulement... mais aussi',
        'konm': 'comme',
        'pari': 'par rapport à',
        'akonpan': 'accompagné de',
        'gras a': 'grâce à',
        'malgré': 'malgré',
        'sanz': 'sans',
        'lo': 'loin de',
        'prè': 'près de',
        'vizav': 'en face de',
        'a koté': 'à côté de',
        'anviron': 'autour de',
        'otr': 'autre que',
        'sak': 'sauf',
        'pandan': 'pendant',
        'avan': 'avant',
        'aprè': 'après',
        'just aprè': 'juste après',
        'just avan': 'juste avant',
        'dipi': 'depuis',
        'jiska': 'jusqu\'à',
        'a partir de': 'à partir de',
        'a': 'à',
        'de': 'de',
        'a la': 'à la',
        'au': 'au',
        'dans': 'dans',
        'sur': 'sur',
        'sou': 'sous',
        'anba': 'en dessous',
        'anlé': 'au-dessus',
        'par': 'par',
        'pour': 'pour',
        'avec': 'avec',
        'sans': 'sans',
        'chez': 'chez',
        'entre': 'entre',
        'parmi': 'parmi',
        'contre': 'contre',
        'vers': 'vers',
        'selon': 'selon',
        'hors': 'hors de',
        'dedan': 'dedans',
        'dehors': 'dehors',
        'partout': 'partout',
        'quelque part': 'quelque part',
        'nulle part': 'nulle part',
        'ici': 'ici',
        'là': 'là',
        'là-bas': 'là-bas',
        'd ici': 'd\'ici',
        'de là': 'de là',
        'jusqu ici': 'jusqu\'ici',
        'jusqu  là': 'jusqu\'là',
        'depuis': 'depuis',
        'depuis quand': 'depuis quand',
        'depuis longtemps': 'depuis longtemps',
        'depuis peu': 'depuis peu',
        'pendant que': 'pendant que',
        'avant que': 'avant que',
        'après que': 'après que',
        'aussitôt que': 'aussitôt que',
        'chaque fois que': 'chaque fois que',
        'la première fois que': 'la première fois que',
        'la dernière fois que': 'la dernière fois que',
        'toutes les fois que': 'toutes les fois que',
        'bien que': 'bien que',
        'quoique': 'bien que',
        'même si': 'même si',
        'comme si': 'comme si',
        'si... que': 'si... que',
        'tellement... que': 'tellement... que',
        'trop... pour': 'trop... pour',
        'assez... pour': 'assez... pour',
        'prêt à': 'prêt à',
        'en train de': 'en train de',
        'sur le point de': 'sur le point de',
        'obliger de': 'obligé de',
        'forcer de': 'forcé de',
        'habitué à': 'habitué à',
        'sensé': 'sensé',
        'capab de': 'capable de',
        'en mesure de': 'en mesure de',
        'dans l\'impossibilité de': 'dans l\'impossibilité de',
        'faute de': 'faute de',
        'à cause de': 'à cause de',
        'en raison de': 'en raison de',
        'grâce à': 'grâce à',
        'en dépit de': 'en dépit de',
        'au lieu de': 'au lieu de',
        'à force de': 'à force de',
        'faute de': 'faute de',
        'par manque de': 'par manque de',
        'par excès de': 'par excès de',
        'au risque de': 'au risque de',
        'dans le but de': 'dans le but de',
        'dans l\'espoir de': 'dans l\'espoir de',
        'en vue de': 'en vue de',
        'pour ce qui est de': 'pour ce qui est de',
        'quant à': 'quant à',
        'en ce qui concerne': 'en ce qui concerne',
        'au sujet de': 'au sujet de',
        'touchant': 'touchant',
        'relativement à': 'relativement à',
        'vis-à-vis de': 'vis-à-vis de',
        'par rapport à': 'par rapport à',
        'en fonction de': 'en fonction de',
        'selon': 'selon',
        'conformément à': 'conformément à',
        'suivant': 'suivant',
        'outre': 'outre',
        'en plus de': 'en plus de',
        'y compris': 'y compris',
        'notamment': 'notamment',
        'spécialement': 'spécialement',
        'particulièrement': 'particulièrement',
        'surtout': 'surtout',
        'principalement': 'principalement',
        'essentiellement': 'essentiellement',
        'fondamentalement': 'fondamentalement',
        'généralement': 'généralement',
        'habituellement': 'habituellement',
        'normalement': 'normalement',
        'ordinairement': 'ordinairement',
        'couramment': 'couramment',
        'fréquemment': 'fréquemment',
        'régulièrement': 'régulièrement',
        'occasionnellement': 'occasionnellement',
        'rarement': 'rarement',
        'exceptionnellement': 'exceptionnellement',
        'parfois': 'parfois',
        'de temps en temps': 'de temps en temps',
        'de temps à autre': 'de temps à autre',
        'temps à autre': 'de temps à autre',
        'jamais': 'jamais',
        'ne... jamais': 'ne... jamais',
        'toujours': 'toujours',
        'toujours est-il que': 'toujours est-il que',
        'en tout cas': 'en tout cas',
        'dans tous les cas': 'dans tous les cas',
        'dans tous les cas de figure': 'dans tous les cas de figure',
        'quoi qu\'il en soit': 'quoi qu\'il en soit',
        'en définitive': 'en définitive',
        'finalement': 'finalement',
        'au final': 'au final',
        'à la fin': 'à la fin',
        'à terme': 'à terme',
        'sur le long terme': 'sur le long terme',
        'sur le court terme': 'sur le court terme',
        'à court terme': 'à court terme',
        'à moyen terme': 'à moyen terme',
        'à long terme': 'à long terme',
        'dès maintenant': 'dès maintenant',
        'désormais': 'désormais',
        'à partir de maintenant': 'à partir de maintenant',
        'à compter de ce jour': 'à compter de ce jour',
        'd\'ores et déjà': 'd\'ores et déjà',
        'déjà': 'déjà',
        'encore': 'encore',
        'ne... plus': 'ne... plus',
        'ne... point': 'ne... point',
        'ne... guère': 'ne... guère',
        'ne... nulle part': 'ne... nulle part',
        'ne... jamais': 'ne... jamais',
        'ne... rien': 'ne... rien',
        'ne... personne': 'ne... personne',
        'ne... que': 'ne... que',
        'ne... aucun': 'ne... aucun',
        'ne... nul': 'ne... nul',
        'seulement': 'seulement',
        'uniquement': 'uniquement',
        'simplement': 'simplement',
        'juste': 'juste',
        'exactement': 'exactement',
        'précisément': 'précisément',
        'approximativement': 'approximativement',
        'environ': 'environ',
        'à peu près': 'à peu près',
        'presque': 'presque',
        'quasiment': 'quasiment',
        'pratiquement': 'pratiquement',
        'virtuellement': 'virtuellement',
        'réellement': 'réellement',
        'réellement': 'réellement',
        'effectivement': 'effectivement',
        'vraiment': 'vraiment',
        'sincèrement': 'sincèrement',
        'franchement': 'franchement',
        'honnêtement': 'honnêtement',
        'carrément': 'carrément',
        'absolument': 'absolument',
        'certainement': 'certainement',
        'sûrement': 'sûrement',
        'probablement': 'probablement',
        'peut-être': 'peut-être',
        'éventuellement': 'éventuellement',
        'potentiellement': 'potentiellement',
        'naturellement': 'naturellement',
        'logiquement': 'logiquement',
        'normalement': 'normalement',
        'évidemment': 'évidemment',
        'bien sûr': 'bien sûr',
        'bien entendu': 'bien entendu',
        'sans doute': 'sans doute',
        'sans aucun doute': 'sans aucun doute',
        'indubitablement': 'indubitablement',
        'certainement': 'certainement',
        'assurément': 'assurément',
        'manifestement': 'manifestement',
        'clairement': 'clairement',
        'nettement': 'nettement',
        'distinctement': 'distinctement',
        'précisément': 'précisément',
        'exactement': 'exactement',
        'spécifiquement': 'spécifiquement',
        'particulièrement': 'particulièrement',
        'spécialement': 'spécialement',
        'notamment': 'notamment',
        'surtout': 'surtout',
        'principalement': 'principalement',
        'essentiellement': 'essentiellement',
        'fondamentalement': 'fondamentalement',
        'généralement': 'généralement',
        'habituellement': 'habituellement',
        'couramment': 'couramment',
        'fréquemment': 'fréquemment',
        'régulièrement': 'régulièrement',
        'occasionnellement': 'occasionnellement',
        'rarement': 'rarement',
        'exceptionnellement': 'exceptionnellement',
        'parfois': 'parfois',
        'de temps en temps': 'de temps en temps',
        'temps à autre': 'de temps à autre',
        'de temps à autre': 'de temps à autre',
        'parfois': 'parfois',
    }
}